### ISSUE TITLE
Format txt ids

### ISSUE THREAD

**Issue by mecoolmendi** [V4NSH4J/discord-mass-DM-GO#1]

**Comment by V4NSH4J** [comment]
Yes 

One User ID on each line!

**Comment by mecoolmendi** [comment]
do you have discord server?

**Comment by V4NSH4J** [comment]
> 
> 
> do you have discord server?

I don't yet, but I should probably make one

**Comment by mecoolmendi** [comment]
i have an issue, when starts to dm, works well with 2 delay, 5 seconds, and stucked and still not continues


Do you know why? thanks

**Comment by mecoolmendi** [comment]
maybe rate limited?

**Comment by V4NSH4J** [comment]
> 
> 
> i have an issue, when starts to dm, works well with 2 delay, 5 seconds, and stucked and still not continues
> 
> Do you know why? thanks

Do your tokens work? 
https://discord.gg/YRzYfV7e
Discord server for better coms
