### ISSUE TITLE
How do I need to put in my proxies?

### ISSUE THREAD

**Issue by Mohammad12134** [V4NSH4J/discord-mass-DM-GO#101]
Hello.
Whenever i type in my proxies, it sends out that i'm using an invalid port. I use proxies with ip:port:username:password, but it seems like it just needs ip:port. How do i bypass this?
Also another thing:
- Do i need to use a specific type of proxy? (SOCKS5, HTTP)

**Comment by V4NSH4J** [comment]
Hi, the format for proxies is username:password@IP:port
And HTTP(S) proxies are supported.

**Comment by camolot13** [comment]
@V4NSH4J proxy ware dont give the username password and ive saw to use it many times in here
