### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by manisakurdu** [V4NSH4J/discord-mass-DM-GO#103]
Hello i cant use "pip install discum" command
![image](https://user-images.githubusercontent.com/97475567/150699169-45525f67-5fef-466e-95c9-b0ee38e4cab6.png)

**Comment by seanthakid** [comment]
you gotta download python

**Comment by manisakurdu** [comment]
ser i download spyder python

**Comment by manisakurdu** [comment]
![image](https://user-images.githubusercontent.com/97475567/150699730-5212f55a-60aa-4470-92ca-2e68cca21fd5.png)
