### ISSUE TITLE
scraping memberids

### ISSUE THREAD

**Issue by grx7** [V4NSH4J/discord-mass-DM-GO#104]
Whats the best way to scrape members from a discord server? I am using Discum python script as per video.
members = get_members('906253007350558750', '906253008105508897')
memberslist = []

however, if for a selected channel only. How to scrape entire server and not just per channel scrape?

**Comment by V4NSH4J** [comment]
Use offline scraper included in DMDGO V1. 0.7 and higher

**Comment by seanthakid** [comment]
discum scraper dosnt work use built in scraper

**Comment by grx7** [comment]
got it. @V4NSH4J what does this error mean? https://imgur.com/rlnN3aF

**Comment by V4NSH4J** [comment]
> got it. @V4NSH4J what does this error mean? https://imgur.com/rlnN3aF Also where are they stored once scraped in offline mode(3)?

Hi, this is an error on an older version. You should update your DMDGO
