### ISSUE TITLE
Best config and proxy setup to avoid tokens being locked

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#106]
was wondering if anyone knows the best config and proxy setup to avoid tokens being locked. Thank you for this amazing resource!

**Comment by V4NSH4J** [comment]
Hey, you can't completely avoid generated tokens from getting locked. At some point, they will get locked.
You can use any proxy service like packetstream or proxiware or iproyal for proxies. DMDGO was tested on proxiware proxies but they're a more expensive option. 
The delays I personally use are 60 individual and rate limit. It's the maximum speed and efficiency. You can find my whole config under examples in the readme.

**Comment by pscpc** [comment]
I'm using 30 individual, 300 rate_limit and 400 offset.
