### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Y234333** [V4NSH4J/discord-mass-DM-GO#107]
Hello, I keep getting this message when I try to run the .exe program. What do I do?

![Capture](https://user-images.githubusercontent.com/80032443/150748472-44742708-6806-41a1-a929-ad61f046a01a.PNG)

**Comment by seanthakid** [comment]
turn McAfee screen scanning off

**Comment by Y234333** [comment]
@seanthakid I don't use McAfee. I will try disabling my other antivirus and trying again.

**Comment by Y234333** [comment]
Update: I disabled my antivirus and it worked thank you!
