### ISSUE TITLE
Failed to send message

### ISSUE THREAD

**Issue by Eddie009** [V4NSH4J/discord-mass-DM-GO#11]
Hi
Thanks for your kind help. I am trying the code and followed every step, but i am getting an error "Failed to send message from Token". I have checked my token, its valid. Please help

**Comment by V4NSH4J** [comment]
Hey, could you elaborate a bit? Which mode are you using? Any error codes?
I recommend checking your `message.json` file, try with the default message once as well. Let me know

**Comment by Eddie009** [comment]
Thanks a lot Bro, problem was with embed message, edited default message and it worked..

**Comment by V4NSH4J** [comment]
No worries! Feel free to open another issue if you face any other problems!
