### ISSUE TITLE
Enter your tokens in tokens.txt error

### ISSUE THREAD

**Issue by manisakurdu** [V4NSH4J/discord-mass-DM-GO#110]
i already enter my tokens in tokens.txt but its giving me this error

![image](https://user-images.githubusercontent.com/97475567/150794767-efad9268-9980-4967-bf78-9ccd2dc14d54.png)

**Comment by V4NSH4J** [comment]
Hi, it's some problem with read/write permissions on your computer. 
If you checkout #107 and #87 people who faced similar problems solved it by disabling their anti-virus software. Feel free to add dmdgo as an exception or running it on a VM/sandbox.
