### ISSUE TITLE
Add function for each token to send a message to some channel within a server.

### ISSUE THREAD

**Issue by GhostGkali** [V4NSH4J/discord-mass-DM-GO#112]

**Comment by V4NSH4J** [comment]
Duplicate #68

**Comment by ciribo-sys** [comment]
hey bro sorry for writing here , i want to ask you something .. i ve seen people who dm immediatly after i join a server even if the server has no "Welcome" channel , i have checked the reacts button but seems that is not showing exactly who is the last person who joined server.. i am so confused

**Comment by V4NSH4J** [comment]
> hey bro sorry for writing here , i want to ask you something .. i ve seen people who dm immediatly after i join a server even if the server has no "Welcome" channel , i have checked the reacts button but seems that is not showing exactly who is the last person who joined server.. i am so confused

There is a gateway event when someone reacts.
