### ISSUE TITLE
Tokens keep getting locked even after they are just generated and verified. Could it be my proxies?

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#114]
Tokens keep getting locked even after they are just generated and verified. Could it be my proxies that are flagged?

**Comment by V4NSH4J** [comment]
> Tokens keep getting locked even after they are just generated and verified. Could it be my proxies that are flagged?

It could be anything. If you're using a GitHub gen then chances are it's not even generating unlocked accounts. Or they could be verified on a flagged domain. It could really be anything
