### ISSUE TITLE
Error while joining/getting response from cookies request

### ISSUE THREAD

**Issue by loom4k** [V4NSH4J/discord-mass-DM-GO#115]
Hey! I was trying to setup everything and I am getting this error. I inputed a few proxies I found online but it's always prompting me this message 😭 

Can anyone help?

![image](https://user-images.githubusercontent.com/58235265/150892368-f03cd432-ab6f-4e98-9fa1-1b63179b2fa4.png)

**Comment by V4NSH4J** [comment]
Please don't use proxies then using free ones
