### ISSUE TITLE
Token Onliner

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#116]
Hello, when i try token onlineer after 150-200 tokens i get errors like this.
websocket: close 1006 (normal)
websocket: close 1000 (normal)
Error while opening websocket: failed to create websocket connection: unexpected EOF

Should i worry?

**Comment by V4NSH4J** [comment]
If they're connected and this happens, they try reconnecting on their own. Still I'd say to invite them to an empty server to see how many are online.
