### ISSUE TITLE
token.txt error

### ISSUE THREAD

**Issue by genius4441** [V4NSH4J/discord-mass-DM-GO#117]
Have done as previous advise and removed anti-virus, but still having this error on option 13, when searching for tokens

Enter your choice:
13
Check if your tokens are still in the server
[04:54:21] Error while getting necessary data: no tokens found in tokens.txt

Press ENTER to EXIT

What to do?
![2022-01-25 (5)](https://user-images.githubusercontent.com/98368255/150896479-a742de42-1658-4f95-b7b2-6ba587f1c880.png)

**Comment by pscpc** [comment]
you need to add your tokens to \input\tokens.txt

**Comment by genius4441** [comment]
> you need to add your tokens to \input\tokens.txt

But where do I get the tokens from?

**Comment by pscpc** [comment]
from internet

**Comment by genius4441** [comment]
> from internet

I put my token? or I need to find tokens? My issue is the latter, I don't know where to find online the tokens that are real

**Comment by pscpc** [comment]
> > from internet
> 
> I put my token? or I need to find tokens? My issue is the latter, I don't know where to find online the tokens that are real

find tokens

**Comment by genius4441** [comment]
> > > from internet
> > 
> > 
> > I put my token? or I need to find tokens? My issue is the latter, I don't know where to find online the tokens that are real
> 
> find tokens

where

**Comment by pscpc** [comment]
you are genius, you can figure it out how

**Comment by V4NSH4J** [comment]
You have to put tokens into tokens.txt
