### ISSUE TITLE
Offline scraper (mode 3)

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#118]
Getting this error:
![image](https://user-images.githubusercontent.com/89306625/151012820-0dd0a08f-ba6a-4905-87d9-941508c221c5.png)
Any syggestions? 
Cheers ✌️

**Comment by V4NSH4J** [comment]
Hi, it just retries to reconnect if this happens, no members are lost. This is only a problem if your program crashes after this (which was also solved in the DMDGO V1.0.7.4 patch)
