### ISSUE TITLE
Antivirus blocks windows zip 

### ISSUE THREAD

**Issue by StefosGeo** [V4NSH4J/discord-mass-DM-GO#12]
Hello, 

I tried to download the windows version, but my antivirus blocks the download. Is this a known issue ?

Thank you

**Comment by m1zr** [comment]
file infected with malware...

**Comment by V4NSH4J** [comment]
Hey guys, this is a known issue. As GO is a relatively new language the Anti-Virus software are often not able to understand it's Binary's structure. 
Here's it explained in the official GO documents: https://go.dev/doc/faq#virus

What I can assure you is that the file is safe to download however don't take my word for it. Feel free to browse through the source code and compile yourself. Instructions on compilation are also provided in  the Readme. 
Alternatively to stay safe, you can use Virtual Machines.
