### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by badudidudi1** [V4NSH4J/discord-mass-DM-GO#120]
hey how can use it on mac?

**Comment by iulianulplay** [comment]
You can build from source if there's no version for mac, check the readme guide

**Comment by V4NSH4J** [comment]
^ Yes you can build from source. We also have pre-built versions in the releases. 
The Darwin files are for macOs. The AMD64 file is for intel processors and ARM64 is for the new M1 chips 
Once downloaded, you'd have to provide dmdgo permissions to run as a program which can be done with this command 
```chmod +x ./discord-mass-dm-GO```
Or by going into properties and permitting it there. 
Once permitted, you can simply execute the binary by doing 
```./discord-mass-dm-GO```
