### ISSUE TITLE
Error while changing name

### ISSUE THREAD

**Issue by chonker11** [V4NSH4J/discord-mass-DM-GO#122]
Hey i keep getting this error while changing name :401 unauthorized

**Comment by V4NSH4J** [comment]
This can mean that your token is wrong or your password is wrong

**Comment by chonker11** [comment]
very weird as all the other features work fine with the format and tokens. Iv got another question how can people send out so many dm's of quantities of 100k if dealing with thousands of tokens? just getting them all in the server to join is pretty hard unless a really slow delay

**Comment by V4NSH4J** [comment]
> very weird as all the other features work fine with the format and tokens. Iv got another question how can people send out so many dm's of quantities of 100k if dealing with thousands of tokens? just getting them all in the server to join is pretty hard unless a really slow delay

They usually don't spam servers which need you joining with delay. If they do, they used aged/phone verified accounts. Sending 100k DMs isn't hard, just find a big server without anti-raid, use offline scraper and spam them all.
