### ISSUE TITLE
Socket connection issue

### ISSUE THREAD

**Issue by ganynmednet** [V4NSH4J/discord-mass-DM-GO#125]
![image](https://user-images.githubusercontent.com/51125243/151249077-82e3c143-05b7-49e8-8240-6e0160208b5c.png)

what could be the reason? encounter this from time to time

Thanks!

**Comment by V4NSH4J** [comment]
Heyo, if you're websocketing because of the 400 Unauthorised error, I recommend using the dedicated option for doing so, run it for 10-20 seconds. Also if there's some error while opening websocket, it would mostly retry.

**Comment by ganynmednet** [comment]
> Heyo, if you're websocketing because of the 400 Unauthorised error, I recommend using the dedicated option for doing so, run it for 10-20 seconds. Also if there's some error while opening websocket, it would mostly retry.

What is the "dedicated option"? Thank you!

**Comment by ArshBansal** [comment]
Still no fix 
![image](https://user-images.githubusercontent.com/60055960/151769559-69635532-c435-4085-9344-5c09bd687e4b.png)
