### ISSUE TITLE
Name Changer

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#126]
Yesterday i would like to change my tokens names. After that all my tokens in tokens.txt are gone. I mean they all died. Is there a bug or?

**Comment by V4NSH4J** [comment]
I don't think there's anything in the name changer code which would empty the tokens.txt file.

**Comment by CssHammer** [comment]
he means his tokens locked i guess

**Comment by V4NSH4J** [comment]
Hmmm, the name changer isn't locking tokens as of now. It could be that you ran the token checker in the email:pass:token format which the program thought were invalid

**Comment by pscpc** [comment]
no, i checked them as "token" format. (i know the token checker dont properly work while email:pass:token format).

**Comment by V4NSH4J** [comment]
So what's the problem? Did the name changer lock them or they just disappeared from tokens.txt?

**Comment by CssHammer** [comment]
i also tried it. i guess it was just a wrong token format. btw it is really weird that half of the functions accept ONLY login:pass:token format and other half doesnt... had to edit the code to make it work properly

**Comment by V4NSH4J** [comment]
> i also tried it. i guess it was just a wrong token format. btw it is really weird that half of the functions accept ONLY login:pass:token format and other half doesnt... had to edit the code to make it work properly

The functions have it written in front of them which format they accept. And you have option 6 to convert email:pass:token to token format.

**Comment by qwanysh** [comment]
> he means his tokens locked i guess

could you explain what is difference between "locked" and "banned" please?

**Comment by V4NSH4J** [comment]
> > i also tried it. i guess it was just a wrong token format. btw it is really weird that half of the functions accept ONLY login:pass:token format and other half doesnt... had to edit the code to make it work properly
> 
> The functions have it written in front of them which format they accept. And you have option 6 to convert email:pass:token to token format.

The whole program works only on token format. It's only the name changer which needs the password. It's not by choice that some functions work with it, it's a necessity

**Comment by V4NSH4J** [comment]
> > he means his tokens locked i guess
> 
> could you explain what is difference between "locked" and "banned" please?

Synonymous in this case, but generally locked means when you're phone locked by discord, disabled means when discord deletes your account and banned means when you're banned from a server

**Comment by pscpc** [comment]
> So what's the problem? Did the name changer lock them or they just disappeared from tokens.txt?

yes. exactly

**Comment by pscpc** [comment]
they locked

**Comment by V4NSH4J** [comment]
> they locked

Did you run the token checker after changing names?

**Comment by pscpc** [comment]
yes. you know the tokens.txt is empty. i copied the tokens from origin txt and pasted again in tokens.txt. but they _all_ seems locked.

**Comment by V4NSH4J** [comment]
> yes. you know the tokens.txt is empty. i copied the tokens from origin txt and pasted again in tokens.txt. but they _all_ seems locked.

Maybe they were flagged? I just changed 1K tokens to my name to try, seemed fine

**Comment by pscpc** [comment]
okay, i will try again on latest version.

**Comment by theroney** [comment]
hi, i just had this problem and got here, still same. i do name change and only 43 out of 150 tokens are alive.

actually name + pfp and they are directly "invalid"

**Comment by theroney** [comment]
> > yes. you know the tokens.txt is empty. i copied the tokens from origin txt and pasted again in tokens.txt. but they _all_ seems locked.
> 
> Maybe they were flagged? I just changed 1K tokens to my name to try, seemed fine

what was the number of "instances" while doing this?

**Comment by theroney** [comment]
> Yesterday i would like to change my tokens names. After that all my tokens in tokens.txt are gone. I mean they all died. Is there a bug or?

> Maybe they were flagged? I just changed 1K tokens to my name to try, seemed fine

Additionally, did you "spoof" the "unicode" characters in this process?

**Comment by theroney** [comment]
In addition, the tool that starts with "9p**" is detected, its maker said it is "debugging" for now, it has told users not to use it for now. I think discord has updated some things.

**Comment by V4NSH4J** [comment]
> In addition, the tool that starts with "9p**" is detected, its maker said it is "debugging" for now, it has told users not to use it for now. I think discord has updated some things. ![unknown](https://user-images.githubusercontent.com/38818937/151638616-64a0eabb-3d23-4ac8-8257-b929e5bbeab5.png)

Yes, but DMDGO is working

**Comment by V4NSH4J** [comment]
> hi, i just had this problem and got here, still same. i do name change and only 43 out of 150 tokens are alive.
> 
> actually name + pfp and they are directly "invalid"

Maybe your emails were flagged too? Could you try joining a couple servers to see if the tokens get locked

**Comment by jonahbill22** [comment]
Maybe this is also a proxy problem?

**Comment by V4NSH4J** [comment]
> Maybe this is also a proxy problem?

Shouldn't be
