### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by Chalinoo** [V4NSH4J/discord-mass-DM-GO#127]
I know embeded messages have been removed, is it still possible to include a picture in in the text your sending (without the link to that image being visible)?
If so, could you please explain how?

Thanks a lot for this great free bot!

**Comment by pscpc** [comment]
i dont think so

**Comment by V4NSH4J** [comment]
In content, you can add anything you'd add as a regular discord message and it would look the same. There's one way of attaching images on discord client which isn't implemented.

Tl;Dr -> anything you can write as message on discord you can put on it

**Comment by Chalinoo** [comment]
Yes I understand, and I do have the picture in the text. But it shows the link to the picture above it which is kinda ugly, is it possible to hide the link or something were the link disappears?

**Comment by V4NSH4J** [comment]
> Yes I understand, and I do have the picture in the text. But it shows the link to the picture above it which is kinda ugly, is it possible to hide the link or something were the link disappears?

You could do the \u200b thing in spoilers which would hide the link. But other than that, I don't think there's anyway right now.
