### ISSUE TITLE
Issues with the Joiner and the Scraper <3

### ISSUE THREAD

**Issue by AXS13** [V4NSH4J/discord-mass-DM-GO#13]
Hi V4NSH4J,
firstly thanks for your amazing tool,
I'm having two issues, I have a few totally VALID tokens but when i'm trying to make them join a server I got this error : 

Error while unmarshalling body invalid character 'e' looking for beginning of value
[04:07:00] Error while joining: invalid character 'e' looking for beginning of value

![image](https://user-images.githubusercontent.com/94145216/146482260-fbde4022-7ab1-406e-8170-a402dbfc21c2.png)

I'm also having an error with the scraper, both server id and channel id are correct, when there is no token in the token input the program runs correctly I believe but when I add my token I got a few errors : 

![image](https://user-images.githubusercontent.com/94145216/146482568-8dcb14ef-7cb3-48c7-9f1f-6c8c43267486.png)

Thanks a lot ! <3

**Comment by V4NSH4J** [comment]
Hey! Thank you for making this issue. 
The first error, "error while unmarshalling body invalid character 'e'" is in most cases the cloudflare rate limit. Using VPN/Proxy would solve this. 

I'm not so sure about the second error. Can you ensure python was installed correctly? Join the discord support server so I can take a closer look as well 
https://discord.gg/Hkzt98CThv
