### ISSUE TITLE
invalid header error

### ISSUE THREAD

**Issue by manisakurdu** [V4NSH4J/discord-mass-DM-GO#130]
hello guys what is this error how can i fix this 
![image](https://user-images.githubusercontent.com/97475567/151573182-45faf586-603e-4617-8f91-7e1009dddf0e.png)

**Comment by V4NSH4J** [comment]
Hi, is this a repeated issue? Or it happens just once in a while?
Also, I think this should be fixed after a recent change one of the contributors pushed to the source code

**Comment by manisakurdu** [comment]
> Hi, is this a repeated issue? Or it happens just once in a while? Also, I think this should be fixed after a recent change one of the contributors pushed to the source code

Yes this is repeated issue

**Comment by V4NSH4J** [comment]
> > Hi, is this a repeated issue? Or it happens just once in a while? Also, I think this should be fixed after a recent change one of the contributors pushed to the source code
> 
> Yes this is repeated issue

Could you try using the source code?

**Comment by manisakurdu** [comment]
> > > Hi, is this a repeated issue? Or it happens just once in a while? Also, I think this should be fixed after a recent change one of the contributors pushed to the source code
> > 
> > 
> > Yes this is repeated issue
> 
> Could you try using the source code?

i tried its happen againg but after i re open it didnt happened again

**Comment by omegabank** [comment]
I have the same issue

**Comment by omegabank** [comment]
![image](https://user-images.githubusercontent.com/57399009/151713852-34c012d6-13d1-4f93-b27b-ba4e40dfc701.png)

**Comment by V4NSH4J** [comment]
Don't worry, it has been fixed in the source code. It has not been compiled yet. But feel free to build from source, it's explained in readme
