### ISSUE TITLE
reccomended delay time when joining a server?

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#132]
Do you guys have a recommended base delay time and random delay time when joining a server using the invite option (option 1)?

**Comment by theroney** [comment]
yes why not? this makes it harder for server owners to find yours token, random thing

**Comment by seanthakid** [comment]
> yes why not? this makes it harder for server owners to find yours token, random thing

what delay time do you reccomend?
