### ISSUE TITLE
Error while setting messages: invalid character '\r' in string literal

### ISSUE THREAD

**Issue by joojleo** [V4NSH4J/discord-mass-DM-GO#133]
![image](https://user-images.githubusercontent.com/55558889/151641974-93aae8c4-7d74-414e-a360-654465d8c149.png)
this happens when i try to run mass dm

**Comment by V4NSH4J** [comment]
Can you attach your message.json

**Comment by joojleo** [comment]
by somehow it solved, thanks tho
