### ISSUE TITLE
im not able to use server id ?

### ISSUE THREAD

**Issue by pussycake123** [V4NSH4J/discord-mass-DM-GO#134]
Hi can someone help me ive got this error
![image](https://user-images.githubusercontent.com/98628087/151643429-204657e3-7118-4a00-b2eb-832bba147b46.png)

**Comment by seanthakid** [comment]
dont use discum use the built inscraper in the most recent version. once you start the actual exe file select option 10 (scraper)

**Comment by theroney** [comment]
yes, this version is as irrelevant to the current
