### ISSUE TITLE
captcha bypass for invite?

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#135]
is there a way to bypass captcha for the built-in server join option (option 1).

**Comment by V4NSH4J** [comment]
Which captcha?

**Comment by seanthakid** [comment]
> Which captcha?

when joining some servers there are captcha (or other forms of verification) how do I bypass this. Right now my tokens join the server but get kicked and banned because they cannot complete the server verification process.

**Comment by V4NSH4J** [comment]
> > Which captcha?
> 
> when joining some servers there are captcha (or other forms of verification) how do I bypass this. Right now my tokens join the server but get kicked and banned because they cannot complete the server verification process.
> 

It can't support every captcha as every server and verification is different.
Have you confirmed your accounts didn't get caught by the anti-raid? 
If it was the "solve captcha or kick" type of situation, you can't raid that server or you'd have to keep rejoining it.

**Comment by seanthakid** [comment]
> > > Which captcha?
> > 
> > 
> > when joining some servers there are captcha (or other forms of verification) how do I bypass this. Right now my tokens join the server but get kicked and banned because they cannot complete the server verification process.
> 
> It can't support every captcha as every server and verification is different. Have you confirmed your accounts didn't get caught by the anti-raid? If it was the "solve captcha or kick" type of situation, you can't raid that server or you'd have to keep rejoining it.

yes I have to keep rejoining because for any server that has a verification process, I kick or banned bc the option 1 doesn't complete the verification

**Comment by V4NSH4J** [comment]
> > > > Which captcha?
> > > 
> > > 
> > > when joining some servers there are captcha (or other forms of verification) how do I bypass this. Right now my tokens join the server but get kicked and banned because they cannot complete the server verification process.
> > 
> > 
> > It can't support every captcha as every server and verification is different. Have you confirmed your accounts didn't get caught by the anti-raid? If it was the "solve captcha or kick" type of situation, you can't raid that server or you'd have to keep rejoining it.
> 
> yes I have to keep rejoining because for any server that has a verification process, I kick or banned bc the option 1 doesn't complete the verification

It's an invite joiner, not magic. It can't complete every verification it comes across. It can bypass community screening and if discord decides to add hcaptcha to join servers like before it can be easily updated to bypass that. Other than that, it just an invite joiner and it can't bypass any other types of security

**Comment by seanthakid** [comment]
> > > > > Which captcha?
> > > > 
> > > > 
> > > > when joining some servers there are captcha (or other forms of verification) how do I bypass this. Right now my tokens join the server but get kicked and banned because they cannot complete the server verification process.
> > > 
> > > 
> > > It can't support every captcha as every server and verification is different. Have you confirmed your accounts didn't get caught by the anti-raid? If it was the "solve captcha or kick" type of situation, you can't raid that server or you'd have to keep rejoining it.
> > 
> > 
> > yes I have to keep rejoining because for any server that has a verification process, I kick or banned bc the option 1 doesn't complete the verification
> 
> It's an invite joiner, not magic. It can't complete every verification it comes across. It can bypass community screening and if discord decides to add hcaptcha to join servers like before it can be easily updated to bypass that. Other than that, it just an invite joiner and it can't bypass any other types of security

yeah true. Thanks for the response and this tool!

**Comment by V4NSH4J** [comment]
My pleasure

**Comment by seanthakid** [comment]
> My pleasure

I don't suppose you could point me in the direction of a tool that could bypass anti-raid or verifications. If not, thank you for your time.

**Comment by V4NSH4J** [comment]
> > My pleasure
> 
> I don't suppose you could point me in the direction of a tool that could bypass anti-raid or verifications. If not, thank you for your time.

You can bypass Anti-raid with delays but I don't think there are any tools which bypass verification. If there are, they would have to write a different tool for each server probably
