### ISSUE TITLE
Is there possible to make them join server faster?

### ISSUE THREAD

**Issue by pussycake123** [V4NSH4J/discord-mass-DM-GO#136]
join 20k total is take a while is there a way to make it quicker?

**Comment by pussycake123** [comment]
i did for 4000 and take me like 3hours..

**Comment by V4NSH4J** [comment]
Reduce your offset to 1, it's the fastest you can go. If you go proxyless with a low offset you can probably have them join all 20k in a couple minutes

**Comment by pscpc** [comment]
> join 20k total is take a while is there a way to make it quicker?

btw you don't want that, because there is a high chance tokens get banned in target server
