### ISSUE TITLE
can someone help me with this probleme

### ISSUE THREAD

**Issue by pussycake123** [V4NSH4J/discord-mass-DM-GO#137]
![image](https://user-images.githubusercontent.com/98628087/151656233-9e8eea44-1418-4e6d-bed6-2c07899e823b.png)

**Comment by V4NSH4J** [comment]
You are rate limited, use proxy/VPN

**Comment by pussycake123** [comment]
You have proxy to suggest me

Le sam. 29 janv. 2022 5 h 49 a.m., Vanshaj ***@***.***> a
écrit :

**Comment by V4NSH4J** [comment]
https://iproyal.com
https://proxiware.com
