### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by pizzalover32** [V4NSH4J/discord-mass-DM-GO#14]
do my tokens need to be phone verified?
and can you suggest a place where i can buy good proxies :)

**Comment by eboujlal** [comment]
Do you have a tool that let you to verify token by phone number ?

**Comment by V4NSH4J** [comment]
> do my tokens need to be phone verified? and can you suggest a place where i can buy good proxies :)

Hey, tokens don't necessarily need to be phone verified! They can be only email verified as well. It depends on the servers you're targeting and your cost efficiency. You can try Packetstream or Iproyal for proxies! Be sure to only buy rotating ones.

**Comment by V4NSH4J** [comment]
> Do you have a tool that let you to verify token by phone number ?

No unfortunately not.

**Comment by pizzalover32** [comment]
if i use this tool will it lock my tokens are not?

**Comment by pizzalover32** [comment]
i used the tool didnt lock my tokens is there anyway it could be just a message instead of a embed?

**Comment by V4NSH4J** [comment]
> if i use this tool will it lock my tokens are not?

Every token will get locked at some point. That point would really be decided by your token quality and verification. Checkout the part in the readme file regarding Tokens. 



> i used the tool didnt lock my tokens is there anyway it could be just a message instead of a embed?

Remove the whole embed part, there's an example for this as well in the readme file.

**Comment by pizzalover32** [comment]
i read the readme thanks for the help bro. as my last question do yk where i can buy tokens or a gen?

**Comment by V4NSH4J** [comment]
> 

No problem at all. you'd have to find a seller for tokens. Token gens aren't easy to come by, they usually cost a lot... Try joining the Discord support server, I've got some sellers listed there who's tokens I've personally tried.

**Comment by eboujlal** [comment]
> > 
> 
> No problem at all. you'd have to find a seller for tokens. Token gens aren't easy to come by, they usually cost a lot... Try joining the Discord support server, I've got some sellers listed there who's tokens I've personally tried.

Can you update discord server's link because its not working any more

**Comment by V4NSH4J** [comment]
> > > 
> > 
> > 
> > No problem at all. you'd have to find a seller for tokens. Token gens aren't easy to come by, they usually cost a lot... Try joining the Discord support server, I've got some sellers listed there who's tokens I've personally tried.
> 
> Can you update discord server's link because its not working any more

Permanent invite: https://discord.gg/Rv4D5dQnqH
