### ISSUE TITLE
Not writing ids in failed or completed.txt

### ISSUE THREAD

**Issue by nikushakhabu** [V4NSH4J/discord-mass-DM-GO#140]
<img width="1388" alt="Screenshot 2022-01-30 at 20 28 08" src="https://user-images.githubusercontent.com/98703903/151708532-447e9c2f-3aa1-4f13-bcf6-d2f1b1359035.png">

I do have failed.txt and completed.txt in the input folder

When I go into the same folder with terminal and type open input/failed.txt it does open the txt file

**Comment by V4NSH4J** [comment]
Does DMDGO have read/write perms?

**Comment by nikushakhabu** [comment]
@V4NSH4J DMDGO  executable or the folder?

**Comment by nikushakhabu** [comment]
<img width="449" alt="Screenshot 2022-01-30 at 23 56 33" src="https://user-images.githubusercontent.com/98703903/151715381-93bb1802-22d8-4beb-91b0-34c30e85f114.png">
@V4NSH4J

**Comment by nikushakhabu** [comment]
@V4NSH4J any ideas?

**Comment by V4NSH4J** [comment]
Usually this problem can arise when you're using the binary which isn't for your OS/Arch.
Could you give me more information about your chipset and which binary you're using?

**Comment by V4NSH4J** [comment]
> <img width="580" alt="Screenshot 2022-01-31 at 17 07 28" src="https://user-images.githubusercontent.com/98703903/151836869-3d123228-c410-4a7c-a498-c604baef409b.png">
> 
> 
> @V4NSH4J 

And you're using the AMD64 Darwin binary?

**Comment by nikushakhabu** [comment]
@V4NSH4J yes

**Comment by V4NSH4J** [comment]
Okay, I want you to build from source and try this out

**Comment by nikushakhabu** [comment]
@V4NSH4J I did build from source and its exactly the same

**Comment by V4NSH4J** [comment]
Okay, I asked some people more experienced than me what this could be. 
They think that you might not be executing it from the location where the input folder exists.

**Comment by nikushakhabu** [comment]
I am running from the location where the input folder exists. It sometimes writes in it maybe once in every 1000 failed message

**Comment by nikushakhabu** [comment]
Also, what is the maximum amount of tokens that I should use at the same time?

I tried using 500 tokens with 2,000 proxies and websocket gives error saying smth like "tcp too many open files"
when I try 250 tokens it works without any issues.

**Comment by V4NSH4J** [comment]
> I am running from the location where the input folder exists. It sometimes writes in it maybe once in every 1000 failed message

I'm unsure then what's causing this, as if it were a problem with the program it would never write to file...



> Also, what is the maximum amount of tokens that I should use at the same time?
> 
> I tried using 500 tokens with 2,000 proxies and websocket gives error saying smth like "tcp too many open files" when I try 250 tokens it works without any issues.

There's not really a limit, if you're using a websocket function, try enabling and disabling proxy_for_gateway in config. It's a better idea to not use any websocket functions while DMing anyways. Let me know, also ensure proxy_from_file is enabled

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
