### ISSUE TITLE
proxy not working

### ISSUE THREAD

**Issue by k0n3c** [V4NSH4J/discord-mass-DM-GO#141]
Hello, I use proxyware and when I disable the file proxy the DM works but when I use the proxy an error appears "[10:18:49] Error while getting response from cookies request Get "https://discord. com": read tp xx.xx.x.x:xxxxx->xx.xxx
xxx.xxx:xx02: wsarecv: An existing connection must have been closed by the remote host."

**Comment by V4NSH4J** [comment]
Make sure you're IP is authenticated

**Comment by k0n3c** [comment]
yes that's what i did

**Comment by k0n3c** [comment]
you don't have another idea? it's really annoying

**Comment by V4NSH4J** [comment]
> you don't have another idea? it's really annoying

If your IP is authed, the format of proxies is correct and you still have proxy data you should be good. I was using proxiware in my recent video as well

**Comment by k0n3c** [comment]
can i use proxies with a vpn?

**Comment by V4NSH4J** [comment]
> can i use proxies with a vpn?

Ofcourse, but then you'll have to Authorize your VPN IP

**Comment by k0n3c** [comment]
it works without vpn

**Comment by k0n3c** [comment]
yet I bind my vpn address

**Comment by V4NSH4J** [comment]
> yet I bind my vpn address

If it works without VPN, use it without it?
