### ISSUE TITLE
{"message": "Missing Access", "code": 50001}

### ISSUE THREAD

**Issue by DMG-G** [V4NSH4J/discord-mass-DM-GO#143]
Failed to bypass Token OTM0MDcwMTYxNTk2NjIwODgx.Yequ4w.AZsr2S4Rj43vq3lmwKzACw 403 {"message": "Missing Access", "code": 50001}

**Comment by V4NSH4J** [comment]
Your token got kicked/banned before it could bypass community screening

**Comment by DMG-G** [comment]
> 

can't there be any solutions to this problem?

**Comment by DMG-G** [comment]
> Your token got kicked/banned before it could bypass community screening
![крин](https://user-images.githubusercontent.com/97929909/151785389-c9dd742f-9e0e-48f7-8961-79f81cd5512b.jpg)

**Comment by V4NSH4J** [comment]
> > Your token got kicked/banned before it could bypass community screening
> > ![крин](https://user-images.githubusercontent.com/97929909/151785389-c9dd742f-9e0e-48f7-8961-79f81cd5512b.jpg)
> 
> If I enter it manually, it writes like this. What does this mean?

It can't see the membership screening prompt so it can't bypass it
