### ISSUE TITLE
Running into this error when trying to scrape certain servers. Connecting but not actually scraping anything?

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#144]
![7E734DE0-C93B-4BA6-B47A-EF30BD91FBE1](https://user-images.githubusercontent.com/96969678/151778533-40004ba1-514b-48ff-88bc-2f9f4ff6577b.jpeg)

**Comment by V4NSH4J** [comment]
Make sure your token is in the server and can see the channel you're trying to scrape. If the problem still persists, use the discum scraper.

**Comment by theroney** [comment]
I think when you scrape online, enter the token you will do and then choose it from the channels you can see with used token
