### ISSUE TITLE
When tool can't login to a proxy it's still running but proxyless.

### ISSUE THREAD

**Issue by jonahbill22** [V4NSH4J/discord-mass-DM-GO#145]
Hello,

I was wondering why so many tokens got locked. Then I noticed when the tool can't access to a proxy it's running without the proxy and the tokens are running over the normal internet connection (proxyless). I tried this several times and also insert dummy proxies but some tokens are still joining a server for e.g..

Can you look into this? Thank you very much!

**Comment by V4NSH4J** [comment]
It's an intentional thing, if the program isn't able to break down the proxy in parts to get it's username password, etc due to wrong format or anything, it will work proxyless for the token which was supposed to use that proxy. If all your proxies are dummies, it will ofcourse be proxyless.
