### ISSUE TITLE
Compare with previous version (1.0.6)

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#146]
When i used 1.0.7.6 first time i noticed it "locks" token higher then 1.0.6. 
And the token checker, lets say i have 500 token. i tried to mass dm with them on latest version. in first 50 line 25 of token got locked.(475). And then i checked the tokens (token checker). Script said only 425 tokens are valid of 500.  (425)
But i put the origin 500 tokens in 1.0.6 version's tokens.txt and checked them (token checker). script said 475 valid of 500.

At total 1.0.7.6. locked 25 tokens and Gave wrong results at token checker.

Is there anybody to had like these problems and continuing to use 1.0.6?

(sorry for my bad england)

**Comment by V4NSH4J** [comment]
It's a problem with your proxies really. The token checker code is *exactly* the same. You can still continue to use proxies the old way as you did in DMDGO 1.0.6
