### ISSUE TITLE
Server verification security

### ISSUE THREAD

**Issue by nikushakhabu** [V4NSH4J/discord-mass-DM-GO#147]
![oee](https://user-images.githubusercontent.com/98703903/151830108-5e865fd9-f99b-41a8-ba3b-10e8a83ce471.png)

When a server has this kind of entry verification, it asks you to put an emoji and then agree to terms before you can see other channels. After I  join 100 tokens, how do I make them bypass this?

**Comment by V4NSH4J** [comment]
> ![oee](https://user-images.githubusercontent.com/98703903/151830108-5e865fd9-f99b-41a8-ba3b-10e8a83ce471.png)
> 
> When a server has this kind of entry verification, it asks you to put an emoji and then agree to terms before you can see other channels. After I join 100 tokens, how do I make them bypass this?

The verification in the screenshot is automatically bypassed by the invite joiner.
If you wish to bypass an emoji verification, you can use the reaction adder. However it's not required to send DMs

**Comment by nikushakhabu** [comment]
<img width="1416" alt="Screenshot 2022-01-31 at 20 43 50" src="https://user-images.githubusercontent.com/98703903/151835733-ab841a3c-bd37-4662-87f1-c7827d651eb0.png">


This is the landing page when I join the channel. If we don't click on emojy the verification popup does not come up. In this case would you use reaction adder or not? otherwise I think tokens will be kicked after some time

**Comment by V4NSH4J** [comment]
> <img alt="Screenshot 2022-01-31 at 20 43 50" width="1416" src="https://user-images.githubusercontent.com/98703903/151835733-ab841a3c-bd37-4662-87f1-c7827d651eb0.png">
> 
> @V4NSH4J This is the landing page when I join the channel. If we don't click on emojy the verification popup does not come up. In this case would you use reaction adder or not? otherwise I think tokens will be kicked after some time

The joiner will bypass the thing at the top on its own mostly. So you'll be able to use reaction adder to add the emoji if you wish
