### ISSUE TITLE
How to run on MacOS?

### ISSUE THREAD

**Issue by ibeallc** [V4NSH4J/discord-mass-DM-GO#15]
I downloaded arm64 file on releases for m1 but I don't understand how to run discord-mass-dm-GO file. Help pls

**Comment by V4NSH4J** [comment]
> I downloaded arm64 file on releases for m1 but I don't understand how to run discord-mass-dm-GO file. Help pls

Hi you should be able to execute it from your terminal window. Make sure you're in the right directory.

**Comment by ibeallc** [comment]
Hi thank you for replay.
I'm trying execute it on terminal but it says cannot execute binary file
https://imgur.com/a/igCmkap

**Comment by ibeallc** [comment]
> > I downloaded arm64 file on releases for m1 but I don't understand how to run discord-mass-dm-GO file. Help pls
> 
> Hi you should be able to execute it from your terminal window. Make sure you're in the right directory.

Hi, thank you for your reply.
I'm trying to execute it on terminal but it says it cannot execute binary file.
https://imgur.com/a/igCmkap

**Comment by V4NSH4J** [comment]
> > > I downloaded arm64 file on releases for m1 but I don't understand how to run discord-mass-dm-GO file. Help pls
> > 
> > 
> > Hi you should be able to execute it from your terminal window. Make sure you're in the right directory.
> 
> Hi, thank you for your reply. I'm trying to execute it on terminal but it says it cannot execute binary file. https://imgur.com/a/igCmkap

I think this happens when you try to execute the binary of another architecture. Could you try building from source? For DMDGO v1.0.6 releases, I didn't put a precompiled version for ARM64

**Comment by ibeallc** [comment]
I solved by this.
> chmod a+x ./folder
Thank you!
