### ISSUE TITLE
server where?

### ISSUE THREAD

**Issue by cateee69** [V4NSH4J/discord-mass-DM-GO#150]
where is is the coffee shop?

**Comment by V4NSH4J** [comment]
Got terminated, turns out discord is proficient in French. RIP 5th server (lasted 2 days)

**Comment by cateee69** [comment]
i didn't get a dm from discord so it looked like you deleted the server

**Comment by V4NSH4J** [comment]
![Screenshot_20220201-163330__01](https://user-images.githubusercontent.com/79518089/151957379-118cb43a-1c3e-4666-8292-3c5429221cc2.jpg)
They were kind enough to send me a copy pasted email lol

**Comment by cateee69** [comment]
they didn't term the server it self but they termed you
every server you have ever created got deleted

**Comment by V4NSH4J** [comment]
> they didn't term the server it self but they termed you every server you have ever created got deleted

Oh? I see, next time I make it on an alt 😂
