### ISSUE TITLE
Idea: scrape based on the category

### ISSUE THREAD

**Issue by nikushakhabu** [V4NSH4J/discord-mass-DM-GO#151]
So on the right hand side you have Admins, Moderators, Whitelisted, Online, Offline etc...

It would be great to let us scrape specific category, for example Whitelisted, so we can directly target people who work hard.

**Comment by pscpc** [comment]
probably not possible

**Comment by V4NSH4J** [comment]
It is possible to scrape based on the permissions the user has so something might be possible

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
