### ISSUE TITLE
Issue while sending DM's

### ISSUE THREAD

**Issue by monstariko** [V4NSH4J/discord-mass-DM-GO#152]
_[09:47:37] Error while getting response from cookies request Get "https://discord.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[09:47:37] Error while opening DM channel: error while getting cookie error while getting response from cookie request Get "https://discord.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)_ 
Most of all DM's are with this error. But:
_[09:47:40] DM advertisement took 72.7129183. Successfully sent DMs to 2 IDs. Failed to send DMs to 58 IDs. 7 tokens are dis-functional & 53 tokens are functioning_
Proxies - backconnect, tokens - email verified only.
Help me please :)

**Comment by V4NSH4J** [comment]
Which proxy service are you using? They look slow. Could you send your config.json here and also try setting a higher timeout in config?

**Comment by monstariko** [comment]
Proxy https://fosy.club/ backconnect. 
[config.zip](https://github.com/V4NSH4J/discord-mass-DM-GO/files/7977958/config.zip)

**Comment by V4NSH4J** [comment]
Okay, I've never heard of this proxy service so no idea about their proxies. But try increasing your timeout in config from 30 to like 120

**Comment by monstariko** [comment]
Yes, without proxy all works well. Thanks!
