### ISSUE TITLE
Token gets banned after sending around 10 messages with 1min intervals. How are you guys doing this so that you have enough tokens for this to be worth while?

### ISSUE THREAD

**Issue by samuelcelko** [V4NSH4J/discord-mass-DM-GO#153]

**Comment by Samuel-Celko** [comment]
as in how do you guys get lots and lots of tokens?

**Comment by V4NSH4J** [comment]
Hey, 10 DMs is pretty less. Your tokens might be flagged. Log into one and try sending some DMs by hand, see how many you get. People have token generators to get tokens

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
