### ISSUE TITLE
How react work i dont understand it..

### ISSUE THREAD

**Issue by pussycake123** [V4NSH4J/discord-mass-DM-GO#157]
Hey how can i do react with mass dm bot?

**Comment by V4NSH4J** [comment]
Reaction Adder option 
You don't need to react to send DMs though

**Comment by pussycake123** [comment]
i want do react on my own channel..

**Comment by V4NSH4J** [comment]
Use the reaction adder

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
