### ISSUE TITLE
Best setting for 25 dm+

### ISSUE THREAD

**Issue by pussycake123** [V4NSH4J/discord-mass-DM-GO#158]
Hi i have mail verified token and i want to know the best setting at this moment please <3

**Comment by V4NSH4J** [comment]
Hey, usually 60 individual and rate limit delay is the best and fastest setting possible. I've also explained the best offset in the readme. However the number of DMs you get would depend on many factors like token quality and the people (if their dms are open or not)

**Comment by pussycake123** [comment]
![image](https://user-images.githubusercontent.com/98628087/152073054-8544f1e4-bea0-4462-9c59-77f7f4e9b566.png)

can you tell me what i do wrong im doing 9 dm... with proxy and all

**Comment by V4NSH4J** [comment]
Your tokens might be flagged, try logging into one and sending dms manually

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
