### ISSUE TITLE
Failed to send message ERROR 400

### ISSUE THREAD

**Issue by basvuh** [V4NSH4J/discord-mass-DM-GO#16]
Hello, first of all thanks for sharing this amazing project.

Coming back to the problem, I receive error 400 on sending the messages, I checked the tokens and they are valid.
I'm trying to send a simple messaged without the embed. I read the readme file and I just replaced the infos that I needed to change. When trying to run the programm it gives me this error.
Error 400: Cannot send empty message 

I initially tried to send it with the default messaged that you left there and it worked, but once I changed it it stopped working and giving me this error.

**Comment by V4NSH4J** [comment]
Hi, this is a very common issue with the new users of DMDGO. The problem lies in your message.json file. There should not be a comma following the last field in JSON format. **This means you have to remove the comma in front of content**
