### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hellothere-imyoung** [V4NSH4J/discord-mass-DM-GO#160]
![Screenshot 2022-02-01 193130](https://user-images.githubusercontent.com/83843280/152074216-5a05ff0a-4040-458f-9fed-04d9c8a1066f.png)
I'm not sure what I've done wrong here.

**Comment by EricFerland** [comment]
Drop the discord.gg///

Just use the invite code.

**Comment by V4NSH4J** [comment]
Token is wrong or disabled

**Comment by hellothere-imyoung** [comment]
Ah yeah I was thinking the same, I'm using a token gen so makes sense.

**Comment by V4NSH4J** [comment]
> Ah yeah I was thinking the same, I'm using a token gen so makes sense.

Run your tokens through the token checker.

**Comment by hellothere-imyoung** [comment]
Alright, will do when I get home.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
