### ISSUE TITLE
Proxy authentification required

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#162]
I have checked my proxies and they are working on discord.com
But have this error when trying to join tokens to the server:
![image](https://user-images.githubusercontent.com/89306625/152213865-0ea3655f-fee7-4759-8297-e24ad943cab2.png)

Here is how my proxy file looks like:
![image](https://user-images.githubusercontent.com/89306625/152214164-1541fbb4-6e09-4938-a7ac-a6f9c4b5ffcc.png)

**Comment by V4NSH4J** [comment]
The user:pass on your proxy is incorrect.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
