### ISSUE TITLE
403 after 2-5 DMs

### ISSUE THREAD

**Issue by ganynmednet** [V4NSH4J/discord-mass-DM-GO#163]
Hey,

I use the tool with different tokens from good sources, in average I have 25+ dm per email verified token. After the latest updates today, it dropped to 2-3 dm per token. I tried different proxies.

Could the issue be related to the update? 
Could the offset 50 in the config be the issue?

Thx

**Comment by YardRhino** [comment]
Can you link where you got the tokens from?

**Comment by V4NSH4J** [comment]
Hey, it could be that your tokens are flagged or used. Try logging into one and send a few DMs manually and see how many you can get.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
