### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by nikushakhabu** [V4NSH4J/discord-mass-DM-GO#164]
<img width="1385" alt="Screenshot 2022-02-03 at 02 06 39" src="https://user-images.githubusercontent.com/98703903/152245504-17f6c5d4-f41d-470e-852b-96c6eadd65b6.png">

Has this used all of my call limits? and why is this happening?  if I use more than 200 tokens this is what happens. I have 1500 proxies or more and all of them are premium proxies. I tried other proxies as well same issue

**Comment by V4NSH4J** [comment]
Hey, is the issue in #140 solved? 
There seems to be a limit on the number of file descriptors you may open on Linux/Darwin. This affects both the network socket and the regular files. 
You can check your hard limit and soft limit using the `ulimit -Hn` and `ulimit -Sn`
commands and then increase them by adding a number in front of it like `ulimit -Sn value` but make sure the value does not exceed the hard limit. You can find more information on this on the internet as well.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
