### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shurjeelfayyaz1** [V4NSH4J/discord-mass-DM-GO#166]
Sir I am getting this error while joining any server.
<img width="660" alt="12" src="https://user-images.githubusercontent.com/94997952/152273555-96d9a27e-405d-42a8-9313-d04a3505e319.PNG">

**Comment by V4NSH4J** [comment]
Hey, you're on DMDGO V1.7.6 or older. I fixed this issue in the DMDGO v1,7.7 release

**Comment by shurjeelfayyaz1** [comment]
Oh thanks a lot. Sorry
