### ISSUE TITLE
[02:02:47] Error while joining: invalid character 'e' looking for beginning of value Error while unmarshalling body invalid character 'e' looking for beginning of value

### ISSUE THREAD

**Issue by xchanger17** [V4NSH4J/discord-mass-DM-GO#167]
I seem to get this error every time I try to join any server. Any ideas why?

**Comment by V4NSH4J** [comment]
> I seem to get this error every time I try to join any server. Any ideas why?

Hi, this error is cloudflare error 1015 which is an IP based rate limit. A temporary solution to this can be using a VPN. The permanent solution would be to use proxies.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
