### ISSUE TITLE
[19:41:32] Token OTM4NDcxNTU4MjYxOTA3NTA3.Yfqy9w.-vYjeToo2UpnGCh5saHd_8 failed to DM 818585700014096414 User has DMs closed or not present in server {"message": "Cannot send messages to this user", "code": 50007} [1]

### ISSUE THREAD

**Issue by Bebeez** [V4NSH4J/discord-mass-DM-GO#168]
HI, 

when i sent the command i receive this error on all the token

[19:41:32] Token OTM4NDcxNTU4MjYxOTA3NTA3.Yfqy9w.-vYjeToo2UpnG8 failed to DM 818585700014096414 User has DMs closed or not present in server {"message": "Cannot send messages to this user", "code": 50007} [1]

the problem comes from my token.txt? thank you in advance for your help

**Comment by V4NSH4J** [comment]
Hi, I tried to modify your text to hide your token but it's logged here anyways so if it's an account that holds value to you I recommend to change its password ASAP. 

For your issue, it looks like either your accounts are not in the server you're trying to DM. You can join them using invite joiner. If you did already, there's a chance an antiraid bot mightve kicked them. This can be checked by using the server checker option, it will tell you if your tokens are still in the server. 

If your tokens are still in the server and you're being spammed with this then you're using an incorrect memberlist. Either from another server or you forgot to scrape. 

Some of these errors are normal as some users may have their DMs closed but being spammed it is not normal

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
