### ISSUE TITLE
message embed format please

### ISSUE THREAD

**Issue by drizzy009** [V4NSH4J/discord-mass-DM-GO#169]
cant get it to work

**Comment by V4NSH4J** [comment]
Embed support was removed from DMDGO following a minor Discord update on 22nd January 2022 removing the ability to send embeds from regular discord clients.

**Comment by origranot** [comment]
@V4NSH4J 
Is there any bypass to this discord update?

**Comment by V4NSH4J** [comment]
#124 is the only way of sending embeds

**Comment by yomamabig234** [comment]
Can give give the source which says discord has disabled it please ? im having trouble explaining people its actually disabled

**Comment by V4NSH4J** [comment]
> Can give give the source which says discord has disabled it please ? im having trouble explaining people its actually disabled

Ofcourse Discord won't do an official announcement as selfbots are against discord TOS and community guidelines. Here are a few sources for you: 
https://www.reddit.com/r/Discord_selfbots/comments/sdhr4p/discord_just_patched_embeds_sadge_even_more/?utm_medium=android_app&utm_source=share

https://www.reddit.com/r/Discord_selfbots/comments/sa0hc2/discord_embeds_patched/?utm_medium=android_app&utm_source=share

https://github.com/Merubokkusu/Discord-S.C.U.M/issues/311

What's there to explain? Ask them to try send an embed, it won't deliver, only the message content will go. The only way to send an embed now is explained in #124

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
