### ISSUE TITLE
Message: Cannot send an empty message Info on Errors on GitHub Readme

### ISSUE THREAD

**Issue by bobthebuilder1234321** [V4NSH4J/discord-mass-DM-GO#17]
Any ideas? I put in one verified token that I had access to. I joined the server w the token and when I chose option (2), aka mass DM advertiser, I got this. 
![image](https://user-images.githubusercontent.com/96494419/147109326-f06f6884-5eb1-4186-86b9-efe1b0858e05.png)

**Comment by V4NSH4J** [comment]
Hi, having the message format in message.json incorrect causes DMDGO to not detect the message and try send empty messages which is not possible on Discord. Please make sure if you removed the embed that you also removed the comma following content. Share your message.json file so I can take a look!

**Comment by basvuh** [comment]
> Hi, having the message format in message.json incorrect causes DMDGO to not detect the message and try send empty messages which is not possible on Discord. Please make sure if you removed the embed that you also removed the comma following content. Share your message.json file so I can take a look!

I was able to fix the error. Thanks
I also wanted to know, if you have anything that auto mass #verify on the channels once the tokens join the servers

**Comment by V4NSH4J** [comment]
> > Hi, having the message format in message.json incorrect causes DMDGO to not detect the message and try send empty messages which is not possible on Discord. Please make sure if you removed the embed that you also removed the comma following content. Share your message.json file so I can take a look!
> 
> I was able to fix the error. Thanks I also wanted to know, if you have anything that auto mass #verify on the channels once the tokens join the servers

Every server is different, to detect and add bypasses to every type of captcha bot/anti raid bot is impossible, so no, you can manually check out the server security and bypass the tokens accordingly.

**Comment by basvuh** [comment]
> > > Hi, having the message format in message.json incorrect causes DMDGO to not detect the message and try send empty messages which is not possible on Discord. Please make sure if you removed the embed that you also removed the comma following content. Share your message.json file so I can take a look!
> > 
> > 
> > I was able to fix the error. Thanks I also wanted to know, if you have anything that auto mass #verify on the channels once the tokens join the servers
> 
> Every server is different, to detect and add bypasses to every type of captcha bot/anti raid bot is impossible, so no, you can manually check out the server security and bypass the tokens accordingly.

I know, but most of the servers have only a accept the rules and a #verify channel where you have to click a reaction. If it's not possible I will do it manually, but it would be better if it would be possible.
If you could make anything like that I could pay you as well. Again, grateful for the help you given me previously.

**Comment by cateee69** [comment]
use reaction adder

**Comment by basvuh** [comment]
> use reaction adder

Could you link me something?

**Comment by cateee69** [comment]
Option 4
