### ISSUE TITLE
Failed to bypass Token OTMzNTc0ODU1ODc2NTcxMTU2.YejhcA.jsVq 400 {"code": 50035, "errors": {"form_fields": {"_errors": [{"code": "MEMBER_VERIFICATION_FORM_MISMATCH", "message": "Form responses do not match the server's existing form format."}]}}, "message": "Invalid Form Body"}

### ISSUE THREAD

**Issue by DMG-G** [V4NSH4J/discord-mass-DM-GO#170]
Failed to bypass Token OTMzNTc0ODU1ODc2NTcxMTU2.YejhcA.jsVqOBMPW2YoZChg86H 400 {"code": 50035, "errors": {"form_fields": {"_errors": [{"code": "MEMBER_VERIFICATION_FORM_MISMATCH", "message": "Form responses do not match the server's existing form format."}]}}, "message": "Invalid Form Body"}

**Comment by V4NSH4J** [comment]
Hi, which version of DMDGO are you on? Discord did a small patch, I fixed it in DMDGO V1. 7.7

**Comment by V4NSH4J** [comment]
Reopen if problem persists.

**Comment by bribbon** [comment]
Using DMDGO v1.11.2 and get a lot of errors while trying to join a server:

`[ERROR  ][15:51:54] » [15:51:54] Error while Getting cookies: error while getting response from cookies request Get "https://discord.com": unexpected EOF
[SUCCESS][15:51:58] » NDQE4MjIzMjQ2MTE0ODM3.GljKtY.DpKWKGoc_J0g2eunwLvhZ6O1xdtFCJnC31AXSQ joined guild yC8dF7e4
[ERROR  ][15:52:00] » [15:52:00] Failed to bypass Token NDQE4MjIzMjQ2MTE0ODM3.GljKtY.DpKWKGoc_J0g2eunwLvhZ6O1xdtFCJnC31AXSQ 400 {"code": 50035, "errors": {"form_fields": {"_errors": [{"code": "MEMBER_VERIFICATION_FORM_MISMATCH", "message": "Form responses do not match the server's existing form format."}]}}, "message": "Invalid Form Body"}
[SUCCESS][15:52:30] » All Threads Completed!`
