### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by poe-god** [V4NSH4J/discord-mass-DM-GO#172]
I keep seeing this when i try to scrape members. What am I doing wrong?

**Comment by V4NSH4J** [comment]
Hey! Could you provide a full screenshot of the error and let me know which version of DMDGO you're on

**Comment by Ic3m4n34** [comment]
Same issue here. 
Version: `V1.0.7.6`
System: Mac M1

I'm using proxies from proxiware

<img width="1174" alt="Bildschirmfoto 2022-02-05 um 16 02 24" src="https://user-images.githubusercontent.com/11556486/152647386-4d27dc98-adef-4fdf-8af0-88a91317719c.png">

Any help is appreciated!

**Comment by V4NSH4J** [comment]
Hey, the unknown error could mean a variety of things. Usually for me it appears when token is kicked from the server. 
You can try using the discum scraper
Reopen if problem persists.
