### ISSUE TITLE
Scraper connects to web socket, but doesn’t scrape. Discum scraper dosnt work either. Token is correctly typing in server and channel. Any help?

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#175]
![898607FF-BCDB-4607-85B2-CD3D9A619829](https://user-images.githubusercontent.com/96969678/152638016-dbbadbba-c1b9-4c8e-be21-c9c2eff1d732.jpeg)

**Comment by franklin112** [comment]
i get the same error, no idea why

**Comment by V4NSH4J** [comment]
> i get the same error, no idea why

If your token is present in the server and can see the channel and is still not able to scrape, it can be because you're in a lot of servers. Try with a fresh token, if it still doesn't work. Use the Discum scraper

**Comment by seanthakid** [comment]
> > i get the same error, no idea why
> 
> If your token is present in the server and can see the channel and is still not able to scrape, it can be because you're in a lot of servers. Try with a fresh token, if it still doesn't work. Use the Discum scraper

I tried with 10+ fresh tokens none worked. Discum doesn't work either.

**Comment by seanthakid** [comment]
> > > i get the same error, no idea why
> > 
> > 
> > If your token is present in the server and can see the channel and is still not able to scrape, it can be because you're in a lot of servers. Try with a fresh token, if it still doesn't work. Use the Discum scraper
> 
> I tried with 10+ fresh tokens none worked. Discum doesn't work either.

Please help me :( I've been trying to fix for weeks now and it's not working :((. It is only on this one particular server that it doesn't scrape. Why is that?

**Comment by V4NSH4J** [comment]
Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol

**Comment by seanthakid** [comment]
> Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol

lol that the one I've been trying to do for like a month now

**Comment by seanthakid** [comment]
> Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol

Invite joiner also doesn't work for that server. Even version 1.7.8. I just want to say, I really appreciate everything your doing, making the code open script and all. You are doing gods work lol. When I make some money, I promise a good amount of it is going to you because this wouldn't be possible without you.

**Comment by V4NSH4J** [comment]
> > Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol
> 
> Invite joiner also doesn't work for that server. Even version 1.7.8. I just want to say, I really appreciate everything your doing, making the code open script and all. You are doing gods work lol. When I make some money, I promise a good amount of it is going to you because this wouldn't be possible without you.

:) I'll check it out tomorrow, would fetch some phone verifieds from somewhere.

**Comment by seanthakid** [comment]
> > > Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol
> > 
> > 
> > Invite joiner also doesn't work for that server. Even version 1.7.8. I just want to say, I really appreciate everything your doing, making the code open script and all. You are doing gods work lol. When I make some money, I promise a good amount of it is going to you because this wouldn't be possible without you.
> 
> :) I'll check it out tomorrow, would fetch some phone verifieds from somewhere.

Let me know what u find out

**Comment by seanthakid** [comment]
> > > Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol
> > 
> > 
> > Invite joiner also doesn't work for that server. Even version 1.7.8. I just want to say, I really appreciate everything your doing, making the code open script and all. You are doing gods work lol. When I make some money, I promise a good amount of it is going to you because this wouldn't be possible without you.
> 
> :) I'll check it out tomorrow, would fetch some phone verifieds from somewhere.

Did u end up checking it out

**Comment by V4NSH4J** [comment]
> > > > Someone sent me discord.gg/rndm I tried it out, turns out it really doesn't work on some servers, just use the offline scraper lol
> > > 
> > > 
> > > Invite joiner also doesn't work for that server. Even version 1.7.8. I just want to say, I really appreciate everything your doing, making the code open script and all. You are doing gods work lol. When I make some money, I promise a good amount of it is going to you because this wouldn't be possible without you.
> > 
> > 
> > :) I'll check it out tomorrow, would fetch some phone verifieds from somewhere.
> 
> Did u end up checking it out

I did, I tried to emulate scrolling on the member list to see what response it gives, but it doesn't return anything on that server for some reason.
