### ISSUE TITLE
Used proxiware but proxies not working

### ISSUE THREAD

**Issue by kramans** [V4NSH4J/discord-mass-DM-GO#177]
Hello,
facing issues with proxies - purchased basic plan on proxiware and it is not working for me.

nl.proxiware.com:12000
pl.proxiware.com:12000
gb.proxiware.com:2000

used it like this but could not connect, any ideas?

**Comment by V4NSH4J** [comment]
IP Authenticated?

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
