### ISSUE TITLE
Scraping : too many files opened

### ISSUE THREAD

**Issue by kramans** [V4NSH4J/discord-mass-DM-GO#178]
How to avoid this error?

2022/02/05 18:40:54 open /Users/nonstop/Desktop/DMdisc-FEB/dmdgo_v1.7.7_darwin_amd64/input/memberids.txt: too many open files
logout

**Comment by V4NSH4J** [comment]
Hi checkout #164

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
