### ISSUE TITLE
Error while change username

### ISSUE THREAD

**Issue by Kirumasuta** [V4NSH4J/discord-mass-DM-GO#179]
Error while changing name: 400 Bad Request {"code": 50035, "errors": {"username": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"}
idk what i can do with this, help me if you can

**Comment by V4NSH4J** [comment]
Have you made sure you've put your names in names.txt? The format is one name per line. The name has to be longer than 2 characters, but shorter than 32. You cannot have words like "discord" in your name and you cannot have a name which 9999 people have already.

**Comment by Kirumasuta** [comment]
thanks
