### ISSUE TITLE
Bypass rules accept button

### ISSUE THREAD

**Issue by origranot** [V4NSH4J/discord-mass-DM-GO#181]
Hey,

Is there a way to bypass this with bots?
![image](https://user-images.githubusercontent.com/48911144/152736186-0daa0440-909d-4482-9adc-b1296b17769d.png)

Same as "Add Reaction" but for this kind of verification.

**Comment by V4NSH4J** [comment]
Hi, if you're talking about the membership screening at the bottom. It's automatically bypassed by the invite joiner

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
