### ISSUE TITLE
Error while opening DM channel: invalid status code while sending request 400 [2]

### ISSUE THREAD

**Issue by ag-labs-sys** [V4NSH4J/discord-mass-DM-GO#182]
Hi,

Getting this error when using the bot with the default message template. Can anyone help fix this issue? Not sure what's going wrong here.

Cheers!

**Comment by V4NSH4J** [comment]
Hi looks like a wrong or blank memberid

**Comment by V4NSH4J** [comment]
Yes these are usernames, not memberids. You should use the scraper to scrape memberids or right click users and copy their IDs
