### ISSUE TITLE
Feature request: welcome message deleter

### ISSUE THREAD

**Issue by telugu-boy** [V4NSH4J/discord-mass-DM-GO#183]
Welcome messages, if sent, are technically under the user's name... so can there be a config option to delete this if sent?

**Comment by V4NSH4J** [comment]
Sorry I didn't understand, what are you trying to do?

**Comment by telugu-boy** [comment]
![image](https://user-images.githubusercontent.com/42505125/152800430-d39c9fbd-744e-4b59-8c14-dabd74af94d8.png)
The system welcome messages can be deleted by the author, I mean @V4NSH4J

**Comment by V4NSH4J** [comment]
Oh, interesting idea will have to look into it
