### ISSUE TITLE
Token Issue

### ISSUE THREAD

**Issue by 1of1b** [V4NSH4J/discord-mass-DM-GO#184]
Does not recognize valid tokens in email:password:token format

**Comment by V4NSH4J** [comment]
Each function has the format it accepts in front of it.

**Comment by 1of1b** [comment]
okay thanks, but i'm trying to use the name changer function and the application just closes

**Comment by 1of1b** [comment]
I can't get the name changer function to work, is there any special requirement for it to work?

**Comment by V4NSH4J** [comment]
Solved?
