### ISSUE TITLE
I WOULD LIKE TO PROPOSE AN IDEA

### ISSUE THREAD

**Issue by 1of1b** [V4NSH4J/discord-mass-DM-GO#185]
is it possible for this tool to dm each new member in a server? it would be awesome to have that feature in the next release

**Comment by V4NSH4J** [comment]
It does not really come under mass DMs. This program is specifically for mass DMing and things you'd need to do that... Maybe another program but might not ever be included in this one haha

**Comment by 1of1b** [comment]
haha i guess so, but when you have a lot of people joining a server, lets say in hundreds over a short period of time, sending them a welcome message will also be a form of mass DM since it's a lot of people you're DMing but this feature is kinda limited to bots only. I would love to see someone develop something like that and i don't mind paying for it lol

**Comment by V4NSH4J** [comment]
Well yeah I see your point ... Maybe some other time some other repository

**Comment by KORKI1** [comment]
I have python program which sends dm to only new users on reaction. Discord: KORKI#5945
