### ISSUE TITLE
Error while getting response from cookie request Get "https://discord.com" : proxyconnect tcp: dial tcp: followed by ip royal proxy invalid port

### ISSUE THREAD

**Issue by srs775** [V4NSH4J/discord-mass-DM-GO#186]
Error while getting response from cookie request Get "https://discord.com" : proxy connect tcp: dial tcp: followed by ip royal proxy invalid port.

Someone in Discord MP telegram says its headers issue.

**Comment by V4NSH4J** [comment]
It's not a header problem. What format are you putting your proxy in

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
