### ISSUE TITLE
Serverid // Scraping 

### ISSUE THREAD

**Issue by taranda2232** [V4NSH4J/discord-mass-DM-GO#187]
Hi, 

I think discord changed something inspite of the Server - Channel IDs. You know cannot the see the server ID anymore, only if you click on a channel and check for the "get link"! if you use those IDs from it, nothing works anymore (Yours and the Discum scraper)

Anybody else having this issue?

**Comment by heroesx3** [comment]
works fine for me right now.

**Comment by V4NSH4J** [comment]
You can right click servers and channels to copy their ID. Watch a YouTube tutorial on it

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
