### ISSUE TITLE
Error 400 H captcha

### ISSUE THREAD

**Issue by williamzhu1** [V4NSH4J/discord-mass-DM-GO#188]
400 Failed to join guild {"captcha_key": ["captcha-required"], "captcha_sitekey": "", "captcha_service": "hcaptcha"}, I get an error like this while trying to join servers

**Comment by origranot** [comment]
I think it's new protection by discord..

**Comment by camolot13** [comment]
same problem let me knbow if yall find fix @origranot @heroesx3 @williamzhu1

**Comment by camolot13** [comment]
![image](https://user-images.githubusercontent.com/99244344/152954561-d2d43a76-d41b-4a18-9130-560d224c3af2.png)

**Comment by ganynmednet** [comment]
hey @V4NSH4J have you released the update? I've got a few updates from the rep, but I suppose it's WIP yet

**Comment by V4NSH4J** [comment]
> hey @V4NSH4J have you released the update? I've got a few updates from the rep, but I suppose it's WIP yet

Yeah, still working on it. Worst case scenario, if I can't bypass it I'll add some captcha APIs

**Comment by cristianberbecaru** [comment]
Same problem here. Let's do this V4NSH4J. Let us know if you need any help !

**Comment by ganynmednet** [comment]
@V4NSH4J Thanks for your work, man. I don't believe in miracles and preparing for Captcha APIs :)

**Comment by V4NSH4J** [comment]
Thank you guys :)

**Comment by zxcspectator** [comment]
V4NSH4J is there any chance to contact you directly? i want to offer you something

**Comment by V4NSH4J** [comment]
V9NSH4J#9494

This issue has been resolved in DMDGO V1.7.8 and subsequent updates.
