### ISSUE TITLE
about bypass

### ISSUE THREAD

**Issue by theroney** [V4NSH4J/discord-mass-DM-GO#192]
![image](https://user-images.githubusercontent.com/38818937/153002629-cd7f04ee-c405-40c2-93d8-e4ba067d084f.png)

**Comment by cristianberbecaru** [comment]
What can we do about this ?

**Comment by cChimney** [comment]
cry

**Comment by theroney** [comment]
actually i shared it to fix the progress of the repo, i have already solved it by myself

**Comment by cristianberbecaru** [comment]
can you share?

**Comment by theroney** [comment]
"v4nsh4j" is already aware of the situation, it will be fixed soon

**Comment by cristianberbecaru** [comment]
oh ok, good to know. cool

**Comment by alexbes00** [comment]
> "v4nsh4j" уже в курсе ситуации, скоро будет исправлено

Thank you for your help.

**Comment by V4NSH4J** [comment]
Hey guys, I've just pushed an update through for DMDGO V1.7.8 You can use solvers like anti-captcha.com or capmonster.cloud to solve the captchas now.

**Comment by cristianberbecaru** [comment]
how can I use the solvers? For ex: anti-captcha.com

**Comment by V4NSH4J** [comment]
> how can I use the solvers? For ex: anti-captcha.com

In your config, in the "captcha_api" field put "anti-captcha.com"
Then head over to anticaptcha, load some balance and copy your API key.
Add it to the config in front of "captcha_api_key" and you should be good to run!

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
