### ISSUE TITLE
Error while getting context Error while getting invite context 429 

### ISSUE THREAD

**Issue by WorldMecha** [V4NSH4J/discord-mass-DM-GO#194]
<img width="470" alt="Capture d’écran 2022-02-08 à 17 33 37" src="https://user-images.githubusercontent.com/97831252/153032181-5d6a5190-ef8a-4021-81c5-3cbd92312be3.png">

**Comment by V4NSH4J** [comment]
Hi, use proxies. Error 429 is Rate limit.

**Comment by WorldMecha** [comment]
Thank you, how can I do that?

**Comment by V4NSH4J** [comment]
Enable proxy_from_file and put your proxies in proxies.txt

**Comment by WorldMecha** [comment]
Okay thank you. So now I always need proxies? Or if I buy other token it will work? I must buy proxies or I can find different way?

**Comment by V4NSH4J** [comment]
It seems like discord is rate limiting too often now, I'll remove some useless parts of the code soon to somewhat fix this but yes to truly avoid the rate limit you'll need better proxies.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
