### ISSUE TITLE
I need your help with the source code.

### ISSUE THREAD

**Issue by DetectMR** [V4NSH4J/discord-mass-DM-GO#198]
I have token generators but there is a module missing in the code can you help me ?
https://i.imgur.com/jRFMqJI.png
my telegram [@mr_d](https://t.me/M_rd2)

**Comment by V4NSH4J** [comment]
https://github.com/bryonpokemon/postuwu-woens-discord-token-generator
Here's the full source of the generator. It has the bypass folder you're looking for as well. Although I'm not sure why you require it as it's patched. You can just delete the import and find another way to solve captchas.

**Comment by DetectMR** [comment]
> https://github.com/bryonpokemon/postuwu-woens-discord-token-generator Here's the full source of the generator. It has the bypass folder you're looking for as well. Although I'm not sure why you require it as it's patched. You can just delete the import and find another way to solve captchas.

So there's no point in having it because it doesn't work? I don't really know the language yet, I'm a beginner and I can't do it myself, are there any such programs just working at the moment ?

**Comment by V4NSH4J** [comment]
> > https://github.com/bryonpokemon/postuwu-woens-discord-token-generator Here's the full source of the generator. It has the bypass folder you're looking for as well. Although I'm not sure why you require it as it's patched. You can just delete the import and find another way to solve captchas.
> 
> So there's no point in having it because it doesn't work? I don't really know the language yet, I'm a beginner and I can't do it myself, are there any such programs just working at the moment ?

Ofcourse there would be someone with a working generator. But most of them get patched as soon as they end up on github. So chances you find one here are highly unlikely... 
The generator you're referring to works you see, it's only the captcha part you'd have to fix.

**Comment by DetectMR** [comment]
> > > https://github.com/bryonpokemon/postuwu-woens-discord-token-generator Вот полный исходный код генератора. В нем также есть папка обхода, которую вы ищете. Хотя я не уверен, зачем вам это нужно, поскольку он исправлен. Можно просто удалить импорт и найти другой способ решения капчи.
> > 
> > 
> > Так что нет смысла иметь его, потому что он не работает? Я еще толком не знаю язык, я новичок и сам не умею, есть ли такие программы, которые просто работают на данный момент?
> 
> Конечно, был бы кто-то с работающим генератором. Но большинство из них исправляются, как только они попадают на github. Так что шансы, что вы найдете его здесь, очень малы... Генератор, о котором вы говорите, работает, вы видите, это только часть капчи, которую вам нужно исправить.

Can you help with the alternator? I can't do it.........

**Comment by V4NSH4J** [comment]
Sure, what do you have in mind?
