### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by NotII** [V4NSH4J/discord-mass-DM-GO#2]
ur a huge skid

**Comment by V4NSH4J** [comment]
And who did I skid from? please provide evidence, I'll send you $1000 BTC

**Comment by NotII** [comment]
I doubt some broke indian has $1000 btc

**Comment by V4NSH4J** [comment]
> 
> 
> I doubt some broke indian has $1000 btc

As I expected, you have no proof. You're just racist. If you have something constructive, feel free to open another Issue or do a pull request. Otherwise, mind your own business.
