### ISSUE TITLE
invite joiner not working with the new captcha thing

### ISSUE THREAD

**Issue by jhnsnow999** [V4NSH4J/discord-mass-DM-GO#200]
the invite joiner doesn't work for you too ? if you try to join in discord there is a new captcha feature

**Comment by cristianberbecaru** [comment]
it is not working for me too

**Comment by V4NSH4J** [comment]
Guys please update to DMDGO V1.7.8
there is an option to use a captcha solver now. You can chose between capmonster.cloud and anti-captcha.com

**Comment by DetectMR** [comment]
all working https://youtu.be/XVJx848TSlQ

**Comment by V4NSH4J** [comment]
Thank you for making this

**Comment by Bouhmid123** [comment]
do i need to subscribe to capmonster for this to work ?

**Comment by V4NSH4J** [comment]
Yes, you need to top up your balance there but it's super cheap. like 3-5$/1000 joins

**Comment by YardRhino** [comment]
context error while getting invite context 429, any ideas how to fix? I have anitcaptcha

**Comment by swtnsss** [comment]
I also used proxies

**Comment by cristianberbecaru** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/32863083/153091674-c0bcdfb4-ae5d-42c4-9a16-08bcb07435f5.png">
what is this error?

**Comment by pashob** [comment]
Where do we add the captcha after we buy it ?

**Comment by V4NSH4J** [comment]
> <img alt="image" width="966" src="https://user-images.githubusercontent.com/32863083/153091674-c0bcdfb4-ae5d-42c4-9a16-08bcb07435f5.png">
> 
> what is this error?

Cloudflare error 1015 Is rate limited you need proxies

**Comment by V4NSH4J** [comment]
> Where do we add the captcha after we buy it ?

Config.json
