### ISSUE TITLE
i get this error when i try to change names? what should i do 

### ISSUE THREAD

**Issue by saouthq** [V4NSH4J/discord-mass-DM-GO#201]
<img width="718" alt="Capture d’écran 2022-02-08 à 21 29 24" src="https://user-images.githubusercontent.com/99272989/153070381-b951a2ef-a758-4f60-aedc-04dd2e6ed5f0.png">

**Comment by V4NSH4J** [comment]
The name changer takes the format email:pass:token if you use any other format, it will print out that error for those tokens. If you have more tokens in your file you can run the threads it will change the names for the right formatted tokens
