### ISSUE TITLE
Is there a version for MacOS

### ISSUE THREAD

**Issue by origranot** [V4NSH4J/discord-mass-DM-GO#202]
?

**Comment by V4NSH4J** [comment]
Yes, this program can be used on most Os/Archs
The Darwin AMD64 file is for MacOS running on Intel chips. Check the releases! If you have an M1 chip MacOS there isn't a release yet so you can build from source (explained in readme) I'll do a release for that as well tomorrow

**Comment by origranot** [comment]
I will wait for your release tomorrow, thanks 👍

**Comment by kllmng3** [comment]
hey, has the MacOS version been released??

**Comment by V4NSH4J** [comment]
> hey, has the MacOS version been released??

Hi yes, the darwin releases are for MacOS. 
AMD64 is for Intel chips
ARM64 is for M1 chips
https://github.com/V4NSH4J/discord-mass-DM-GO/releases/tag/v1.7.8
