### ISSUE TITLE
Server login problem

### ISSUE THREAD

**Issue by zoomikone** [V4NSH4J/discord-mass-DM-GO#203]
When I try to enter the server, it says that I was banned, but this is not so, the tokens are new, https://capmonster.cloud/ is also added and the key to solve the captcha, what's the problem, thanks in advance =)
https://imgur.com/r1Shp4r

**Comment by V4NSH4J** [comment]
Hi, it could be that your IP is banned from the server. Try using a VPN/Proxy

**Comment by swtnsss** [comment]
Enter your choice:
2
Mass DM Advertiser/Spammer
This will DM everyone in memberids.txt from your tokens
Press 1 to use messages from file or press 2 to enter a message:
1
invalid character '1' in string escape code
[17:58:08] Error while setting messages: invalid character '1' in string escape code

Press ENTER to EXIT

Any ideas how to fix this error?

**Comment by DetectMR** [comment]
> Enter your choice: 2 Mass DM Advertiser/Spammer This will DM everyone in memberids.txt from your tokens Press 1 to use messages from file or press 2 to enter a message: 1 invalid character '1' in string escape code [17:58:08] Error while setting messages: invalid character '1' in string escape code
> 
> Press ENTER to EXIT
> 
> Any ideas how to fix this error?

You have an error in your file message.json

**Comment by DetectMR** [comment]
use this example.
`[
  {
    "content": "Hi <user> join my guilded server https://guilded.gg/tos"
  }
]`
