### ISSUE TITLE
looking for beginning of value error code: 1015

### ISSUE THREAD

**Issue by cristianberbecaru** [V4NSH4J/discord-mass-DM-GO#204]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/32863083/153091925-a1c43978-038d-41db-8dcb-48ab36e0cdbb.png">
I'm getting this error. why ?

**Comment by SeebyyDev** [comment]
me too

**Comment by V4NSH4J** [comment]
Cloudflare error 1015 is a rate limit. You need proxies/VPN

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
