### ISSUE TITLE
Successfully joining and bypassing captcha, but when checking immediatly after, tokens arn't in server.

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#206]
Tokens are successfully joining and bypassing captcha, but they just aren't in the server upon checking immediately after
![invite join error](https://user-images.githubusercontent.com/96969678/153102702-73dbc924-e314-4e43-81ab-780fdefa87fb.png)
.

**Comment by V4NSH4J** [comment]
Make sure you put the right serverid. If you did and it says that then the token probably for kicked. You can confirm by logging into it.

**Comment by seanthakid** [comment]
> Make sure you put the right serverid. If you did and it says that then the token probably for kicked. You can confirm by logging into it.

i logged and logged in and tried to join once more. In terminal, it said joined but in discord, it never actually joined? :(

**Comment by V4NSH4J** [comment]
If it says it joint then it joint, it probably got kicked or banned from the server.
