### ISSUE TITLE
error Message.Json

### ISSUE THREAD

**Issue by saouthq** [V4NSH4J/discord-mass-DM-GO#207]
<img width="648" alt="Capture d’écran 2022-02-09 à 07 22 57" src="https://user-images.githubusercontent.com/99272989/153133759-b8aa05c9-c078-49cb-8c40-57c9aef24be8.png">
can you change the "  [ ] " on code pls thanks

**Comment by V4NSH4J** [comment]
Hi, embeds can no longer be sent. Please check the examples in the readme to know the new format

**Comment by saouthq** [comment]
thank you 
btw, i have a mac m1 and the Darwin file works perfectly, no need to use the source file

**Comment by V4NSH4J** [comment]
> thank you btw, i have a mac m1 and the Darwin file works perfectly, no need to use the source file

Interesting, I assumed something for your cpu architecture would give you better performance but it's fine too if there's no problems!

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
