### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by WorldMecha** [V4NSH4J/discord-mass-DM-GO#208]
Hello, how can I fix this error whiteout pay a proxy? Thank you

**Comment by V4NSH4J** [comment]
Discord rate limits your IP. You can use a VPN and keep changing the VPN IP or pay for proxies

**Comment by Setirf32** [comment]
Hello I tried to use a VPN and still have an error but 403 error now..

**Comment by Setirf32** [comment]
<img width="466" alt="Capture d’écran 2022-02-10 à 06 51 14" src="https://user-images.githubusercontent.com/99330942/153346313-b48eaa86-0835-44d4-84cc-25d390db7641.png">

**Comment by V4NSH4J** [comment]
Hi, use DMDGO V1.7.9 I removed this context stuff from it

**Comment by Setirf32** [comment]
Thank you, but I am on Mac and the version is not available.

**Comment by V4NSH4J** [comment]
@Setirf32 I've added binaries for MacOS too.

**Comment by Setirf32** [comment]
Thank you I have another error 403 which the latest version.
<img width="566" alt="Capture d’écran 2022-02-10 à 10 53 13" src="https://user-images.githubusercontent.com/99330942/153382572-47996ab2-609a-4c54-a076-ec75f9af97c1.png">

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
