### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by daikerSec** [V4NSH4J/discord-mass-DM-GO#21]
Can you ask me some tips to bypass  Discord Terms of Service & Community guidelines..My account(s) was terminated.

**Comment by V4NSH4J** [comment]
Automation of discord user accounts also known as "self-bot(s)" is a violation of Discord Terms of Service and Community Guidelines and can get your account disabled, flagged or terminated.  Please do not try to bypass Discord's TOS and keep your account safe.
