### ISSUE TITLE
Error while getting response from cookies request Get "https://discord.com": unexpected EOF Error while getting context error while getting response from cookie request Get "https://discord.com": unexpected EOF

### ISSUE THREAD

**Issue by kong0497** [V4NSH4J/discord-mass-DM-GO#210]
![image_2022-02-09_164718](https://user-images.githubusercontent.com/93990747/153170768-42c325be-2dfa-43c6-ad39-48735ba096b9.png)

Hello, Everytime when I try to use DM GO with proxy it works sometimes but 50% of the time it will show "Error while getting response from cookies request Get "https://discord.com": unexpected EOF
Error while getting context error while getting response from cookie request Get "https://discord.com": unexpected EOF"

What cause this problem?? could it be wrong proxy format or proxy source?

Thanks in advance

**Comment by V4NSH4J** [comment]
Hi, it looks like a connectivity/proxy issue. Which proxies are you using?

**Comment by kramans** [comment]
having the same issue, proxiware is dead and banned by discord, using now litespeed and facing the same issue

**Comment by V4NSH4J** [comment]
Weird, it's highly unlikely they ban the whole proxy service 😅

**Comment by kramans** [comment]
that's what proxiware told me today

**Comment by kong0497** [comment]
> Hi, it looks like a connectivity/proxy issue. Which proxies are you using?

I used private prodivder. it's called zestras proxy. I just tried connect proxy with my own PC. seem like some of the IP is slow some has good connection. I guess that's why some times it's work sometimes it will give that error

**Comment by fireridlle** [comment]
same for me. somethime ok, another doesn't

**Comment by V4NSH4J** [comment]
This is a connection related problem, it could be your proxies or your own internet. I use proxiware proxies and face this error rarely. Reopen if problem persists.
