### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by G4meFreak** [V4NSH4J/discord-mass-DM-GO#212]
Hey, so i was trying to use this but i kept getting this error. I can login with the token just fine.
This is the formate i used

kjaoid@gmail.com:donbie:.gOhA.5PT8WgRA8EadsvoYCGAkGvY
adawdat@gmail.com:1ssjfel:OTQOTQwMU0MzA5MEjIw.gOt8arztsISwotiEBI_n5rtNeVEQ

![Knipsel](https://user-images.githubusercontent.com/87331945/153198273-62921aeb-c3e0-4401-a02d-56db7c4a7aef.PNG)

**Comment by 0xCZMan** [comment]
New discord update I believe, he said in an earlier thread he is working on a fix :)

**Comment by V4NSH4J** [comment]
Hi, the format for joining servers is one token on each line.

**Comment by G4meFreak** [comment]
Yea, i didn't use 6 that was the problem!
