### ISSUE TITLE
How to solve this error

### ISSUE THREAD

**Issue by Bouhmid123** [V4NSH4J/discord-mass-DM-GO#214]
![issue](https://user-images.githubusercontent.com/99221596/153238369-3d9b26b1-2c32-47ef-ba1e-632bc209160f.jpg)

How to fix this issue (i am sure that the password:email:token is valid) ?

**Comment by V4NSH4J** [comment]
Yeah, I think it's the wrong password as well.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
