### ISSUE TITLE
bad gateway?

### ISSUE THREAD

**Issue by felements1337** [V4NSH4J/discord-mass-DM-GO#215]
![Screenshot 2022-02-09 171024](https://user-images.githubusercontent.com/99353127/153253050-7aca074f-01e8-4e47-9660-1f93c2b18409.png)

Hello, can someone understand what this means? I'm trying to mass dm. tokens already in the server.

**Comment by V4NSH4J** [comment]
Hi, the Bad Gateway error is HTTP Response code 502 which is a server side thing as far as I understand. Is the problem persistent? I think it might just be a one time thing

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
