### ISSUE TITLE
invalid token 

### ISSUE THREAD

**Issue by saouthq** [V4NSH4J/discord-mass-DM-GO#216]
when i do tokens checker i get a message that says invalid tokens, after i put proxy and. activate in config, i bought them on proxiware

**Comment by G4meFreak** [comment]
When u press 7 in the menu there is a build in checker!

**Comment by V4NSH4J** [comment]
If you entered tokens in the right format (one token on each line), and your proxies were working then your tokens are wrong/locked.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
