### ISSUE TITLE
Free proxy

### ISSUE THREAD

**Issue by G4meFreak** [V4NSH4J/discord-mass-DM-GO#217]
Hello, i have been working a bit and my own proxy just got banned so i was trying to find a free one but i only get a shit ton of errors. What format should it be in and are there any free working?

-Freek Apeldoorn

**Comment by V4NSH4J** [comment]
Hey, the free ones are usually completely crap dead proxies. You should look into buying some proxies. I recommend https://proxiware.com

**Comment by G4meFreak** [comment]
Yea, i was looking into that but i don't have a credit card or bitcoin wallet. 

BTW how long would i last with 1 gb

**Comment by V4NSH4J** [comment]
You can make a Bitcoin wallet? 
I've no idea how long it will last and there's no way to tell either as different functions different consumptions, it will depend on your use case. Buy 1 GB and try it out on your own...

**Comment by G4meFreak** [comment]
Oh i mean't more that  i don't have any way to buy bitcoin. and i don't have a credit card since i'm only 14.....
