### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by muhy06** [V4NSH4J/discord-mass-DM-GO#22]
Hi I have been to reach you, but no contact/email given. This is my email : muhy06@gmail.com.
Thank you.

**Comment by Abdul0919** [comment]
ini contac me
081290046883

Pada tanggal Sen, 27 Des 2021 04:25, muhy06 ***@***.***>
menulis:

**Comment by V4NSH4J** [comment]
My current Discord is V2NSH4J#6504.
