### ISSUE TITLE
WHY is this so slow ?

### ISSUE THREAD

**Issue by BigBoy2rf00** [V4NSH4J/discord-mass-DM-GO#220]
I want to do a mass dm to hundreds of thousand of people. I am right now sending a dm every 3-4 seconds !? Like why is this so extremely slow. I haveset the delay in the config everywhere to 1 and there is literally no difference

**Comment by seawolph** [comment]
Your proxies probably suck to be honest, no other reason for it.

**Comment by BigBoy2rf00** [comment]
I haven't used any proxies. It's on false

**Comment by BigBoy2rf00** [comment]
I thought it's sending like 100dms per minute

**Comment by V4NSH4J** [comment]
Due to how discord rate limits are structured, you can only send 10 New DMs every 10 minutes. 
You can send them all in 5 seconds then wait 10 minutes or you can send 1 DM every minute makes no difference whatsoever. 
The delay you set in config is only the delay it waits manually. It takes a little bit of time to open DM channels and send DMs, it's not magic. Faster internet could help.

**Comment by BigBoy2rf00** [comment]
But on video it send 100 per minute ?

**Comment by BigBoy2rf00** [comment]
I have 1k phone verified and email verified accounts. There must be a way to send way more dms ?

**Comment by V4NSH4J** [comment]
1k accounts will be sending 10k dms per 10 minutes. 
The more tokens you have the more dms you can send faster

**Comment by BigBoy2rf00** [comment]
Ah thank you for your fast response <3.
I'm gonna buy a token tool from this exordium guy. You know him ? Is he legit  ? Cause I need a lot of tokens

**Comment by BigBoy2rf00** [comment]
The guy on YouTube with like 60k subscribers...

**Comment by V4NSH4J** [comment]
> Ah thank you for your fast response <3. I'm gonna buy a token tool from this exordium guy. You know him ? Is he legit ? Cause I need a lot of tokens

Exordium guy is a 100% scam. You will be ghosted after you've sent the payment. He sells open source programs. The channel is purchased and the engagement is botted.

**Comment by BigBoy2rf00** [comment]
Dayum really ? I was about to spend 50$. I'm broke and I don't have much money. Buy I reay need a token generator

**Comment by BigBoy2rf00** [comment]
If you know a tool who does that. I'm willing to spend money on that

**Comment by BigBoy2rf00** [comment]
Yeah i have seen that with Luna too. It was suspicious but I ended up believing it. Would be too nice finding a tool like that 😔

**Comment by V4NSH4J** [comment]
Yeah, I can give you a guarantee that the guy is 100% scammer. Most of my communities longest standing members found us after being scammed by him... 
You're unlikely to find a token generator in $50, probably looking at a few grand. Better option would be to just buy tokens...

**Comment by BigBoy2rf00** [comment]
But where ? I searched it up and I only found some weird Websites. In hid comments there are people though who say it's legit. Hm ?

**Comment by V4NSH4J** [comment]
> But where ? I searched it up and I only found some weird Websites. In his comments there are people though who say hes legit. Hm ?

https://guilded.gg/tos 
Join here, ask anyone. You'll find hundreds of people who got ripped off by him

**Comment by V4NSH4J** [comment]
![Screenshot_20220210-031142](https://user-images.githubusercontent.com/79518089/153294943-a7c66f96-16f6-4d57-a4a0-3efe8b9ee3bc.jpg)

![Screenshot_20220210-031154](https://user-images.githubusercontent.com/79518089/153294956-6d82ac90-6ec9-47a8-a253-8da6b2f376af.jpg)
Plenty proof on internet too if you search "Exordium scammer"

**Comment by BigBoy2rf00** [comment]
Thank you for Warning. Csn you recommend Websites where I can buy legit tokens from  ?

**Comment by V4NSH4J** [comment]
> Thank you for Warning. Csn you recommend Websites where I can buy legit tokens from ?

There aren't a lot of them out there, market kinda dry and overpriced. Best way would be joining selfbotting communities like the guilded server and buying from reputed people

**Comment by BigBoy2rf00** [comment]
Bist du deutsch ?

**Comment by V4NSH4J** [comment]
> Bist du deutsch ?

Nien

**Comment by BigBoy2rf00** [comment]
Ah alright then. 😅😂. I was so happy. I was working for money to get this exordium guys Tool. I was working so hard for that 50$. Thank you m8

**Comment by V4NSH4J** [comment]
> Ah alright then. 😅😂. I was so happy. I was working for money to get this exordium guys Tool. I was working so hard for that 50$. Thank you m8

Haha no worries. Treat yourself you didn't get scammed by him.
