### ISSUE TITLE
Any idea about this error?

### ISSUE THREAD

**Issue by shurjeelfayyaz1** [V4NSH4J/discord-mass-DM-GO#221]
<img width="638" alt="111" src="https://user-images.githubusercontent.com/94997952/153287194-0d79a991-0834-45ea-a07a-3202389752b6.PNG">

**Comment by V4NSH4J** [comment]
I'll check this out, I had someone else also have the same error today over at guilded.

**Comment by shurjeelfayyaz1** [comment]
Thank you sir. Will be waiting. ☺️

**Comment by V4NSH4J** [comment]
Hi, try out the DMDGO V1.7.9 release

**Comment by shurjeelfayyaz1** [comment]
![image](https://user-images.githubusercontent.com/94997952/153302937-f3adb599-7456-4556-9a95-f5f27cf4659c.png)

**Comment by kramans** [comment]
put your captcha key to solve this problem

**Comment by shurjeelfayyaz1** [comment]
But there are no captchas when I join from my original account. :(

**Comment by V4NSH4J** [comment]
> But there are no captchas when I join from my original account. :(

Captchas only show on accounts which discord thinks might be used for spam
HQ accounts still don't get any captcha

**Comment by shurjeelfayyaz1** [comment]
Can you suggest someone who can give me HQ accounts?

**Comment by V4NSH4J** [comment]
> Can you suggest someone who can give me HQ accounts?

Don't know anyone. Just put a captcha key

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
