### ISSUE TITLE
Error while getting Context Error while getting invite Context (429)

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#222]
getting this lately when doing invite joiner , before that was normal, everything worked with captcha solver etc .

Any Idea?

Thank OP

**Comment by V4NSH4J** [comment]
Heyo, error 429 stands for rate limit. Best solution would be using proxies. Also update to DMDGO V1.7.9 It should work much better as I removed the context stuff.

**Comment by Indica666** [comment]
Thank you OP !

you are legend.

**Comment by kramans** [comment]
living legend, is the update available only for windows?

**Comment by V4NSH4J** [comment]
> living legend, is the update available only for windows?

Yeah for now, it was 4 AM I wanted to sleep so I just did it for windows lol
