### ISSUE TITLE
Mass DM advanced settings

### ISSUE THREAD

**Issue by nikushakhabu** [V4NSH4J/discord-mass-DM-GO#223]
So if I send mass dm advrtising with advanced settings and ask to check if token is on server before dm (I am not joining any tokens beforehand because I will get banned by anti-raid) in that case I assume I will be able to send much less DMs right? because I will be making an extra call to the api before sending every DM so I will be actually able to send much less DMs? or am I wrong

**Comment by V4NSH4J** [comment]
DMs and calls to API are different things. You'll get the same number of DMs.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
