### ISSUE TITLE
Mention @ in the message?

### ISSUE THREAD

**Issue by kramans** [V4NSH4J/discord-mass-DM-GO#224]
Is it possible to mention @ username while sending mass dms?
Thank u in advance G

**Comment by seawolph** [comment]
Yes, use <user>

**Comment by seawolph** [comment]
Use "<user>"

**Comment by seawolph** [comment]
Ugh, it wont let me do it on here.
<> with user in the middle

**Comment by DetectMR** [comment]
write <user>

**Comment by kramans** [comment]
Oh thank you a lot, so this is 100% sure that it will work, am I right?

Example:
Hello, <user>! \n **Hope you have a great day!** \n _Our Developer is magnificent with his tool._ \n https://thisisyourlink.lalala/

**Comment by V4NSH4J** [comment]
Yes looks fine \<user\>

**Comment by kramans** [comment]
Thank you!
