### ISSUE TITLE
Account generators

### ISSUE THREAD

**Issue by nikushakhabu** [V4NSH4J/discord-mass-DM-GO#225]
Has anyone come across good account generator code? (email verified accounts) to reduce costs of buying accounts from forums

**Comment by seawolph** [comment]
Best of luck on that, working ones are not openly available.

**Comment by syf3** [comment]
Just found this https://www.youtube.com/watch?v=XgcLtUfr13I - got it working but a lot of proxies is required and some knowledges, he doesn't give support for this leak..

**Comment by V4NSH4J** [comment]
> Just found this https://www.youtube.com/watch?v=XgcLtUfr13I ([shop](https://pulsar.sellix.io/product/6205198eb6502)) - got it working but a lot of proxies is required and some knowledges, he doesn't give support for this leak..

You are a scammer, using my name to scam people. I have no such repository public or private.
