### ISSUE TITLE
How to speed up captcha

### ISSUE THREAD

**Issue by kllmng3** [V4NSH4J/discord-mass-DM-GO#226]
Hey,ive used 300 tokens to join a server and its been over three hours - any ideas on how to speed it up 
![image](https://user-images.githubusercontent.com/99277195/153342708-2e4cda53-5043-44a3-981e-5f04bb621041.jpeg)

![image](https://user-images.githubusercontent.com/99277195/153342718-0ba4e89c-0e91-4613-8368-d69736e12bbd.jpeg)

**Comment by V4NSH4J** [comment]
Use more threads. You can put 0 and they should join in a couple minutes

**Comment by kramans** [comment]
Btw, if I want to change the joining time to the server and close the Terminal - will it try to add again the same tokens to the same server?

Left my pc overnight but it went to sleep randomly
