### ISSUE TITLE
WHY MY TOKENS GET BANNED

### ISSUE THREAD

**Issue by Bouhmid123** [V4NSH4J/discord-mass-DM-GO#229]
So when i try to check tokens without using proxies , it says that all accounts are working but as soon as i put a proxy it bans all of my token ( i use proxiware)

**Comment by V4NSH4J** [comment]
It does not ban them, there's probably something with connection which causes it to not even check the tokens.

**Comment by kramans** [comment]
the tool is just down, tokens should be valid, checker aint working that well

**Comment by V4NSH4J** [comment]
> the tool is just down, tokens should be valid, checker aint working that well

Tool is not down.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
