### ISSUE TITLE
Error 404, 405

### ISSUE THREAD

**Issue by JeremyMeissner** [V4NSH4J/discord-mass-DM-GO#23]
Hi,
When I try to use the 2) I have the error `Token MYTOKEN is locked or disabled. Stopping instance. 405 405: Method Not Allowed`
![token](https://user-images.githubusercontent.com/34174370/147452234-c4c52799-5a51-4c02-945d-458cadb38056.png)

Does anyone know why?

**Comment by V4NSH4J** [comment]
Hi, I don't think you've loaded in the members in .\input\memberids.txt 

Use Discum's scraper to scrape members from the server you wish to DM and add it there

**Comment by JeremyMeissner** [comment]
I found the problem.

In the `.\input\memberids.txt` there was the id of the account I was testing with.
