### ISSUE TITLE
Profile Picture & Username Won't Change

### ISSUE THREAD

**Issue by kramans** [V4NSH4J/discord-mass-DM-GO#230]
Hello, 

Facing difficulties once changing profile pictures and usernames.
1. Username:pass:token format in token.txt
2. Change username (changes just a couple of them and stops running)
3. Change profile picture (changes just a couple of them and stops running)

Any ideas? Is there some bug in it?
Maybe the tool is down?
Any other tools recommended for this?
Can I somehow checked whether the usernames and profile pictures are changed for all tokens?
Will my tokens be banned after trying it multiple times??

Thank you

**Comment by ColegoneCrazy** [comment]
have we figured out this issue? if so please update me, currently having this issue !
