### ISSUE TITLE
scarping dont work anymore. But i have the newest version

### ISSUE THREAD

**Issue by Sanchez452** [V4NSH4J/discord-mass-DM-GO#231]

**Comment by kramans** [comment]
having same issue, scraps max 10k and closes the terminal, maybe any other tool available for this? except py or py with guidance?

**Comment by Sanchez452** [comment]
i cant scrape any id. used proxies and campmonster to join. token still valid but scarping doesnt work

**Comment by Sanchez452** [comment]
i got error with websocket but i download the new version

**Comment by kramans** [comment]
same here....

**Comment by kramans** [comment]
or /Users/ssss/Desktop/MASS DM TOOL NEW 10:02.7/input/memberids.txt: too many open files

**Comment by kllmng3** [comment]
yea im getting the same issue, it doesn't scrape any ids

**Comment by V4NSH4J** [comment]
Jesus Christ how many times will I answer this same thing. The too many open files thing is not related to the tool, it's related to your Operating System. Please see #164  
Run the program from a command prompt / terminal window so it doesn't close if and when it crashes so atleast we have an error. Everyday, I answer to 500 people who message me saying, "It is not working". I can't spend 6 hours asking them what is not working? Do you have an error code? Give me no information at all and expect me to solve it.
If you don't like the scraper, use the Discum scraper. If both of them don't work and you think you did everything correctly then the server can't be scraped move on.
