### ISSUE TITLE
you keep ignoring me

### ISSUE THREAD

**Issue by zxcspectator** [V4NSH4J/discord-mass-DM-GO#232]
V4NSH4J, i want to order a software, can u give me ur telegram or whatever? i am asking 3rd time, you just ignored me for some reasons, if u aint working with anybody, just let me know, no need to ignore :c

**Comment by V4NSH4J** [comment]
> V4NSH4J, i want to order a software, can u give me ur telegram or whatever? i am asking 3rd time, you just ignored me for some reasons, if u aint working with anybody, just let me know, no need to ignore :c

I don't ignore anyone, I just get overwhelmed with the number of messages. My telegram is @campingarunner

**Comment by nastyatimosha** [comment]
> V4NSH4J, i want to order a software, can u give me ur telegram or whatever? i am asking 3rd time, you just ignored me for some reasons, if u aint working with anybody, just let me know, no need to ignore :c

you are such an idiot! why you ask that you need the software??? you don't even know how to download the shit?? is free fucking bastard! learn how to do this! why you bother V4 asking that you need the fucking software? do you need v4 put the software inside your asshole??? for such lazy greedy idiots as you.. v4 decided to quit! go fuck yourself!

**Comment by V4NSH4J** [comment]
> > V4NSH4J, i want to order a software, can u give me ur telegram or whatever? i am asking 3rd time, you just ignored me for some reasons, if u aint working with anybody, just let me know, no need to ignore :c
> 
> you are such an idiot! why you ask that you need the software??? you don't even know how to download the shit?? is free fucking bastard! learn how to do this! why you bother V4 asking that you need the fucking software? do you need v4 put the software inside your asshole??? for such lazy greedy idiots as you.. v4 decided to quit! go fuck yourself!

Eyo eyo calm down no one's quitting! Where'd you hear that?
