### ISSUE TITLE
Error code 1015

### ISSUE THREAD

**Issue by Setirf32** [V4NSH4J/discord-mass-DM-GO#233]
<img width="562" alt="Capture d’écran 2022-02-10 à 17 05 02" src="https://user-images.githubusercontent.com/99330942/153447205-3992dc35-24b8-4555-8b3f-ca6457ca7b6f.png">
Hello, someone can help me I bought for captcha and new token and I have this error

**Comment by Setirf32** [comment]
I buy on proximate and now I have this.
<img width="561" alt="Capture d’écran 2022-02-10 à 17 30 41" src="https://user-images.githubusercontent.com/99330942/153452354-d2eddeb3-2081-413c-8fcd-c82fe615b27f.png">
.
Can you help me please?..

**Comment by V4NSH4J** [comment]
Bad proxies
