### ISSUE TITLE
Failed to bypass token when joining

### ISSUE THREAD

**Issue by pashob** [V4NSH4J/discord-mass-DM-GO#242]
![err](https://user-images.githubusercontent.com/99305394/153524533-8a305aef-662b-44ed-9fd9-5b62c2352d5b.png)
What might the cause of this be?

**Comment by V4NSH4J** [comment]
Login to the token and see, probably got kicked from the server or there are no channels.

**Comment by V4NSH4J** [comment]
Anti-Raid probably
Many servers have restrictions - instant ban new accounts / accounts without pfp or accounts if they join too fast

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
