### ISSUE TITLE
Changing name stuck

### ISSUE THREAD

**Issue by fireridlle** [V4NSH4J/discord-mass-DM-GO#244]
In the middle of the changing name, seems like process stuck and no new logs apears

**Comment by V4NSH4J** [comment]
How many tokens? And could you search up the last token on your token list? Maybe it's completed

**Comment by fireridlle** [comment]
200 tokens. the last logged token somewhere in the middle of tokens.txt

**Comment by V4NSH4J** [comment]
I'll add some logging in the future to check the progress
