### ISSUE TITLE
NAME CHANGER NOT WORKING

### ISSUE THREAD

**Issue by 1of1b** [V4NSH4J/discord-mass-DM-GO#245]
I just started getting this error while trying to use the name changer command
<img width="676" alt="error" src="https://user-images.githubusercontent.com/97744408/153577712-c775f5ad-6c6f-4340-a171-b5585e0680c8.png">

**Comment by V4NSH4J** [comment]
Have you loaded your tokens.txt ?

**Comment by 1of1b** [comment]
yes but i got it working, thank you

**Comment by V4NSH4J** [comment]
Glad to know
