### ISSUE TITLE
Open Input/failed.txt: NO SUCH FILE

### ISSUE THREAD

**Issue by Alvinthomas122** [V4NSH4J/discord-mass-DM-GO#246]
![B36D37F3-B00F-4D6E-8096-C0375075A6DD](https://user-images.githubusercontent.com/99506713/153657099-3f0ebdaa-b5c7-40b5-ad97-081cd94d4184.jpeg) please how do I fix this on Mac? 
“Open input/failed.txt” No such file or directory
Also with 
“Open input/completed.txt” No such file or directory 
These files are already in ‘input’. 
Thanks

**Comment by V4NSH4J** [comment]
Make sure you're using the right binary if you downloaded from releases. Darwin files are for mac. AMD64 is for intel chips and ARM64 is for M1 chips. If that doesn't fix it, try building from source.

**Comment by V4NSH4J** [comment]
Reopen if problem persists.
