### ISSUE TITLE
When invite im get "Error while unmarshalling body"

### ISSUE THREAD

**Issue by Jij8ui** [V4NSH4J/discord-mass-DM-GO#25]
When using invite to server I get the error "Error while unmarshalling body invalid character 'e' looking for beginning of value". I understand that this means I entered the wrong invite code, but it is correct and some tokens successfully enter the server, but after that I get this error

**Comment by V4NSH4J** [comment]
Hi, this is usually the beginning of the cloud flare rate limit error message. Please use a VPN or use proxies.
