### ISSUE TITLE
Benefit of use_proxy_for_gateway

### ISSUE THREAD

**Issue by jonahbill22** [V4NSH4J/discord-mass-DM-GO#253]
Hello,

at first I want to thank you for your good work!

What is the benefit of using use_proxy_for_gateway 'true'?

'Set to true, websocket connections will use proxy as well. Recommend keeping it at false unless you have very good proxies.'
What defines a good proxy? Clean proxy or wss proxy (and not http)?

**Comment by V4NSH4J** [comment]
Hi thank you!
There's no benefits really, discord hasn't been banning/disabling for things done over websocket. It's just an extra option there for you to use it you want to use proxies in the websocket connection. It drains data pretty fast too.
A good proxy is a fast & private proxy (https)
