### ISSUE TITLE
Error while users connecting to discord server

### ISSUE THREAD

**Issue by b0tn3t000** [V4NSH4J/discord-mass-DM-GO#254]
I'm having issue when users connecting to discord server and in console writes out that everyone has connected but when I check is it true or no it writes out me that only half of them are on the server. I mean that 90-80 % tokens are in server, but when I check them manually with "Token Server Check" there only 50-40% in server. Another half is banned from this server. Is this problem with program or no? I'm using full verifed tokens and high-quality proxies
![image](https://user-images.githubusercontent.com/78261745/153723384-804274cf-10a3-4509-9e93-7c087ff6e2bc.png)

**Comment by V4NSH4J** [comment]
The server probably has anti-raid measures which kick your tokens.

**Comment by V4NSH4J** [comment]
Use higher delays. I've gone into very depth about this in the readme if you want to learn more about it.

**Comment by roberrti** [comment]
I have used proper delays. my tokens accepted in server but when I start DMs then after 76 DMs my tokens kicked out from server. What is solution of this?

**Comment by V4NSH4J** [comment]
> I have used proper delays. my tokens accepted in server but when I start DMs then after 76 DMs my tokens kicked out from server. What is solution of this?

I can't really say as there's not one solution to every server. All servers have different anti-raids. They can be checking different things really. I've seen some people join thousands of tokens to lag out the anti-raids and quickly mass DM everyone. It really depends on the server.

**Comment by roberrti** [comment]
I have joined 25 tokens in same server manually, they stayed in that server, but when I joined by using captcha service then server kicked out my tokens.

**Comment by roberrti** [comment]
It is happening, brother.

**Comment by roberrti** [comment]
If it's server then those token which I have joined manually are there in that server. why ?

**Comment by V4NSH4J** [comment]
> If it's server then those token which I have joined manually are there in that server. why ?

Because of higher and random delay probably which it would've taken you to join the server. If you don't like the joiner, don't use it. I'm not going to repeat for the 5th time that it's the anti-raid.

**Comment by roberrti** [comment]
sorry, can you please tell me one thing more I am facing this issue while inviting ( Error while unmarshalling body invalid character 'e' looking for beginning of value error code: 1015
[17:43:38] Error while joining: invalid character 'e' looking for beginning of value )  
Can you please tell me solution of this?

**Comment by V4NSH4J** [comment]
https://github.com/V4NSH4J/discord-mass-DM-GO#q-invalid-character-e-looking-for-beginning-of-value-error-code-1015

**Comment by roberrti** [comment]
You have updated old version. waow Love you bro

**Comment by roberrti** [comment]
Just last Question, sorry for wasting your time. I have read Question (What is membership screening/ minimum security of servers preventing me from DMing?) 
I just want to confirm that it is passed by manually only?

**Comment by V4NSH4J** [comment]
> Just last Question, sorry for wasting your time. I have read Question (What is membership screening/ minimum security of servers preventing me from DMing?) I just want to confirm that it is passed by manually only?

It is bypassed automatically by the invite joiner as long as your account meets the requirements of the server. Only sometimes servers require you to wait 10 minutes before DMing.
