### ISSUE TITLE
How to use proxy from file?

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#255]
what is the correct format for login pass proxy to put in the proxy txt?

could not find it here 

if anyone can help please, thanks !

bless you OP

**Comment by V4NSH4J** [comment]
Hi! The format is user:pass@ip:port

**Comment by pscpc** [comment]
I have a question about proxy too. Do i have to use proxy_from_file true or can i just type my port in config.json

**Comment by V4NSH4J** [comment]
You can make a new field named "proxy" which and add your proxy as a string in the format IP:port or User:Pass@IP:port

**Comment by moonsquanch** [comment]
Hi, I'm trying to use proxiware proxies and cannot get the to work. I changed the "proxy_from_file" to true, and put a couple proxies in the proxies.txt file. I tried in domain:port and IP:port format but they still not work. In the IP:port format it looks like its trying but it times out. Thank you
