### ISSUE TITLE
Someone grabbed my tokens

### ISSUE THREAD

**Issue by poe-god** [V4NSH4J/discord-mass-DM-GO#257]
Someone grabbed my tokens and all the tokens I have in the bot.

**Comment by AustinPrograms** [comment]
Ok

**Comment by AustinPrograms** [comment]
not a issue

**Comment by V4NSH4J** [comment]
Lol thanks for your tokens

**Comment by poe-god** [comment]
> Lol thanks for your tokens

Oh. Nice
