### ISSUE TITLE
NAME CHANGES BUT 1 NAME IS GETTING USED FOR MULTIPLE ACCOUNTS EVEN AFTER HAVING A LOT OF NAMES

### ISSUE THREAD

**Issue by hynfort** [V4NSH4J/discord-mass-DM-GO#259]

**Comment by hynfort** [comment]
HEY THE ISSUE ON MY TITLE FIX?

**Comment by hynfort** [comment]
Bro but I put like 1000 names for 100 accounts but still they repeated

**Comment by hynfort** [comment]
+ I have another query my captcha is taking so much time i am using anti captcha

**Comment by V4NSH4J** [comment]
> * I have another query my captcha is taking so much time i am using anti captcha

If the captcha is taking time, you probably should increase your max bid on anti-captcha or use Capmonster. If joining is taking time because of less threads, just increase your threads.

**Comment by hynfort** [comment]
Can you please guide me it will really help me

**Comment by hynfort** [comment]
what happens if I increase it @V4NSH4J

**Comment by V4NSH4J** [comment]
You pay more for captchas but they give you priority. It's really all explained on their website

**Comment by hynfort** [comment]
Bro the name problem is still there like I have 100 names and 50 accounts so every account should have a random name but they don't

**Comment by V4NSH4J** [comment]
> Bro the name problem is still there like I have 100 names and 50 accounts so every account should have a random name but they don't

All of them have same name?

**Comment by hynfort** [comment]
No but quite a few

**Comment by V4NSH4J** [comment]
It really is a random thing, maybe try more names? Maybe they all had the same name before and some name changes failed so it looks like a lot of them didn't change names

**Comment by V4NSH4J** [comment]
Added a scraper in op8, you can scrape names.
