### ISSUE TITLE
When i am starting Mass DM advertiser, all my bought and verified accounts get banned in 5 minutes 

### ISSUE THREAD

**Issue by minimor** [V4NSH4J/discord-mass-DM-GO#260]
Help me please to fix this. When i am starting Mass DM advertiser, all my bought and verified accounts get banned in 5 minutes.

**Comment by Indica666** [comment]
did you use proxy?

**Comment by V4NSH4J** [comment]
Yeah, did you use proxy? Also it could be that your tokens were flagged.

**Comment by V4NSH4J** [comment]
Reopen if problem persists
