### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by oxyuranus1** [V4NSH4J/discord-mass-DM-GO#261]
How the bot connects the proxies? 2 tokens for 1 proxy, 3 tokens for 1 proxy or 1 token for 1 proxy? How are proxies from file distributed among tokens? What proxies are better to use?

**Comment by Indica666** [comment]
u can use one rotating proxy from file

**Comment by V4NSH4J** [comment]
Hi, one proxy is assigned to each token randomly from the file. 
The token uses that one proxy for everything.

**Comment by oxyuranus1** [comment]
> Hi, one proxy is assigned to each token randomly from the file. The token uses that one proxy for everything.

So, if I have proxies less than tokens, 100 tokens and 50 proxies for example, will they be evenly distributed over all tokens?

**Comment by V4NSH4J** [comment]
Not evenly realistically, but ideally yeah.
