### ISSUE TITLE
2 New Errors ive never seen before

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#262]
*using fully ver tokens 

*using rotating proxy

>invite joiner :

base delay 30 sec

random delay 5 sec

threads : 3
------
Error 1: 
Error while getting response from cookies request get : https://discord.com/ :EOF ] Error while getting cookies: %!v (MISSING)

Error 2:
Error while unmarshelling body invalid character 'e' looking for beginning of value error code : 1015

Thanks

(most of tokens joint )

**Comment by V4NSH4J** [comment]
Error 1 is a proxy/connection thing

Error 2 is cloudflare's rate limit. You need proxies/VPN to circumvent it
