### ISSUE TITLE
online scraper dosent work

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#265]
![issue scrape](https://user-images.githubusercontent.com/99367991/153878489-67997b4a-2d54-4dc7-a7f1-37b6ae03088e.png)

**Comment by Indica666** [comment]
can you please explain ? it works on a similar server

**Comment by DaddyCalder** [comment]
If people in a server have a role or multiple roles the scraper does not work on them. It only works on accounts with no server role.

**Comment by Indica666** [comment]
.
