### ISSUE TITLE
bot stuck

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#266]
![error 23](https://user-images.githubusercontent.com/99367991/153927337-7a217b3b-772a-41ae-9e33-1e2561dcffe6.png)

**Comment by DaddyCalder** [comment]
Bad proxies it looks like

**Comment by Indica666** [comment]
im using IP Royal

**Comment by GG23s** [comment]
got same problem with packetstream.... only proxyware working good for me....

**Comment by V4NSH4J** [comment]
Yeah, issue with slow proxies. You can increase timeout in config to wait longer for responses.
https://proxiware.com proxies are working fine. 
Make sure y'all using Statics from file

**Comment by kujoez** [comment]
> Yeah, issue with slow proxies. You can increase timeout in config to wait longer for responses. https://proxiware.com proxies are working fine. Make sure y'all using Statics from file

wait so rotating isn't recommended? I thought static list of proxies don't read line by line on here.

**Comment by Indica666** [comment]
> Yeah, issue with slow proxies. You can increase timeout in config to wait longer for responses. https://proxiware.com proxies are working fine. Make sure y'all using Statics from file

what would be a recommend increase in 'timeout'? rn is 60

**Comment by V4NSH4J** [comment]
Timeout 60 is fine. You can increase to 120 if you want to wait longer. And yes static proxies are recommended
