### ISSUE TITLE
account got termed

### ISSUE THREAD

**Issue by cateee69** [V4NSH4J/discord-mass-DM-GO#27]
my main got termed and i cant join your server can you provide me your username/tag.

your cat
EDIT: LOL the server got termed

**Comment by ItsChasa** [comment]
server got beemed by discord
![image](https://user-images.githubusercontent.com/79016507/147988122-5f31a163-bef0-4d60-8c0d-f90e8f127d44.png)

**Comment by ItsChasa** [comment]
you will be missed <3

**Comment by cateee69** [comment]
i got banned in the ban wave

**Comment by ItsChasa** [comment]
> i got banned in the ban wave

i haven't yet, but I've backed up my account (using my tool which u can buy :wink:) just in case

**Comment by cateee69** [comment]
imma make one and then sell it 😉

**Comment by ItsChasa** [comment]
> imma make one and then sell it 😉

bet

**Comment by cateee69** [comment]
for 1$

**Comment by ItsChasa** [comment]
> for 1$

stonks

**Comment by cateee69** [comment]
waiting for V4NSH4J or Siegfried reply

**Comment by ItsChasa** [comment]
same

**Comment by V4NSH4J** [comment]
Hi guys, we are making the servers and stuff right now! Both V4NSH4J and Siegfried accounts are termed.

**Comment by V4NSH4J** [comment]
https://discord.gg/bJQSCzXkwc
New server

**Comment by cateee69** [comment]
cool
