### ISSUE TITLE
Websocket closed when scraping online members

### ISSUE THREAD

**Issue by Desoxyribon** [V4NSH4J/discord-mass-DM-GO#270]
Hey does someone know how to fix that error when scraping online members?
Websocket closed error while reading message from websocket: websocket: close 4004: Authentication failed
Tokens are valid and tried on multiple servers tried it with mail verified and phone+mail verified nothing seems to work.
When i try to use Token Onliner it just activated debug mode and nothing happens

**Comment by V4NSH4J** [comment]
Sure you're using the right format for tokens?
