### ISSUE TITLE
DM only new server users

### ISSUE THREAD

**Issue by KORKI1** [V4NSH4J/discord-mass-DM-GO#272]
Hello V4NSH4J, 
 
Maybe you're interesting in my python program which DM new server users?
Would be great to update your Discord-mass-DM-GO bot

Contact me: Discord KORKI#5945

**Comment by V4NSH4J** [comment]
Hey! It doesn't really come under mass DMs. If I ever release it, it'll be in a seperate repository.

**Comment by ciribo-sys** [comment]
KORKI#5945 is a fucking scammer ..

**Comment by ciribo-sys** [comment]
don't deal with him
