### ISSUE TITLE
Prevent messages to be marked as spam

### ISSUE THREAD

**Issue by GG23s** [V4NSH4J/discord-mass-DM-GO#273]
Guys do you know what makes messages that we send to be marked as spam?
How can we prevent it or how to make it less likely to be marked ?
Is there a way to check if your msg-s are marked as spam?

Thanks for the answers!

**Comment by V4NSH4J** [comment]
Hey, you'd have to look at the token from another account to see if it's marked as spam. Usually accounts flagged at generation are marked as spam. One example of getting flagged is when you get locked while registering and use a phone number to unlock.

**Comment by V4NSH4J** [comment]
Reopen if problem persists
