### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#276]
Error while Solving Captcha: error creating the request for captcha [Post "https://api.capmonster.cloud/createTask": net/http: TLS handshake timeout]

(i have CAPTCHA SOLVER + Rotating Proxy)

**Comment by V4NSH4J** [comment]
Rotating proxy in config or in file?

**Comment by Indica666** [comment]
file

**Comment by V4NSH4J** [comment]
Try using sticky proxies
