### ISSUE TITLE
message from file

### ISSUE THREAD

**Issue by jermz1** [V4NSH4J/discord-mass-DM-GO#277]
trying to embed a message within the bot, every time I press 1 to use message from file an error message appears "json: cannot unmarshal object into go value of type []utilities.Message any help?

![IMG_0688](https://user-images.githubusercontent.com/98884245/154328673-570431a1-5875-4902-a6dd-1252687575cc.jpg)

**Comment by Indica666** [comment]
u cant use embed anymore

**Comment by jermz1** [comment]
with this particular bot? or in general?

**Comment by V4NSH4J** [comment]
In general, you can't send embeds anymore. Only possible with website links now. Also add a pair of [] around your message if you haven't already

**Comment by jermz1** [comment]
Thank you for your response, any theories on how these are still able to do it?

<img width="411" alt="Screenshot 2022-02-16 at 20 39 14" src="https://user-images.githubusercontent.com/98884245/154353250-0cc26dfd-a5d7-408e-9ba8-90a2ebbf3a81.png">

**Comment by V4NSH4J** [comment]
> Thank you for your response, any theories on how these are still able to do it? (sent to my dm's 5 days ago)
> 
> <img alt="Screenshot 2022-02-16 at 20 39 14" width="411" src="https://user-images.githubusercontent.com/98884245/154353250-0cc26dfd-a5d7-408e-9ba8-90a2ebbf3a81.png">

Checkout #124 for explanation on what this is

**Comment by jermz1** [comment]
Thank you, can you provide me with a link to the server so I can see the detailed in-depth explanation please? the invite link is invalid.

**Comment by V4NSH4J** [comment]
> Thank you, can you provide me with a link to the server so I can see the detailed in-depth explanation please? the invite link is invalid.

The server got terminated
