### ISSUE TITLE
IP:Port dosent work from proxies.txt

### ISSUE THREAD

**Issue by Indica666** [V4NSH4J/discord-mass-DM-GO#278]
it shows my tokens are invalid , when i switch back to the other provider with the other format (user:passwrod@ip:port) it works

the problem is , proxiware do not provide it in the format that it reads from proxies.txt . 

am i doing something wrong?

Thanks

**Comment by V4NSH4J** [comment]
Hi, it may be that you haven't Authenticated your IP on proxiware. Make sure you've authenticated it and are using the right IP (No VPN or anything; if using VPN authenticate VPN IP)
Thing with token checker is that, it only considers a token valid only if everything works well and it's valid. If it gets proxy error when checking token it will show token as invalid.
