### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by D3JOC1K** [V4NSH4J/discord-mass-DM-GO#280]
I know this tool is free, and im really appreciate it, and also i asked V4NSH4J to pay him for discord token generator but he dont wanna do it for money xD so i got question to all of you. 

Can you recommend me any token seller? My last 3 supplier are finished now

**Comment by yung-guzzy** [comment]
Same with my suppliers tried some tokens from guy named ivanshop
idk if his tokens are shit or im doing incorrectly but i get 20-30 dms and he say his customers get up to 100

**Comment by syf3** [comment]
How  much are you willing to offer for a generator of thousand tokens per day ?  You already know that a batch of HQ tokens cost arround $50. You can take contact with me on discord at **Gossy#8841** to ask details, and might reserve a slot for daily generation - if you are willing to offer like $100, you can continue to buy batchs from script kiddies and their shit tokens.

**Comment by V4NSH4J** [comment]
> How much are you willing to offer for a generator of thousand tokens per day ? You already know that a batch of HQ tokens cost arround $50. You can take contact with me on discord at **Gossy#8841** to ask details, and might reserve a slot for daily generation - if you are willing to offer like $100, you can continue to buy batchs from script kiddies and their shit tokens.

You yourself are a script kiddie and a scammer

**Comment by syf3** [comment]
Not this time, the generator is ready and the "scam" was removed :)

**Comment by V4NSH4J** [comment]
> Not this time, the generator is ready and the "scam" was removed :)

LMAO, you tried to use my name to scam people. The video was skidded from Luna Gen's video which was a fake generator too. In the description you put that it's my (V4NSH4J's) leaked generator and were charging people like 200$ for it. 
You are 100% a scammer whatever you comment here. You can say anything to make yourself feel good but you're a no-skill script kiddie and scammer. Only know how to steal money.

**Comment by syf3** [comment]
Anyway, cost is about 3k$. These guys which didn't understand how everything works will get scammed by your token sellers - you know these 0.04$ tokens generated with self brought domain, just sayin

**Comment by syf3** [comment]
If you want a proof, just contact me at **Gossy#8841** and give me discord names for newly created tokens and a server invite to let them join on creation. You will have the tokens to test them.

**Comment by V4NSH4J** [comment]
> Anyway, cost is about 3k$. These guys which didn't understand how everything works will get scammed by your token sellers - you know these 0.04$ tokens generated with self brought domain, just sayin

Funny coming from you. Go get a job instead of scamming people off their hard earned money.

**Comment by syf3** [comment]
I can't do nothing for your bad users, they get scammed by getting tokens without knowing what they are doing.

**Comment by V4NSH4J** [comment]
I don't want to have to deal with low IQ skiddy scammers here. Scam people elsewhere.

**Comment by syf3** [comment]
Trusting is a grand word here.

**Comment by V4NSH4J** [comment]
> Trusting is a grand word here.

It is, considering you have a history of scamming and you used my name to scam. And you're still trying to scam people from the community that I built. Sir for you, trusting is the grandest word which no one will ever do with you.

**Comment by syf3** [comment]
low IQ which made a token generator. The low IQ here is the guys buying these tokens from your telegram.

**Comment by syf3** [comment]
I will not ruin your community :)

**Comment by V4NSH4J** [comment]
> low IQ which made a token generator. The low IQ here is the guys buying these tokens from your telegram.

You didn't make shit. If you did make shit you wouldn't be scamming people earlier selling fake gens. People may be gullible enough to fall for your scam but you're the skid here. Go get a job at starbucks or something instead of scamming people and calling them low iq lmao

**Comment by V4NSH4J** [comment]
And go away from my community, I don't want people like you here.

**Comment by syf3** [comment]
stop emoraging boy. error is human, and it was a bit fun. Now the real fun can begin, anyway, real users which need a tokens generator are first, not here, and they have ino not the money, as they are "working" hard a day to buy a batch of 500 self-domain verified at $60 .

**Comment by V4NSH4J** [comment]
Yes you made a whole video with a fake generator and used my name to scam by error for fun. You're a scammer, nothing gonna change that so fuck off I'll delete everything you write after this comment. Get a life idiot

**Comment by GG1services** [comment]
Best tokens on the market by far  https://ggservices.sellix.io/ 

V4nsh4j #1 dev

**Comment by syf3** [comment]
> Best tokens on the market by far https://ggservices.sellix.io/
> 
> V4nsh4j #1 dev

It's like a scam, selling these tokens is nothing more than a scam, and people are asking themselve why they are getting their tokens as spammer..

**Comment by syf3** [comment]
@GG1services You also get a good copy of the ``tokenfarmer` shop - look like you are a king 🤦‍♂️

**Comment by syf3** [comment]
@V4NSH4J edit this one please 🍆

**Comment by VANSH4J** [comment]
🍆

**Comment by fonko** [comment]
i am confused XD

**Comment by V4NSH4J** [comment]
> i am confused XD

His name is VANSH4J 
My name is V4NSH4J with 2 4's 
He's trying to scam people with my name lol

**Comment by smith2122** [comment]
> > i am confused XD
> 
> 
> 
> His name is VANSH4J 
> 
> My name is V4NSH4J with 2 4's 
> 
> He's trying to scam people with my name lol 

How can I connect with you on telegram or Discord?
