### ISSUE TITLE
Proxies not working

### ISSUE THREAD

**Issue by moonsquanch** [V4NSH4J/discord-mass-DM-GO#282]
Hi, I'm trying to use proxiware proxies and cannot get the to work. I changed the "proxy_from_file" to true, and put a couple proxies in the proxies.txt file. I tried in domain:port and IP:port format but they still not work. In the IP:port format it looks like its trying but it times out. Thank you

**Comment by V4NSH4J** [comment]
Hi, try putting more proxies in the list and also authenticate your IP if you hadn't 
IP:port format is supported

**Comment by D3JOC1K** [comment]
Which proxy are you recommend to use?

**Comment by KORKI1** [comment]
It's because discord add session_id. I have coded a new program to bypass server join and tokens don't get locked. If you need one. Discord: KORKI#5945

**Comment by dtsrgb** [comment]
> It's because discord add session_id. I have coded a new program to bypass server join and tokens don't get locked. If you need one. Discord: KORKI#5945

@V4NSH4J already fixed that in new version, released 15 minutes ago

**Comment by dtsrgb** [comment]
> also authenticate your IP if you hadn't

What do you mean by that? Username:password?

**Comment by moonsquanch** [comment]
They work now, it was a matter of binding my IP in proxiware. Thanks
