### ISSUE TITLE
SSL Certificate_Verify_Failed 

### ISSUE THREAD

**Issue by limjame28** [V4NSH4J/discord-mass-DM-GO#283]
![Screen Shot 2022-02-17 at 11 55 42](https://user-images.githubusercontent.com/96048882/154409158-27cfa8ee-7b41-4a21-bf38-b318ae45255e.png)

Hello i got this error when running scrape.py . Any suggestion ?

**Comment by V4NSH4J** [comment]
Try opening an issue on Discum's repository for support on it, I'm not sure
