### ISSUE TITLE
 Error while joining: invalid character 'e' looking for beginning of value

### ISSUE THREAD

**Issue by AndyJZheng** [V4NSH4J/discord-mass-DM-GO#29]
Hey! i'm getting this error when trying to join servers... does anybody know what it could be? 

can you help me out with this error :33] Error while joining: invalid character 'e' looking for beginning of value
Error while unmarshalling body invalid character 'e' looking for beginning of value
[18:20:33] Error while joining: invalid character 'e' looking for beginning of value
Error while unmarshalling body invalid character 'e' looking for beginning of value
[18:20:33] Error while joining: invalid character 'e' looking for beginning of value
Error while unmarshalling body invalid character 'e' looking for beginning of value

**Comment by V4NSH4J** [comment]
You are rate limited, use a rotating proxy in your config or use a VPN
