### ISSUE TITLE
invite joiner error (?)

### ISSUE THREAD

**Issue by fonko** [V4NSH4J/discord-mass-DM-GO#297]
hey guys, most likely this is a ultra noob question. I just started using this took, looks really great but i am getting this message when i try to add my tokens to my server so i can start with the juicy part.

[19:24:46] Error while Solving Captcha: unknown error [1]
[19:24:46] Error while Solving Captcha: unknown error [1]
[19:24:46] Captcha detected, solving...
[19:24:47] Captcha detected, solving...
[19:24:47] Captcha detected, solving...

And none of the users get into the server. What am i doing wrong? i can see in your video that you just got all your users instantly added to yoru server.

**Comment by teplinsky-maxim** [comment]
Hello! Seems like Discord changed something since the latest release, so we need to find out what did they change. According to other issues, they have now added `session_id`, which has to be passed across different interactions such as button click (and probably joining guild, not quite sure)

**Comment by smith2122** [comment]
I had same issues, have you added your captcha AIP details in the config file? And have you updated to the latest update of the mass dm. Should be working

**Comment by D3JOC1K** [comment]
Same for me. New update or something. New wait for update ;/

**Comment by V4NSH4J** [comment]
> hey guys, most likely this is a ultra noob question. I just started using this took, looks really great but i am getting this message when i try to add my tokens to my server so i can start with the juicy part.
> 
> [19:24:46] Error while Solving Captcha: unknown error [1] [19:24:46] Error while Solving Captcha: unknown error [1] [19:24:46] Captcha detected, solving... [19:24:47] Captcha detected, solving... [19:24:47] Captcha detected, solving...
> 
> And none of the users get into the server. What am i doing wrong? i can see in your video that you just got all your users instantly added to yoru server.

You have to put your captcha key in config. There is no session ID in joining servers yet, only for button interactions. Anyone trying to sell you something saying they added session ID is a scammer.

**Comment by fonko** [comment]
what is captcha key?
