### ISSUE TITLE
all my tokens get locked instant

### ISSUE THREAD

**Issue by GG23s** [V4NSH4J/discord-mass-DM-GO#298]
What's the problem guys ? The tool needs update maybe ? 
Tokens lock instants no matter what seller i use... Everything was perfect before 1 day..
Maybe Discord got update ?

**Comment by GG23s** [comment]
I think tokens get fucked by Captcha service.. i use anti captcha .. what service you use ?

**Comment by yung-guzzy** [comment]
> I think tokens get fucked by Captcha service.. i use anti captcha .. what service you use ?

This can easily be true because when you register tokens you get captcha too, and if you solve it incorrectly on first try account will get flagged with very high chance.

**Comment by Sanchez452** [comment]
The problem is by joining. when you try to join your without captcha solver,,,, everything work.

**Comment by TechnoFrost27** [comment]
> I think tokens get fucked by Captcha service.. i use anti captcha .. what service you use ?

which anti capthca service do u use and how

**Comment by KORKI1** [comment]
It's because discord add session_id. I have coded a new program to bypass server join and tokens don't get locked. If you need one. Discord: KORKI#5945

**Comment by GG23s** [comment]
do capmonster.cloud doesn't work for joining too ?


На пт, 18.02.2022 г. в 10:10 ч. Sanchez452 ***@***.***>
написа:

**Comment by V4NSH4J** [comment]
I've pushed a small update, I don't expect tokens to not get locked. LQ Tokens will get locked atm. You can try using proxies while solving captcha so the captcha and server join is on the same IP.
