### ISSUE TITLE
#TokenLivesMatter

### ISSUE THREAD

**Issue by pizzalover32** [V4NSH4J/discord-mass-DM-GO#30]
i wouldnt recommend using this tool or other tools like nebula spammer astaroth owl spammer etc. discord has patched nebula spammer (i learned the hard way by losing 50 tokens) just wanna tell you guys to not use any spammers

**Comment by ColinChau123** [comment]
Whwere is the new server

**Comment by ColinChau123** [comment]
> i wouldnt recommend using this tool or other tools like nebula spammer astaroth owl spammer etc. discord has patched nebula spammer (i learned the hard way by losing 50 tokens) just wanna tell you guys to not use any spammers

Want to buy tokens off me https://sellix.io/TokensRUs

**Comment by V4NSH4J** [comment]
> i wouldnt recommend using this tool or other tools like nebula spammer astaroth owl spammer etc. discord has patched nebula spammer (i learned the hard way by losing 50 tokens) just wanna tell you guys to not use any spammers

This tool still works

> Whwere is the new server

Working on it lol
