### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by D3JOC1K** [V4NSH4J/discord-mass-DM-GO#300]
![image](https://user-images.githubusercontent.com/98923777/154695867-6f4268df-a3d9-4f85-8a22-26cf3b9f2653.png)

**Comment by D3JOC1K** [comment]
Same issue on all servers ;/ Was ok today, and in 1 minute all tools stop works.

**Comment by yung-guzzy** [comment]
I am no expert, but I heard that discord can now request captcha when you send DM. I am pretty sure DM-GO doesn't detect captcha on DM thats why you get this error.

**Comment by V4NSH4J** [comment]
Error 429 is a rate limit, you need proxies /VPN
