### ISSUE TITLE
Error while changing name: error while getting cookie error while getting response from cookie request Get "https://discord.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by DMG-G** [V4NSH4J/discord-mass-DM-GO#301]
changing nicknames constantly freezes

**Comment by D3JOC1K** [comment]
Just dont change

**Comment by KORKI1** [comment]
It's because discord add session_id. I have coded a new program to bypass server join and tokens don't get locked. If you need one. Discord: KORKI#5945

**Comment by V4NSH4J** [comment]
Slow proxies, don't use proxies or increase timeout in config.
