### ISSUE TITLE
BRO EVERYONE IS HAVING THE SAME ISSUE WHILE SERVER JOINING EITHER THE TOKEN GETS BANNED OR CAPTCHA TAKES SO MUCH TIME

### ISSUE THREAD

**Issue by hynfort** [V4NSH4J/discord-mass-DM-GO#302]
BRO EVERYONE IS HAVING THE SAME ISSUE WHILE SERVER JOINING EITHER THE TOKEN GETS BANNED OR CAPTCHA TAKES SO MUCH TIME

**Comment by achraf190** [comment]
Yeah me to. captcha keeps trying to solve

**Comment by D3JOC1K** [comment]
Dont complaint for free tool. Always you can do tool by yourself... He will fix it probably today or tomorrow.

**Comment by D3JOC1K** [comment]
Everyone got same problem. Im trying to send dms but its hard... but what can i do... just wait

**Comment by hynfort** [comment]
are you getting any issues on server  joining

**Comment by hynfort** [comment]
Like its slow and it locks after one join

**Comment by Sanchez452** [comment]
Discord change something with captcha by joining

**Comment by D3JOC1K** [comment]
He is the King !

**Comment by KORKI1** [comment]
It's because discord add session_id. I have coded a new program to bypass server join and tokens don't get locked. If you need one. Discord: KORKI#5945

**Comment by rakkervleesje** [comment]
I think its working now after the new update from DMDGO but i got now problem with chaning the avatars with the new update.

**Comment by rakkervleesje** [comment]
Because of the keep solving captcha, its eating my funds so fast...

**Comment by xBytez5636** [comment]
> KORKI#5945

update to 1.8.0

**Comment by V4NSH4J** [comment]
Use Anti-Captcha and DMDGO V1.8.1 
Can't fix the locking issue but can reduce it. It works with HQ Tokens
