### ISSUE TITLE
tokens locking instantly and websocket connection error

### ISSUE THREAD

**Issue by dcl121589** [V4NSH4J/discord-mass-DM-GO#303]
hey idk whats going on with the dmgo but im having an issue. my tokens are getting burned instantly and then when it does bypass verification i have issues with the websocket. is there a new discord patch? and if so will you be doing an update soon?

**Comment by dcl121589** [comment]
"Error while unmarshalling body from fingerprint request unexpected end of JSON input"

**Comment by dcl121589** [comment]
im trying to generate phone verifying tokens but having a hard time, do you know how to use sms activate?

**Comment by V4NSH4J** [comment]
You haven't mentioned anything about websocket errors. But the joiner is working only with HQ tokens at the moment. Use DMDGO V1.8.1
