### ISSUE TITLE
Error while changing avatar after update 1.8.0: 

### ISSUE THREAD

**Issue by rakkervleesje** [V4NSH4J/discord-mass-DM-GO#304]
I got error while trying to change the avatar after the new update from DMDGO 1.8.0. 

Error while changing avatar: Patch "https://discord.com/api/v9/users/@me": read tcp

**Comment by dcl121589** [comment]
hey bro where is the 1.8.0 download? i have 1.7.9

**Comment by JeanCarlosAG** [comment]
https://github.com/V4NSH4J/discord-mass-DM-GO/releases/tag/v1.8.0
Do you have the owner's discord link?

**Comment by V4NSH4J** [comment]
Connection error. Use better proxies or no proxies.
