### ISSUE TITLE
joining error and unknown message

### ISSUE THREAD

**Issue by dcl121589** [V4NSH4J/discord-mass-DM-GO#305]
everytime i try to join a server the captchas take forever and then i get spammed red with these messages and then big blocks of random numbers and letters  ive never seen before. can someone tell me whats going on please
![dmdgo error](https://user-images.githubusercontent.com/99930909/154771626-fa1e9d1a-3d27-4eea-98c8-864c96b2279e.png)
![dmdgoerror2](https://user-images.githubusercontent.com/99930909/154771628-e3472d91-52f9-4755-b989-c187c056b51c.png)
.

**Comment by xBytez5636** [comment]
you use mail verified tokens to get in a phone verified discord
captcha working fine, u just need to use other tokens.. create a server ur self and join them there, should work,.

**Comment by V4NSH4J** [comment]
Yeah, you were either using email tokens in a server which needs phone verification or your tokens got locked while joining.
