### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by mjr7829** [V4NSH4J/discord-mass-DM-GO#307]
idk what proxy i have to put to make the code work pls help

**Comment by D3JOC1K** [comment]
There is no issue. Just buy premium Proxy. Stop charging 6$ per 1k dms and do it well... charge more and buy better proxy. Work perfect ! Thanks Vanshaj!

**Comment by xBytez5636** [comment]
> There is no issue. Just buy premium Proxy. Stop charging 6$ per 1k dms and do it well... charge more and buy better proxy. Work perfect ! Thanks Vanshaj!

yours not getting banned after a dm? even my 3week old ones got instant locked after dm, for the rest tool works awesome!

**Comment by D3JOC1K** [comment]
Yes i got some insta locks thats true.

**Comment by V4NSH4J** [comment]
You need HQ tokens to DM at the moment. I personally use proxiware proxies.
