### ISSUE TITLE
Websocket error when sending DMs

### ISSUE THREAD

**Issue by lakers4lyfe** [V4NSH4J/discord-mass-DM-GO#308]
When sending mass DMs, I continuously get this error. Occasionally 4 or 5 DMs will go through before it goes back to spamming this error. Tokens are in the correct format. I've tried with and without "use_proxy_for_gateway"

The error I'm getting is:

Websocket closed error while reading message from websocket: websocket: close 4004: Authentication failed

**Comment by V4NSH4J** [comment]
Are you using any websocket functions or used op8 scraper on the same instance by any chance?

**Comment by lakers4lyfe** [comment]
I am not
  
  
  
  
  
  
  

  
  
>

**Comment by lakers4lyfe** [comment]
After further investigation, it appears that after it cycles to the next token - and if the token is invalid - then it gets stuck in a loop, continuously giving that error. Once I checked the tokens using the token checker, and started doing it again, then it worked. It only worked until once again a token was invalid, then it once again started giving that error.
