### ISSUE TITLE
Instant ban after 1st message proxy or proxyless. even 3 week old accounts get banned that worked before...

### ISSUE THREAD

**Issue by xBytez5636** [V4NSH4J/discord-mass-DM-GO#309]

**Comment by xBytez5636** [comment]
![image](https://user-images.githubusercontent.com/100011125/154786529-287d9b26-91b7-41cf-b94b-4b10f1f350f0.png)

**Comment by D3JOC1K** [comment]
Get better proxy. But yes its happen very often.

**Comment by xBytez5636** [comment]
> Get better proxy. But yes its happen very often.

what site you recommend? I got packetstream , proxiware , iproyal,

**Comment by xBytez5636** [comment]
> Get better proxy. But yes its happen very often.

always used this proxy without a problem, but since 1.7.9 since captcha update, everything gets instant lockt. captcha is working tho

**Comment by V4NSH4J** [comment]
Flagged tokens unfortunately, combined with the low captcha score from the solving services makes it so that only HQ tokens can work at the moment. I've added several options in DMDGO v1.8.1 like proxies for solving captcha so you can try getting a higher score on it.
