### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by pizzalover32** [V4NSH4J/discord-mass-DM-GO#31]
it's tosfollower a few mintues after nova was streaming I left and got my account phone locked i made new accounts/used tokens i had and it always got locked i need to join that server back i keep getting locked😭😭

**Comment by pizzalover32** [comment]
I've also used a vpn and still locked

**Comment by AndyJZheng** [comment]
same here

**Comment by V4NSH4J** [comment]
Eyo the exact same thing happened to pretty much all of us. People had their token stocks randomly phone locked. Give it a few hours and try making a new account or purchase a disposable number.

**Comment by pizzalover32** [comment]
> Eyo the exact same thing happened to pretty much all of us. People had their token stocks randomly phone locked. Give it a few hours and try making a new account or purchase a disposable number.

no like even if i make a new account and try to join the server i instantly get phone locked

**Comment by pizzalover32** [comment]
i made another account and i didnt email verify joined server but as soon as i email verify it got instantly locked

**Comment by V4NSH4J** [comment]
This was happening to Siegfried too, try using incognito with VPN and make account on a new mail (no dot trick or anything)

**Comment by pizzalover32** [comment]
> This was happening to Siegfried too, try using incognito with VPN and make account on a new mail (no dot trick or anything)

i tried it still locked upon signing up i got locked i don't why it keeps asking for phone verification

**Comment by V4NSH4J** [comment]
> > This was happening to Siegfried too, try using incognito with VPN and make account on a new mail (no dot trick or anything)
> 
> i tried it still locked upon signing up i got locked i don't why it keeps asking for phone verification

Buy a disposable Number?

**Comment by pizzalover32** [comment]
i don't have any form of payment
