### ISSUE TITLE
Captcha problem by joining isnt soleved. With capmonster.cloud all tokens get instantly banned by joining. Only when it joins a server without captcha, everything works

### ISSUE THREAD

**Issue by Sanchez452** [V4NSH4J/discord-mass-DM-GO#310]

**Comment by xBytez5636** [comment]
I tried the Tool OneDash it also seems a problem there. the problem is also with the dming, after sending a message it instant locks

**Comment by V4NSH4J** [comment]
Discord has become strict with their captchas. Every tool using solver APIs will only work with HQ tokens. Also upgrade to DMDGO v1.8.1
