### ISSUE TITLE
Its disgusting..

### ISSUE THREAD

**Issue by taranda2232** [V4NSH4J/discord-mass-DM-GO#311]
.. to see how pushy some here are towards Vanshaj.

Didnt you guys read the updated release? 

Note: This **was released early in hopes of fixing problems** with server joining. Any problems which arise will be addressed in V1,8.1

Just wait for him to look into it and find a solution. You can count yourself lucky, that somebody has been build this open sorce. Otherwhise you couldnt do anything at all. GIVE HIM SOME CREDIT!!!

Always this negativity but never a nice word.

I tested the updated version with couldmonster and yes, strong verifies on server kick your tokens off of it immediately. Low verifies kind of work, 100 tokens used, 50 survived within the first 5 minutes. 

Again, he will sort things out, just wait. 

Give that man a cookie for his project, or a whole truck load if it.

**Comment by D3JOC1K** [comment]
Agreed

**Comment by V4NSH4J** [comment]
Thank you, I've tried fixing some stuff in V1.8.1 but the problem still persists. I am looking for solutions and will update it if I find anything.
