### ISSUE TITLE
Does Packetstream working for captcha solving by proxies?

### ISSUE THREAD

**Issue by Sanchez452** [V4NSH4J/discord-mass-DM-GO#312]

**Comment by V4NSH4J** [comment]
Packetstream proxies are kind of slow. The proxy requirements for anti-captcha and capmonster are strict with anti-captcha only allowing proxies with lower than 2s response times and several other conditions met. You'd get error code 25 if your proxy requirements aren't met. You can read about all the proxy requirements of anti-captcha [here](https://anti-captcha.com/faq/510_questions_about_solving_recaptcha_with_proxy__applies_to_funcaptcha__geetest__hcaptcha_) 
I'm assuming they'd be similar for capmonster and 2captcha however capmonster does not allow IP Authenticated proxies while Anti-Captcha does.

**Comment by xBytez5636** [comment]
use indonesian proxy's from packetstream. they work great and fast (only this country)
