### ISSUE TITLE
server joiner is working good for me right now! (full verified)

### ISSUE THREAD

**Issue by xBytez5636** [V4NSH4J/discord-mass-DM-GO#315]
DM'ing is not working yet, after 1 message all instant lock.   --> Websocket Closed Authentication Failed (locked)

I tried proxy and proxyless
Proxy's from IPRoyal 

Thanks for 1.8.1 , looking forward to 1.8.2 , love your work dev!

**Comment by V4NSH4J** [comment]
Haha thanks for your kind words but it's not really working if you're getting disabled after 1 DM. Don't worry, if we figure out something we will push an update.

**Comment by V4NSH4J** [comment]
#351
