### ISSUE TITLE
How to use mobile proxie?

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#316]
@V4NSH4J You're doing extremely cool stuff. Thank you for your hard work, you're awesome.

Guys, does anybody use mobile proxies here? I have a link that changes IP per request, how can I use it? 😃 

And about general proxies, which one do you use guys: IPv4 or IPv6?

**Comment by V4NSH4J** [comment]
<3 IPV4 proxies
You should prefer using static proxies. 
You can put proxies in proxies.txt format is user:pass@ip:port or ip:port
It necessarily doesn't need to be ip, it can be hostname too.
