### ISSUE TITLE
Error while getting response from cookies

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#317]
Does anyone aware of this issue?

![image](https://user-images.githubusercontent.com/89306625/154811994-480cd7ef-1dcd-47fa-9904-c25203b80d7f.png)

**Comment by xBytez5636** [comment]
Yes i do as well

**Comment by bimbi221** [comment]
could we find a solution? xD

**Comment by dtsrgb** [comment]
Most likely proxies issue. I'm testing the solution now, most likely we didn't bind IP correctly

**Comment by mjr7829** [comment]
what can i do if i don t have  proxy what i can do?

**Comment by mjr7829** [comment]
how can i get a free proxy

**Comment by D3JOC1K** [comment]
dont use free proxy. you earning money on mass dm, and you want get free tool / proxy and maybe token also? 10$ per 1gb, just charge more than bargain money for service ;)

**Comment by mjr7829** [comment]
can you tell me the safest and best sites to buy proxies?

**Comment by V4NSH4J** [comment]
You need high quality proxies. Sometimes the proxy doesn't connect and you'd get errors like that. This does not affect your token life though if you're worried about that.
