### ISSUE TITLE
lots of tokens locking instantly

### ISSUE THREAD

**Issue by dcl121589** [V4NSH4J/discord-mass-DM-GO#318]
everytime i try to DM, messages will go through but 50% will be locked instantly and burned, whats the issue

**Comment by dtsrgb** [comment]
Most likely tokens are not good enough
![image](https://user-images.githubusercontent.com/89306625/154816257-a27ee7a4-d01e-4006-8591-86d1ada5e990.png)

**Comment by dcl121589** [comment]
they are gmail, hotmail, and yahoo verified tokens. do you think thats not a high enough quality token?? im making fully verified  now but they take so long to create.

**Comment by yung-guzzy** [comment]
I know this is a shameless plug, but I have a solution to server joining issue
https://discord.gg/XQk9abEj
Open a ticket 👉😊

**Comment by V4NSH4J** [comment]
Hey, try 2captcha with proxy_for_captcha enabled. It's working very well for me.

**Comment by xBytez5636** [comment]
> Hey, try 2captcha with proxy_for_captcha enabled. It's working very well for me.

 by using proxy_for_captcha enabled do you also enable the proxy from file? Im running IP Royal Royal Residential right there
