### ISSUE TITLE
Program just instantly closes when 

### ISSUE THREAD

**Issue by swtnsss** [V4NSH4J/discord-mass-DM-GO#319]
Program instantly closes when I use invite joiner (sorry for bad title I accidentally posted before I was finished)

**Comment by swtnsss** [comment]
Update this only happened trying to join one server, no error codes nothing, switched servers and it worked

**Comment by V4NSH4J** [comment]
Hey, could you open up a command prompt, drag the binary to it and run it from there to see the error before crash?

**Comment by Gercekefsane** [comment]
> Hey, could you open up a command prompt, drag the binary to it and run it from there to see the error before crash?

I have same problem

[16:11:14] Enter base delay for joining in seconds (0 for none)
0
[16:11:14] Enter random delay to be added upon base delay (0 for none)
0
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/zenthangplus/goccm.(*concurrencyManager).WaitAllDone(...)
        C:/Users/ComputerName/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:118
main.Options()
        C:/Users/ComputerName/Desktop/discord-mass-DM-GO-main/main.go:118 +0x8f16
main.main()
        C:/Users/ComputerName/Desktop/discord-mass-DM-GO-main/main.go:38 +0xea

goroutine 5 [chan receive]:
github.com/zenthangplus/goccm.(*concurrencyManager).controller(0xc00001e540)
        C:/Users/ComputerName/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:71 +0x2c
created by github.com/zenthangplus/goccm.New
        C:/Users/ComputerName/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:61 +0x16f
PS C:\Users\ComputerName\Desktop\discord-mass-DM-GO-main>

**Comment by xBytez5636** [comment]
[02:32:50] Captcha detected, solving...
panic: runtime error: index out of range [1] with length 1

goroutine 20 [running]:
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Instance).SolveCaptchaCapmonster(0xc0001a0000, {0xc00000c540, 0x24}, {0xc0001c0000, 0xa5})
        D:/Desktop/discord-mass-DM-GO-main/utilities/captcha.go:57 +0x1669
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Instance).SolveCaptcha(0xc0001a0000, {0xc00000c540, 0x24}, {0xc0001c0000, 0xa5})
        D:/Desktop/discord-mass-DM-GO-main/utilities/captcha.go:18 +0x16c
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Instance).Invite(0xc0001a0000, {0xc000121060, 0x8})
        D:/Desktop/discord-mass-DM-GO-main/utilities/extra.go:287 +0x859
main.Options.func1(0x0)
        D:/Desktop/discord-mass-DM-GO-main/main.go:109 +0x56
created by main.Options
        D:/Desktop/discord-mass-DM-GO-main/main.go:108 +0x8d9f

**Comment by V4NSH4J** [comment]
> > Hey, could you open up a command prompt, drag the binary to it and run it from there to see the error before crash?
> 
> I have same problem
> 
> [16:11:14] Enter base delay for joining in seconds (0 for none) 0 [16:11:14] Enter random delay to be added upon base delay (0 for none) 0 fatal error: all goroutines are asleep - deadlock!
> 
> goroutine 1 [chan receive]: github.com/zenthangplus/goccm.(*concurrencyManager).WaitAllDone(...) C:/Users/ComputerName/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:118 main.Options() C:/Users/ComputerName/Desktop/discord-mass-DM-GO-main/main.go:118 +0x8f16 main.main() C:/Users/ComputerName/Desktop/discord-mass-DM-GO-main/main.go:38 +0xea
> 
> goroutine 5 [chan receive]: github.com/zenthangplus/goccm.(*concurrencyManager).controller(0xc00001e540) C:/Users/ComputerName/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:71 +0x2c created by github.com/zenthangplus/goccm.New C:/Users/ComputerName/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:61 +0x16f PS C:\Users\ComputerName\Desktop\discord-mass-DM-GO-main>

Sometimes Anti-virus software disallow DMDGO from accessing files, try disabling or adding as exception or use a sandbox or VM.
