### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KeparYTbcc** [V4NSH4J/discord-mass-DM-GO#32]
![image](https://user-images.githubusercontent.com/67996155/148145400-96d44089-60c4-4f75-8163-f7a9541cf9ef.png)

**Comment by KeparYTbcc** [comment]
![image](https://user-images.githubusercontent.com/67996155/148145673-84023f25-0966-4102-ab67-5fcf1db1a090.png)

**Comment by purkey1** [comment]
how do you get to that page

**Comment by V4NSH4J** [comment]
Hi, the program finds all the important files relative to the binary. If you do `go run main.go` the binary is created in some temporarily directory and is not able to find the associated files (tokens, config, etc) 

The right way of running it would be building it `go build` in the right directory
