### ISSUE TITLE
websocket error after scrape input

### ISSUE THREAD

**Issue by dcl121589** [V4NSH4J/discord-mass-DM-GO#320]
this just started happening, as soon as i go to scrape op8 offline i get this error. i have tried to change my proxy list a couple of different times and i still get the same error. i have proxy to gateway set on true and its always seemed to work, not sure what the problem is. is proxy format still the same?? username:password@IP:Port ??
![websocket](https://user-images.githubusercontent.com/99930909/154820421-90a14037-a83b-42b6-a7c6-1260ed939ac4.png)

**Comment by dcl121589** [comment]
is proxy format still the same?? username:password@IP:Port ??

**Comment by V4NSH4J** [comment]
Hi, are you surely on the latest version of DMDGO?
