### ISSUE TITLE
Problem with proxy / joining servers / 

### ISSUE THREAD

**Issue by D3JOC1K** [V4NSH4J/discord-mass-DM-GO#321]
What proxy are you recommend to use. Yesterday when i used premium proxy was great. Today is horrible, and i cant send dms.

**Comment by yung-guzzy** [comment]
I know this is a shameless plug, but I have a solution to server joining issue
https://discord.gg/XQk9abEj
Open a ticket 👉😊

**Comment by V4NSH4J** [comment]
Hi, I was using 2captcha along with proxy_for_captcha enabled. The tokens don't lock anymore.
