### ISSUE TITLE
do i need an proxy to use the dm mas bot?

### ISSUE THREAD

**Issue by mjr7829** [V4NSH4J/discord-mass-DM-GO#323]
idk much about proxies and idk if i have to use one to use the dm bot. if it is yes, which website is the best for buying proxies?
pls help

**Comment by post04** [comment]
You do not need proxies to use the tool, if you want proxies however, iproyal works fine.

**Comment by mjr7829** [comment]
ok and idk how to activate the tool on 1.18.1 can you help me?

**Comment by mjr7829** [comment]
i mean can i use the dm mass tool without proxy?

**Comment by mjr7829** [comment]
![image](https://user-images.githubusercontent.com/100002519/154859420-0148f89d-c731-4433-8401-ac01f8a3e6a2.png)
it shows this idk what to do

**Comment by mjr7829** [comment]
i have solved it thanks
