### ISSUE TITLE
Token invalidation due to Websocket

### ISSUE THREAD

**Issue by sergio-msilva** [V4NSH4J/discord-mass-DM-GO#328]
Hey, I was using the bot to scrape users from a server while using proxyscrape's premium proxies and although they seemed to be able to join the server (message confirming "Joint guild"), I didn't see them there and when running the scrape command it returned the following eror message:
Websocket closed error while unmarshalling incoming websocket message: json: cannot unmarshal bool into Go struct field Event.d of type utilities.Data

Someone alerted me to the fact that the token were only email verified and if the server had phone verification they would die instantly, but then I don't know if the joint guild message was valid.  
I'm in no ways an experienced dev so any help/insights on this would be very appreciated!

**Comment by xBytez5636** [comment]
this is true if they are only mmail verified they cant join a phone verified server. Also when a token asks for a command that is not possible it will be flagged by discord and yes this can cause an instant lock. i recommend using full verified

**Comment by V4NSH4J** [comment]
Hi, just restart DMDGO after using the scraper. The websocket functions cannot invalid the tokens. But the invite joiner can if you don't have HQ tokens atm. 
>Someone alerted me to the fact that the token were only email verified and if the server had phone verification they would die instantly, 
This is also not true, if you do that you'll be asked to phone verify but you won't be phone locked. They're different things. You will still be able to use your tokens.
