### ISSUE TITLE
Token is locked

### ISSUE THREAD

**Issue by shawnlunsford** [V4NSH4J/discord-mass-DM-GO#33]
It says the token is locked when dm advertising, I'm confused.

**Comment by V4NSH4J** [comment]
Hey, this could mean that you might be using tokens in a wrong format or wrong tokens! 
If you try using email:pass:token format with massdm you'll get error 401 (unauthorised) which will be counter as a lock although it wouldn't be
It can be that or your accounts could have been flagged in the recent discord ban-wave. They flagged tons of domains tokens were made on, the way to know this would be logging into a token and sending few dms manually.

**Comment by bigmikky10** [comment]
I have been texting you on new discord but no replies. Tokens are getting locked. What could be the issue?

**Comment by V4NSH4J** [comment]
> I have been texting you on new discord but no replies. Tokens are getting locked. What could be the issue?

What's your username? Tokens aren't getting locked because of the program but because of the flagged domains

**Comment by shawnlunsford** [comment]
Sorry but was dealing with an issue I could easily solve, I apologize!

**Comment by V4NSH4J** [comment]
No worries, feel free to open another issue if you require assistance with anything.
