### ISSUE TITLE
files not showing up after commands are run 

### ISSUE THREAD

**Issue by heavenlysovereign** [V4NSH4J/discord-mass-DM-GO#331]
every time i try to run anything the files just dont show up
 **Error while getting necessary data: open C:/Users/User/AppData/Local/Temp/go-build166743335/b001/exe/config.json: The system cannot find the file specified.**
not sure what to do from here on out, havent changed anything on "config.json" either, only entered my tokens in a email,pass,token format just to change names so far. i have the same issue with every other option after changing format as well, 
 **Error while opening tokens.txt: open C:/Users/User/AppData/Local/Temp/go-build146153211/b001/exe/input/tokens.txt: The system cannot find the path specified.**
**Error while reading bios.txt: open C:/Users/User/AppData/Local/Temp/go-build1009637915/b001/exe/input/bios.txt: The system cannot find the path specified.**

i've checked the paths just dont get created and only exist up to "C:\Users\User\AppData\Local\Temp\go-build1009637915\b001\exe\discord-mass-dm-GO.exe"

**Comment by heavenlysovereign** [comment]
nevermind i fixed it i didnt compile it correctly, but now i'm geting a different error, 

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/zenthangplus/goccm.(*concurrencyManager).WaitAllDone(...)
        C:/Users/vansh/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:118
main.Options()
        D:/Desktop/discord-mass-DM-GO-main/main.go:118 +0x8f16
main.main()
        D:/Desktop/discord-mass-DM-GO-main/main.go:38 +0xea

goroutine 6 [chan receive]:
github.com/zenthangplus/goccm.(*concurrencyManager).controller(0xc00007b3b0)
        C:/Users/vansh/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:71 +0x2c
created by github.com/zenthangplus/goccm.New
        C:/Users/vansh/go/pkg/mod/github.com/zenthangplus/goccm@v0.0.0-20211005163543-2f2e522aca15/goccm.go:61 +0x16f

C:\Users\User\Desktop\DMDGO_v1.8.1_windows_amd64>


i am attempting to use invite joiner, single invite, 20 threads(tried 0 and 10, same issue), 10 base delay, 10 random delay.

**Comment by V4NSH4J** [comment]
I think your tokens aren't loading, have you made sure to add your tokens in tokens.txt
Sometimes it has happened that anti-virus software has prevented DMDGO from accessing files, if that's the case, you could try on a VM with anti-virus disabled or DMDGO added as an exception. Reopen if your problem persists. Sorry for the late reply.
