### ISSUE TITLE
Tokens getting kicked immediately after joining guild.

### ISSUE THREAD

**Issue by BTCoasis** [V4NSH4J/discord-mass-DM-GO#334]
Thanks for your work V4nsh4j, really great product you have built here and, very efficient. 

But it seems as though Discord may have updated in the last few days as i have been running the bot effectively but as of last night my tokens get kicked from the server immediately after they have joined the guild. Tokens are HQ and have worked previously, Proxies HQ and anticaptcha is on..

Also reverted back to V1.7.9 because tokens couldn't join guild on 1.8.1

**Comment by BTCoasis** [comment]
Update - Mass Dm seems to run in some servers. In others it gives a Websocket error, due to them being kicked from the server immediately after joining. Using advanced settings i can get about 10 messages before they get kicked lol

**Comment by john1122334455** [comment]
same problem here, join the server but not able to send the dm. immediately token get banned.

**Comment by BTCoasis** [comment]
try without anti-captcha with v1.7.9 not the latest one. It's working for me now

**Comment by cryptopunks6690** [comment]
please explain what you by without anti-captcha

**Comment by xBytez5636** [comment]
Can you add me on discord? xBytez#5636

Op di 22 feb. 2022 11:48 schreef BTCoasis ***@***.***>:

**Comment by cryptopunks6690** [comment]
I sent you a request now

**Comment by pixelartnft1** [comment]
> xBytez#5636

hey sent you a request ")

**Comment by V4NSH4J** [comment]
Hey, thank you. Tokens getting kicked out is not an issue with the captcha but the server you're trying to join has some anti-bot measures which kick your tokens. (Most of them track number of accounts joining in a given time). You can try joining a brand new server as a test or use higher delays
