### ISSUE TITLE
dm issue

### ISSUE THREAD

**Issue by john1122334455** [V4NSH4J/discord-mass-DM-GO#336]
![dm problem](https://user-images.githubusercontent.com/99329787/155124031-be1be8cf-af60-4133-83d1-8b47c5ad4cb0.png)
proxy and captcha problem solved but this error while sending dm. ids are able to join and token are also good. please tell me what i have to do????
![dm problem](https://user-images.githubusercontent.com/99329787/155123914-ed155dde-ac8b-45cb-b1a9-3b4e9df79b67.png)

**Comment by xBytez5636** [comment]
You use email verified tokens to get in a phone verified server. Use full verified tokens or join a server for mail verify only. The error says it self : verification too high

**Comment by john1122334455** [comment]
thanks.. issue solved. now dm working perfectly.
