### ISSUE TITLE
Token might be locked

### ISSUE THREAD

**Issue by cristianberbecaru** [V4NSH4J/discord-mass-DM-GO#337]
Hi,

in the last days I am getting this kind of error as soon as I start the DMs. 

It locks all my tokens after I successfully join in guilds with success captcha.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/32863083/155141978-45905e69-659f-4e69-b908-166b64698ead.png">

**Comment by BigBoy2rf00** [comment]
How did you get so many tokens ? Same Here. Tokens locked

**Comment by swtnsss** [comment]
Same, tokens get locked

**Comment by pixelartnft1** [comment]
same here!

**Comment by john1122334455** [comment]
same here with me. on some small servers it is working but very few dm able to sent. and all other servers  token get  locked after sending may be 2 to 3 dm. token quality is good and already used in last version as well

**Comment by pixelartnft1** [comment]
Yes unfortuantley i have found the same

**Comment by BigBoy2rf00** [comment]
> same here with me. on some small servers it is working but very few dm able to sent. and all other servers  token get  locked after sending may be 2 to 3 dm. token quality is good and already used in last version as well

How did you get Your tokens. I need some plss

**Comment by V4NSH4J** [comment]
#351
