### ISSUE TITLE
Anti-captcha

### ISSUE THREAD

**Issue by Soliidz** [V4NSH4J/discord-mass-DM-GO#338]
Idk what happened but the anti-captcha isnt working for me, just says that is solving

**Comment by dtsrgb** [comment]
same here. Does anybody else get this?
Tried on capmonster.cloud and anti-captcha.com - both gets this during the join: "Captcha detected. Solving..." and it never ends

**Comment by V4NSH4J** [comment]
Both on latest DMDGO? 
`Moreover, when I join this token to server manually, using the same proxy, it didn't gives me captcha.`
If this happens, it's the programs fault and I'll check it out tonight

**Comment by Soliidz** [comment]
Yes im in the latest version, take a look what it says: [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key)
[12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key)
[12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key)
[12:54:44] Captcha detected, solving...
[12:54:44] Captcha detected, solving...

**Comment by onlydrip** [comment]
rucaptcha.com supported?

**Comment by dtsrgb** [comment]
> Both on latest DMDGO?

Right

**Comment by Soliidz** [comment]
yea im in the latest version

**Comment by Soliidz** [comment]
[18:20:47] Error while Solving Captcha: error creating the request for captcha [Post "https://api.anti-captcha.com/createTask": dial tcp 69.39.235.40:443: i/o timeout]

**Comment by onlydrip** [comment]
go to the settings on anti-captcha.com and look for an option to turn on `instant captcha success` or something along those lines. they make you pay a good bit more per captcha but it gets solved in far less tries without the risk of the thread timing out.

**Comment by dcl121589** [comment]
> go to the settings on anti-captcha.com and look for an option to turn on `instant captcha success` or something along those lines. they make you pay a good bit more per captcha but it gets solved in far less tries without the risk of the thread timing out.

wheres this at ? i cant find it

**Comment by V4NSH4J** [comment]
> rucaptcha.com supported?

No

**Comment by V4NSH4J** [comment]
> [18:20:47] Error while Solving Captcha: error creating the request for captcha [Post "https://api.anti-captcha.com/createTask": dial tcp 69.39.235.40:443: i/o timeout]

IP banned from Anticaptcha

**Comment by V4NSH4J** [comment]
> Yes im in the latest version, take a look what it says: [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key) [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key) [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key) [12:54:44] Captcha detected, solving... [12:54:44] Captcha detected, solving...

You haven't put a captcha key in config

**Comment by V4NSH4J** [comment]
> Both on latest DMDGO? `Moreover, when I join this token to server manually, using the same proxy, it didn't gives me captcha.` If this happens, it's the programs fault and I'll check it out tonight

This should've been fixed, please try out DMDGO v1.8.4 Re-open if problem persists.

**Comment by Krypt0nL** [comment]
> > Yes im in the latest version, take a look what it says: [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key) [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key) [12:54:43] Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key) [12:54:44] Captcha detected, solving... [12:54:44] Captcha detected, solving...
> 
> You haven't put a captcha key in config

how to get one
