### ISSUE TITLE
Joining server error 'invalid character'

### ISSUE THREAD

**Issue by obisaurus** [V4NSH4J/discord-mass-DM-GO#34]
Getting error after using joiner: 
![image](https://user-images.githubusercontent.com/97185196/148257526-0dd6a5f1-3f65-4f1c-9095-750a916c0346.png)

How do I fix this?

**Comment by V4NSH4J** [comment]
Hi, this is the beginning of the error 1015 which is a cloudflare rate limit. Try using VPN/proxy.
