### ISSUE TITLE
tokens and token generator?

### ISSUE THREAD

**Issue by john1122334455** [V4NSH4J/discord-mass-DM-GO#340]
hi i need varifed and aged token from a trusted source. can you please guide me??? everything is working fine but i need tokens. or can you please the token generator .

**Comment by xBytez5636** [comment]
Got mine working now, add me on discord xBytez#5636

**Comment by john1122334455** [comment]
please share the price for full verified tokens.

**Comment by xBytez5636** [comment]
If you need tokens add me, Mr. Pinkman#5636

**Comment by V4NSH4J** [comment]
Try joining our [telegram channel](https://t.me/tosviolators) and doing `/trusted` there to find some token sellers.
