### ISSUE TITLE
Captcha solving panic 

### ISSUE THREAD

**Issue by ganynmednet** [V4NSH4J/discord-mass-DM-GO#341]
![image](https://user-images.githubusercontent.com/51125243/155319152-2be7fa51-099f-4ef4-9c8b-3e9ab4016f2c.png)

**Comment by ganynmednet** [comment]
tried with few servers

**Comment by V4NSH4J** [comment]
Hi, this can happen if you're using `proxy_for_captcha` without enabling `proxy_from_file` 
As no proxies are loaded, it tries to extract the proxy from an empty line and panics.
The panic will be handled in the next release. Enable `proxy_from_file` and put your proxies in `input/proxies.txt`

**Comment by ganynmednet** [comment]
thank you! closed
