### ISSUE TITLE
Tokens get locked after join

### ISSUE THREAD

**Issue by GG23s** [V4NSH4J/discord-mass-DM-GO#342]
Guys tried every version and many different settings and every time i use joiner my tokens lock...
Can someone suggest me something ? 
Proxies-Proxyware
Captcha-Anti captcha

**Comment by onlydrip** [comment]
> > Guys tried every version and many different settings and every time i use joiner my tokens lock... Can someone suggest me something ? Proxies-Proxyware Captcha-Anti captcha
> 
> Hey, I will be releasing a fix to the token locks issue today/tomorrow. Join my server and stick around until I do an update: https://discord.gg/HQ8BVD83td tyty

can i bring my tokens with me to your shitty server?

**Comment by yung-guzzy** [comment]
> > > Guys tried every version and many different settings and every time i use joiner my tokens lock... Can someone suggest me something ? Proxies-Proxyware Captcha-Anti captcha
> > 
> > 
> > Hey, I will be releasing a fix to the token locks issue today/tomorrow. Join my server and stick around until I do an update: https://discord.gg/HQ8BVD83td tyty
> 
> can i bring my tokens with me to your shitty server?

bro there won't be any spots left for you soon, idgaf

**Comment by onlydrip** [comment]
> 

yeah i dont think thats how discord works buddy

**Comment by JasonRubar** [comment]
> Guys tried every version and many different settings and every time i use joiner my tokens lock... Can someone suggest me something ? Proxies-Proxyware Captcha-Anti captcha

Which format of proxies do use in proxies.txt? ip:port?

**Comment by Lukey372** [comment]
> > Guys tried every version and many different settings and every time i use joiner my tokens lock... Can someone suggest me something ? Proxies-Proxyware Captcha-Anti captcha
> 
> Which format of proxies do use in proxies.txt? ip:port?

Username:Password@IP:port

**Comment by xBytez5636** [comment]
I can help you if you want to explain, discord is Mr. Pinkman#5636

**Comment by V4NSH4J** [comment]
#351
