### ISSUE TITLE
Tokens getting Banned/Kicked after joining a server,

### ISSUE THREAD

**Issue by Edwarddak1ng** [V4NSH4J/discord-mass-DM-GO#344]
Hi, my vast majoriety of tokens are getting banned after joining a server/sending 1-2 DM's.
the TOKENS are HQ, used them before with no problems.
Used 1,81 version/ 1.7.9. proxy from proxyware, and tested anti captcha, and capmonstercloud captcha API's, still the same thing.

**Comment by glen69** [comment]
> 

Hi Mate, Where did you get HQ Token please? I'd like to get some.

**Comment by yung-guzzy** [comment]
Bro, join my server, I am releasing a tool to fix this issue very soon. https://discord.gg/6ZNvwK9G
My previous server got banned so this one is empty rn, I am willing to give u a free trial if u are interested.
everybody else who is interested may join the server as well and request a trial.

**Comment by Edwarddak1ng** [comment]
> 

hi, dm me

**Comment by Lukey372** [comment]
> Bro, join my server, I am releasing a tool to fix this issue very soon. https://discord.gg/7EuN4mSUgz My previous server got banned so this one is empty rn, I am willing to give u a free trial if u are interested. everybody else who is interested may join the server as well and request a trial.

Boo you suck.

**Comment by yung-guzzy** [comment]
> > Bro, join my server, I am releasing a tool to fix this issue very soon. https://discord.gg/7EuN4mSUgz My previous server got banned so this one is empty rn, I am willing to give u a free trial if u are interested. everybody else who is interested may join the server as well and request a trial.
> 
> Boo you suck.

Are u an idiot? People are having issues and dm-go dev hasn't fixed it yet. Whats wrong with me offering a solution? DOn't like it dont use

**Comment by Lukey372** [comment]
> > > Bro, join my server, I am releasing a tool to fix this issue very soon. https://discord.gg/7EuN4mSUgz My previous server got banned so this one is empty rn, I am willing to give u a free trial if u are interested. everybody else who is interested may join the server as well and request a trial.
> > 
> > 
> > Boo you suck.
> 
> Are u an idiot? People are having issues and dm-go dev hasn't fixed it yet. Whats wrong with me offering a solution? DOn't like it dont use

I highly doubt you can resolve the issue, seeing as most of the bots on the market are broken as of current. So the real question is are you an idiot that is trying to scam people?

**Comment by yung-guzzy** [comment]
> > > > Bro, join my server, I am releasing a tool to fix this issue very soon. https://discord.gg/7EuN4mSUgz My previous server got banned so this one is empty rn, I am willing to give u a free trial if u are interested. everybody else who is interested may join the server as well and request a trial.
> > > 
> > > 
> > > Boo you suck.
> > 
> > 
> > Are u an idiot? People are having issues and dm-go dev hasn't fixed it yet. Whats wrong with me offering a solution? DOn't like it dont use
> 
> I highly doubt you can resolve the issue, seeing as most of the bots on the market are broken as of current. So the real question is are you an idiot that is trying to scam people? Show me proof of your bot working otherwise gtfo.

Are you retarded? I am not sure if you can read, but my message clearly says: you can join my server and try out the trial of the tool.

**Comment by V4NSH4J** [comment]
Guys, I can't do much about it except adding more solver APIs. The captcha solved isn't the highest score combined with LQ tokens gets them flagged or locked. So use latest DMDGO and HQ tokens. To increase the score, you can try using proxy_for_captcha
