### ISSUE TITLE
Error solving captcha

### ISSUE THREAD

**Issue by Sneakers97** [V4NSH4J/discord-mass-DM-GO#345]
Hello,

I am getting the error "Error while Solving Captcha: error unmarshalling the response body [json: cannot unmarshal string into Go struct field Resp.solution of type utilities.Sol]"

What does this mean and how do I fix it?

**Comment by xBytez5636** [comment]
Works for me bro

**Comment by V4NSH4J** [comment]
Captcha service is sending you some unexpected data, can you ensure everything you've set is valid and you're not IP banned from the service?

**Comment by Sneakers97** [comment]
I'm using anti-captcha, I dont think I'm IP banned from the service because it worked for one time and solved the captcha then didnt work for the rest of the day. I was using IProyal for my DMing proxy and anti-captcha. I tried switching to proxiscrape and had the same result. I also made sure that my proxies were entered in the correct format.

**Comment by V4NSH4J** [comment]
You should try printing out the response and asking the captcha service support why you got that response.
