### ISSUE TITLE
why this? i am using captcha service as well proxies

### ISSUE THREAD

**Issue by john1122334455** [V4NSH4J/discord-mass-DM-GO#346]
i am using captcha service as well proxies. and all that was working perfect in last version except dm. but now i am  not able to solve the captcha. please need help to get it on track. from last 2 weeks,
![error](https://user-images.githubusercontent.com/99329787/155714064-9a89eb1f-9470-4eba-a57f-bd644d1db1d4.png)
I am not able to send dm through ( discord-mass-DM-GO)

**Comment by VladM0** [comment]
Have the same problem.. I changed captcha from anti-captcha to 2Captcha but tokens get banned when DM

**Comment by ChronoBrake** [comment]
Something changed in last discord update. I using other tool than DMGO and i get also captcha loop.

**Comment by swtnsss** [comment]
it eventually solves the captcha, it did for me at least

**Comment by xBytez5636** [comment]
For me its working, if you need help add me Mr. Pinkman#5636

**Comment by Sneakers97** [comment]
I get 0’s, 1’s, and 2’s

**Comment by Sneakers97** [comment]
[a9b5fb07-92ff-493f-86fe-352a2803b3df]

**Comment by V4NSH4J** [comment]
> Ah, makes sense. I tried solving it by hand and it was also making me solve the captcha over and over again. Is there a way to avoid this or do I just need higher quality tokens?

Unfortunately I think you'd need different tokens.
Check my reply on #350 
It looks like a discord bug

**Comment by V4NSH4J** [comment]
I was able to bypass this somehow, I'll find more such tokens and try to replicate what I did

**Comment by Sneakers97** [comment]
Ok I’ll check that out, thanks!

**Comment by V4NSH4J** [comment]
Okay guys, I've just pushed through DMDGO V1.8.4 which will break the infinite loop. Also tried to prevent the captcha key in the first place.

**Comment by Sneakers97** [comment]
Thanks for your hard work
