### ISSUE TITLE
Question about tokens

### ISSUE THREAD

**Issue by swtnsss** [V4NSH4J/discord-mass-DM-GO#347]
Is it likely that the people with lower quality tokens will be able to use them again with future updates? I went from about 30 dms to 4, or should I begin my search for super high quality tokens?

**Comment by SiaAlawieh** [comment]
> You need higher quality, got mine from pinkmansbulk at sellix.io , for me it does 40-60 dms per token🤷🏽‍♂️

how much does a token cost?

**Comment by xBytez5636** [comment]
> > You need higher quality, got mine from pinkmansbulk at sellix.io , for me it does 40-60 dms per token🤷🏽‍♂️
> 
> how much does a token cost?

Mostly around $0.3 , got mine from pinkmansbulk.sellix.io
Maybe they also work for you? You could check.

**Comment by linus93** [comment]
> > > You need higher quality, got mine from pinkmansbulk at sellix.io , for me it does 40-60 dms per token🤷🏽‍♂️
> > 
> > 
> > how much does a token cost?
> 
> Mostly around $0.3 , got mine from pinkmansbulk.sellix.io Maybe they also work for you? You could check.
<img width="930" alt="Screenshot 2022-02-27 at 2 58 57 AM" src="https://user-images.githubusercontent.com/96366660/155855767-a7c71d0f-7205-4004-bdd5-491b3607795c.png">
Isn't this yourself? Or did you buy your own tokens?

**Comment by xBytez5636** [comment]
Yeah using my own, they work for me, so why not

**Comment by V4NSH4J** [comment]
You should find higher quality tokens and proxies.

**Comment by SiaAlawieh** [comment]
> > > You need higher quality, got mine from (self advertisement) at sellix.io , for me it does 40-60 dms per token🤷🏽‍♂️
> > 
> > 
> > how much does a token cost?
> 
> Mostly around $0.3 , got mine from (self advertisement) Maybe they also work for you? You could check.

There are 99 items left, but minimum quantity for purchase is 100
