### ISSUE TITLE
How to put proxies in code? 

### ISSUE THREAD

**Issue by hamoudaz99** [V4NSH4J/discord-mass-DM-GO#35]

**Comment by V4NSH4J** [comment]
In your config file you can put 1 http(s) rotating proxy as a string in front of the key "proxy"

**Comment by notihamdutch** [comment]
Please where can I buy Http(s) proxies that’ll work with this? Thanks

**Comment by V4NSH4J** [comment]
> Please where can I buy Http(s) rotating proxies that’ll work with this? Thanks

Iproyal packetstream or any other
