### ISSUE TITLE
Stopping instance

### ISSUE THREAD

**Issue by VladM0** [V4NSH4J/discord-mass-DM-GO#351]
I use new version 1.8.3, I use residential sticky ip, anti-captcha/2captcha (I tried both of them) but when my tokens give the seccond dm, they all die "Stopping instance and adding members to failed list. 403". So I manage to send only one dm per token

**Comment by V4NSH4J** [comment]
Hi, Discord recently introduced hcaptcha before joining servers again. Problem is, when this captcha is solved by captcha solving APIs, it gives a high bot score. Which essentially means that discord can flag your account if you don't have HQ tokens. I'd recommend using HQ tokens and proxies to avoid this. This is how invite joining seems to be from now onwards. Realistically from my point of view, I can only add more captcha APIs and methods so I can't really help if captcha is giving a high bot score.
