### ISSUE TITLE
captcha solver doesn't work

### ISSUE THREAD

**Issue by JasonRubar** [V4NSH4J/discord-mass-DM-GO#354]
![image](https://user-images.githubusercontent.com/100188570/155850500-457a4c6e-d412-4dd5-ae7d-7f63f7fdb6fa.png)
I use anti-captcha_com. api key was added. I've checked my profile on anti-captcha, they counted uploaded captchas

**Comment by linus93** [comment]
Yeah happening to myself too, I tried both anti-captcha  and capmonster but doesn't seem like it is working for any.

<img width="408" alt="Screenshot 2022-02-27 at 12 37 25 AM" src="https://user-images.githubusercontent.com/96366660/155851295-1da31081-bea9-490f-b29b-2e3076b5f35d.png">
.

**Comment by V4NSH4J** [comment]
Please try DMDGO V1.8.4. Error 25 by OP is a proxy problem, Anti-captcha does not support your proxy. Re-open if problem persists.
