### ISSUE TITLE
Feature Request: Monitor "welcome" channel, DM new joiners

### ISSUE THREAD

**Issue by posercorpse** [V4NSH4J/discord-mass-DM-GO#358]
As per title; ability to monitor a "welcome" channel ID and DM new members as they join, using the message.json file.

If there's already a way to accomplish via conjunction with another method, advice would also be greatly appreciated

**Comment by Hypnoticss1html** [comment]
I've got this tool. It sends automatically dm to everyone who joins a server. DC: Skambinam didžėjui#7319

**Comment by posercorpse** [comment]
> I've got this tool. It sends automatically dm to everyone who joins a server. DC: Skambinam didžėjui#7319

That's nice honey.

**Comment by V4NSH4J** [comment]
It's the most popular thing in demand right now but as it's only used for scams I'm unsure if I will be adding it.
