### ISSUE TITLE
Errors while getting user info

### ISSUE THREAD

**Issue by tommy12f** [V4NSH4J/discord-mass-DM-GO#36]
Thanks for the bot, but is is throwing many errors for me:

**Error while getting user info: brotli: PADDING_2**
and
**Error while getting user info: invalid character 'e' looking for beginning of value**

are the most common. These two errors are spammed over and over, what might cause those? Is it possible that my connection/proxy is too weak to handle the amount of requests?

**Comment by V4NSH4J** [comment]
Hi! Please disable check_mutual in config, it currently doesn't function well! 
It is some sort of rate limit, the e error is cloudflare error 1015 which is a cloudflare rate limit and the brotli error was fixed in the source code.
