### ISSUE TITLE
scrape_usernames - scrape_avatar | How it works?

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#360]
![Screenshot_1](https://user-images.githubusercontent.com/56173496/155897243-591e7cdf-049e-44dd-9f36-de6ca8c8c9c8.png)

I was just checking config and found these. How can i use this features?

**Comment by V4NSH4J** [comment]
Hi, once enabled in config, you can run the op8 scraper (offline scraper) normally and it would output names to names.txt and profile pictures to PFPs folder
