### ISSUE TITLE
Cookie error

### ISSUE THREAD

**Issue by xBytez5636** [V4NSH4J/discord-mass-DM-GO#361]
![image](https://user-images.githubusercontent.com/100011125/155912885-00cd9fc0-ad86-4ad5-ac7e-5f768e3a1e50.png)

**Comment by V4NSH4J** [comment]
Error 502 is Bad Gateway error, usually it is a server error. But in this case, it could also mean your proxy received an invalid response from Discord. Which might not be the case, and probably is just your proxy acting up.
