### ISSUE TITLE
Locks tokens

### ISSUE THREAD

**Issue by vrullinger** [V4NSH4J/discord-mass-DM-GO#367]
The joiner and pfp/name changer are patched on this tool. It locks tokens even on name change even if you dont join.

**Comment by V4NSH4J** [comment]
Hey, please only open an issue if you have an actual problem. If you just want to complain without knowing anything about how stuff works on Discord, keep it to yourself, no one wants to hear it. 
The name/pfp changer is NOT patched. The invite joiner isn't patched either. Discord just flags the account on solving captcha if the account or captcha is low quality. You could try: 
1) Using proxy_for_captcha
2) Using a different captcha service
3) Using better tokens.
