### ISSUE TITLE
Anti-Virus problem

### ISSUE THREAD

**Issue by swtnsss** [V4NSH4J/discord-mass-DM-GO#369]
Disabling the anti-virus allowed me to run the program multiple times yesterday, today I tried the same method and the program started to instantly close again. I use VPN and proxies. Any suggestions?

**Comment by swtnsss** [comment]
I think my mistake was setting proxy for captcha to true, would this make sense?

**Comment by V4NSH4J** [comment]
I see, you can run it on a VM with antivirus disabled or add DMDGO as an exception on your machine.
