### ISSUE TITLE
working performance difference

### ISSUE THREAD

**Issue by casestudy25** [V4NSH4J/discord-mass-DM-GO#37]
First of all, thank you for the bot!

When I build with 'go build', its' performance is remarkably slower than your ready-made .exe version.
And also it makes my tokens dead very easily.
I also checked config.json and etc. but could not find any clue.
Is there any special difference between your .exe version and source version(which I have to run 'go build')?

**Comment by V4NSH4J** [comment]
Hey, there isn't any difference in the releases I provided and the source code. The source code is just a little more updated as I was a bit lazy to make new releases for small changes. How many DMs would your tokens normally get and how many when you build it on your own? I'm really interested to know because a lot of people ask me this.

**Comment by casestudy25** [comment]
Hey, thx for the answer.

It is very default version of your source code, 1.0.6 version, which I built with 'go build' method.
Actually I had tried to customize your source code and the performance was not good.
So I retried with your default code again, but the result(performance) was also same(super slow and token dies easily).
Of course I checeked config.json options 😢

On my last test, I simply tried with only 10 tokens, targeted about 200 ids, and all the tokens died before their first sleep.

**Comment by V4NSH4J** [comment]
Could you send me your go environment

**Comment by V4NSH4J** [comment]
Hi, could you try the new version? Does it still exist?

**Comment by casestudy25** [comment]
Hey, thx for the answers.
I just read them. I'll try again and let you know the result.

**Comment by V4NSH4J** [comment]
Any update?
