### ISSUE TITLE
captcha stuck trying to solve.

### ISSUE THREAD

**Issue by kushfax** [V4NSH4J/discord-mass-DM-GO#370]
ive upped my bid and tried 3 different captcha services, exceeds the number of tries. i use proxy from file true and proxy for captcha true. not sure what the problem is.

**Comment by pixelartnft1** [comment]
Hi I had the same issue, the resolution for me was to find another token provider as if they are not verified for a long period of time, they become stuck in an endless H2 captcha loop

**Comment by V4NSH4J** [comment]
Hey, that's unfortunate, there's a new kind of hcaptcha that cannot be solved even manually. Discord shows that to flagged accounts. Make sure you're on latest DMDGO and try finding better tokens.
