### ISSUE TITLE
tokens get locked after 1 dm 

### ISSUE THREAD

**Issue by ThisIsMohsen** [V4NSH4J/discord-mass-DM-GO#373]
hi,
i create one account with hotmail service and phone verify (smspva).
but get locked after 1 dm to user that hasn't messaged before. ( it works when i manually sent message in discord app before single dm spam).

i created a python script that interact with dmdgo exe and send argu to it.(for single dm spam)

**Comment by cristianberbecaru** [comment]
same here, any fix?

**Comment by jaydeebow** [comment]
> .(for single dm spam)

Buy tokens from ish in their telegram. He's a trusted seller. If you use /trusted in their telegram it'll tell you the trusted sellers.

**Comment by V4NSH4J** [comment]
#372
