### ISSUE TITLE
1.8.4 Error while Solving Captcha: unknown error [25]

### ISSUE THREAD

**Issue by ganynmednet** [V4NSH4J/discord-mass-DM-GO#374]
![image](https://user-images.githubusercontent.com/51125243/156423421-eb5f994c-729e-4d5f-b641-0bf1a27af8f0.png)
![image](https://user-images.githubusercontent.com/51125243/156423525-2219a3cc-436f-4f6f-8b14-f34430e1c3e2.png)

**Comment by medzbelo** [comment]
![7c56aaaf-98c0-4942-8e7e-e3cef14677d9](https://user-images.githubusercontent.com/100725833/156427470-91e968b3-4f5d-4980-b2fb-dbdf4953df08.jpg)
 
I dont know if its a similar issue or not, but i'm having this issue too, how do you recommend me fixing it?

**Comment by V4NSH4J** [comment]
Error 25 is when AntiCaptcha doesn't like your proxy. There's a proxy checker on their website you can use or contact their support.
