### ISSUE TITLE
 trying to build 1.8.5

### ISSUE THREAD

**Issue by kushfax** [V4NSH4J/discord-mass-DM-GO#375]
my captcha has been stuck in a loop. im trying to figure out where to build 1.8.5 file can someone show me what i need to do please.

**Comment by pscpc** [comment]
i need this too.

**Comment by pscpc** [comment]
at least can you tell me when will you release 1.8.5. pleeease release

**Comment by pixelartnft1** [comment]
Captcha loop I had the same issue, reaosn is due to the new hCaptcha introduced, best way around this is to use higher quality tokens, any tokens you have running in a loop, manually login and complete the captcah and invite for each, takes a bit of time but reduces the wastage of tokens

**Comment by pscpc** [comment]
actually right now i need captcha APIs support. you said you relase the 1.8.5 code which that supports more captcha services. so i can't compile GO, thats why i need 1.8.5. we know you can't pass hcaptchas with codes, we need proxies for pass

**Comment by V4NSH4J** [comment]
Compiling is explained in the readme file.
