### ISSUE TITLE
Captcha detected but not solved

### ISSUE THREAD

**Issue by Shmalle** [V4NSH4J/discord-mass-DM-GO#376]
Its not solving captchas but is throwing an error. Got a capmnoster.cloud api-key n stuff but it just runs thru the attempts after a few minutes and then goes on
![discord-mass-dm-GO_sIxLk0f9dx](https://user-images.githubusercontent.com/72462771/156470054-80ca83cb-24e2-4e0f-ab8d-e9f04035f04d.png)
EDIT: On capmonster, it says it solved the hcaptcha successfully but the program doesnt respond with a join.

**Comment by pscpc** [comment]
you are trying same tokens, increase the max join retries in config

**Comment by dmulrooney** [comment]
Captcha detected error is still happening with different tokens. Anti-captcha is down, so I can't test that.

**Comment by V4NSH4J** [comment]
Some tokens just can't join servers anymore. Also ensure you're on latest DMDGO
