### ISSUE TITLE
unkown message when joining servers

### ISSUE THREAD

**Issue by dcl121589** [V4NSH4J/discord-mass-DM-GO#377]
i get this error with proxy for captcha and proxy from file true, and i also get this without proxy for captcha and proxy from file, shortly after a bunch of random white lettering spams the software. can not get past this, what is this?

![server joiner](https://user-images.githubusercontent.com/99930909/156487369-eff53fd4-2c93-4c23-a162-df3114b589da.png)

**Comment by zxcspectator** [comment]
yeah same captcha loop

**Comment by Shmalle** [comment]
From capmonster, I get that it could not do createTask

**Comment by cristianberbecaru** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/32863083/156759428-914ba0cd-fef1-44e0-bae8-febeafe81b55.png">
I get this

**Comment by V4NSH4J** [comment]
Error 25 is when the service doesn't like your proxy. It's a question for them rather for me. 

#370 #363 for captcha loop
