### ISSUE TITLE
Need help with joining server with JavaScript code.

### ISSUE THREAD

**Issue by muhitrhn** [V4NSH4J/discord-mass-DM-GO#378]
I’m trying to create a auto shilling script which will also join the servers. But i’m stuck at joining task. I got the captcha solved key from CapMonster Cloud but i’m not sure what should I do with it. Here's my code so far - 
```
const request = require("request");
const { HCaptchaTask } = require("node-capmonster")

const UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0";
const XTrack = "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRmlyZWZveCIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJlbi1VUyIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2Ojk3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvOTcuMCIsImJyb3dzZXJfdmVyc2lvbiI6Ijk3LjAiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6IiIsInJlZmVycmluZ19kb21haW4iOiIiLCJyZWZlcnJlcl9jdXJyZW50IjoiIiwicmVmZXJyaW5nX2RvbWFpbl9jdXJyZW50IjoiIiwicmVsZWFzZV9jaGFubmVsIjoic3RhYmxlIiwiY2xpZW50X2J1aWxkX251bWJlciI6OTk5OSwiY2xpZW50X2V2ZW50X3NvdXJjZSI6bnVsbH0=";
const XSuper = "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRmlyZWZveCIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJlbi1VUyIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2OjgzLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvODMuMCIsImJyb3dzZXJfdmVyc2lvbiI6IjgzLjAiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6IiIsInJlZmVycmluZ19kb21haW4iOiIiLCJyZWZlcnJlcl9jdXJyZW50IjoiIiwicmVmZXJyaW5nX2RvbWFpbl9jdXJyZW50IjoiIiwicmVsZWFzZV9jaGFubmVsIjoic3RhYmxlIiwiY2xpZW50X2J1aWxkX251bWJlciI6MTE2MzExLCJjbGllbnRfZXZlbnRfc291cmNlIjpudWxsfQ==";
const XContext = "eyJsb2NhdGlvbiI6IkpvaW4gR3VpbGQiLCJsb2NhdGlvbl9ndWlsZF9pZCI6IjkyNTA2NjE3MjM0MzM5ODQyMCIsImxvY2F0aW9uX2NoYW5uZWxfaWQiOiI5MjUwNjYxNzIzNDMzOTg0MjMiLCJsb2NhdGlvbl9jaGFubmVsX3R5cGUiOjB9";
const capmonster = new HCaptchaTask("api-key")

capmonster.createTask("https://discord.com/channels/@me", "4c672d35-0701-42b2-88c3-78380b0db560")
    .then((taskId) => {
        return capmonster.joinTaskResult(taskId)
            .then((response) => {
                join("THE_TOKEN", "PBrZsjQ3", response)
            })
    });

function join (token, invite, captcha_key) {
    const cookies = getCookies(function (err, res) {
        if (!err) return res + "; locale:en-US";
    })

    const fingerprint = getFingerprint(cookies);

    request.post(`https://discord.com/api/v9/invites/${invite}`, {
        headers: {
            "Authorization": token,
            "Cookie": cookies,
            "Connection": "keep-alive",
            "sec-ch-ua": 'Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92',
            "Accept": "*/*",
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "User-Agent": UserAgent,
            "Origin": "https://discord.com",
            "Sec-Fetch-Site": "same-site",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Dest": "empty",
            "Referer": "https://discord.com/channels/@me",
            "Accept-Language": "en-US,en;q=0.9",
            "X-Super-Properties": XSuper,
            "X-Fingerprint": fingerprint,
            "X-Context-Properties": XContext
        },
        body: {
            "captcha_key": captcha_key,
            "captcha_sitekey": "4c672d35-0701-42b2-88c3-78380b0db560",
            "captcha_service": "hcaptcha"
        }
    }, (error, response) => {
        if (error) {
            return console.log(error);
        }

        console.log(body, response.statusMessage);
    })
}

function getCookies (callback) {
    request('https://discord.com', function(error, response, body) {
        if (!error && response.statusCode == 200) {
            return callback(null, response.headers['set-cookie']);
        } else return callback(error);
    })
}

function getFingerprint (cookies) {
    request('https://discord.com/api/v9/experiments', function(error, response, body) {
        if (!error && response.statusCode == 200) {
            const fingerprint = JSON.parse(body)["fingerprint"];
            return fingerprint;
        } else return console.log(error);
    })
}```

**Comment by V4NSH4J** [comment]
Hey, thank you for the issue. 
You can first request the endpoint with an empty payload of `{}` like it happens on the client. 
Chances are, you might not need a captcha, in this case your request would go through and you'll join the server.
If it requires a captcha, you'll get HTTP Response code 400 and in the body you'll find the sitekey (there are 3 different ones so you can't make them constant) 
The payload you're sending looks like the response from that request, you don't need to send that. You can send this sitekey to capmonster.cloud and get the solution. 
Once you have the solution, you can repeat the original request with payload `"captcha_key": "solution_from_capmonster" `
And you should hopefully join the server, if they don't accept your captcha, they'll give you status code 400 again. 
Let me know if you want to know anything else.

**Comment by muhitrhn** [comment]
Thank you very much! I had one question, is CapMonster cloud working properly or should I change to another solver?

**Comment by muhitrhn** [comment]
I have tired what you asked. This should be it after getting the first response right?
```
if (response.statusCode == 400 && JSON.parse(body)["captcha_sitekey"]) {
    request.post(`https://discord.com/api/v9/invites/${invite}`, {
        headers: {
            "Authorization": token,
            "Cookie": cookies,
            "Connection": "keep-alive",
            "sec-ch-ua": 'Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92',
            "Accept": "*/*",
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "User-Agent": UserAgent,
            "Origin": "https://discord.com",
            "Sec-Fetch-Site": "same-site",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Dest": "empty",
            "Referer": "https://discord.com/channels/@me",
            "Accept-Language": "en-US,en;q=0.9",
            "X-Super-Properties": XSuper,
            "X-Fingerprint": fingerprint,
            "X-Context-Properties": XContext
        },
        body: {
            "captcha_key": captcha_key
        }
    }, (err, res, bo) => {
        if (err) {
            return console.log(err);
        }

        console.log(bo, res.statusCode);
    })
}```

**Comment by V4NSH4J** [comment]
> Thank you very much! I had one question, is CapMonster cloud working properly or should I change to another solver?

I'm not sure which services work the best, but Capmonster uses AI to solve captchas. I think something like 2captcha should be a better option. And you should use proxies with it so that the captcha is solved on the same IP as the server join. 



> > Once you have the solution, you can repeat the original request with payload "captcha_key": "solution_from_capmonster"
> 
> Do you mean I will have to send a new request then with only the captcha_key in payload?

No no, get the captcha_sitekey from the first response and send it to capmonster or any service of your choice, then send it again in your payload as the value to the "captcha_key" key

**Comment by muhitrhn** [comment]
> No no, get the captcha_sitekey from the first response and send it to capmonster or any service of your choice, then send the solution from them in your payload as the value to the "captcha_key" key

I have tired what you asked. This should be it after getting the first response right?
```
if (response.statusCode == 400 && JSON.parse(body)["captcha_sitekey"]) {
    request.post(`https://discord.com/api/v9/invites/${invite}`, {
        headers: {
            "Authorization": token,
            "Cookie": cookies,
            "Connection": "keep-alive",
            "sec-ch-ua": 'Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92',
            "Accept": "*/*",
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "User-Agent": UserAgent,
            "Origin": "https://discord.com",
            "Sec-Fetch-Site": "same-site",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Dest": "empty",
            "Referer": "https://discord.com/channels/@me",
            "Accept-Language": "en-US,en;q=0.9",
            "X-Super-Properties": XSuper,
            "X-Fingerprint": fingerprint,
            "X-Context-Properties": XContext
        },
        body: {
            "captcha_key": captcha_key
        }
    }, (err, res, bo) => {
        if (err) {
            return console.log(err);
        }

        console.log(bo, res.statusCode);
    })
}```

**Comment by V4NSH4J** [comment]
> > No no, get the captcha_sitekey from the first response and send it to capmonster or any service of your choice, then send the solution from them in your payload as the value to the "captcha_key" key
> 
> I have tired what you asked. This should be it after getting the first response right?
> 
> ```
> if (response.statusCode == 400 && JSON.parse(body)["captcha_sitekey"]) {
>     request.post(`https://discord.com/api/v9/invites/${invite}`, {
>         headers: {
>             "Authorization": token,
>             "Cookie": cookies,
>             "Connection": "keep-alive",
>             "sec-ch-ua": 'Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92',
>             "Accept": "*/*",
>             "sec-ch-ua-mobile": "?0",
>             "sec-ch-ua-platform": "Windows",
>             "User-Agent": UserAgent,
>             "Origin": "https://discord.com",
>             "Sec-Fetch-Site": "same-site",
>             "Sec-Fetch-Mode": "cors",
>             "Sec-Fetch-Dest": "empty",
>             "Referer": "https://discord.com/channels/@me",
>             "Accept-Language": "en-US,en;q=0.9",
>             "X-Super-Properties": XSuper,
>             "X-Fingerprint": fingerprint,
>             "X-Context-Properties": XContext
>         },
>         body: {
>             "captcha_key": captcha_key
>         }
>     }, (err, res, bo) => {
>         if (err) {
>             return console.log(err);
>         }
> 
>         console.log(bo, res.statusCode);
>     })
> }```
> ```

Yes, just that in the payload you have to send the solution as a string which you get from the solver APIs. You can check DMDGO's code on it too, it has a functioning inviter.

**Comment by muhitrhn** [comment]
I tried, but go lang confuses me :smile:

**Comment by BigBoy2rf00** [comment]
I'm trying to learn go but Interfaces especially Reader writer is killing my brain

**Comment by muhitrhn** [comment]
> I'm trying to learn go but Interfaces especially Reader writer is killing my brain

Same here. 😃
