### ISSUE TITLE
CAPCHA_NOT_READY

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#379]
after 1 hour i build the source code. then i tried 2captcha as captcha solver. in javascript some coder fixed it like this: https://gitlab.com/nullworks/accgen/accgen-web/-/commit/fe750d3977abf24a69b6216607564bd57f24877d

btw the problem: (same results with proper delay)
![image](https://user-images.githubusercontent.com/56173496/156673447-9b2a6f67-2cf8-467e-b06c-c7d738c46d48.png)

**Comment by V4NSH4J** [comment]
I was using 2Captcha's official code for golang. Please ask their support why they didn't return captchas if that's the problem you're facing.
