### ISSUE TITLE
[Question to the community] Improvement to memberids.txt and completed.txt

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#383]
@V4NSH4J you're awesome, thanks for your hard work and unbelievable skills.

Currently, if a user from memberids.txt have closed DM (User has DMs closed or not present in server {"message": "Cannot send messages to this user", "code": 50007}) he's still staying in memberids.txt instead of going to the completed.txt

How do you guys think will be better?

**Comment by V4NSH4J** [comment]
Hey, if a DM fails, the user is sent to `failed.txt`. and members from `memberids.txt` are only removed once the DMs complete on their own (program isn't forcefully closed before hand) 
Naturally even when IDs are removed from memberids.txt, only the completed ones are which will leave behind the failed IDs
A closed DM is considered as a failed DM.
