### ISSUE TITLE
scrape_usernames, scrape_avatars

### ISSUE THREAD

**Issue by qizq1337** [V4NSH4J/discord-mass-DM-GO#387]
both are set to true but wont scrape when scraping member id's :/

**Comment by posercorpse** [comment]
> both are set to true but wont scrape when scraping member id's :/

You're know scraping only works with the offline scraper, right?

**Comment by V4NSH4J** [comment]
^ When enabled the op8 or offline scraper would scrape names and PFPs and write them to names.txt and PFPs folder

**Comment by leon-si** [comment]
@V4NSH4J how do I scrape for member usernames on top of member ID?
