### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by petounadim** [V4NSH4J/discord-mass-DM-GO#389]
Hi! First, thanks for the work which is awesome.
I'm writing this for a suggestion: what about generating a txt file with tokens that did not join the server (in addition with the txt file that sort only the tokens that joined in). It would be usefull as we could re-join the tokens that failed to enter the server.

Thanks a lot and really appreciate your work.

**Comment by V4NSH4J** [comment]
Thank you for your kind words. Sounds like a good idea.

**Comment by BigBoy2rf00** [comment]
Yo whats your discord. I want to ask you something in private ?

**Comment by V4NSH4J** [comment]
V11NSH4J#0452

**Comment by BigBoy2rf00** [comment]
Added
