### ISSUE TITLE
New error?  error while getting fingerprint error while unmarshalling response

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#391]
![image](https://user-images.githubusercontent.com/89306625/157039286-16931406-d45b-4e19-b020-7ff7cd10b43e.png)

Error while opening DM channel: error while getting fingerprint error while unmarshalling response from fingerprint request invalid character '<' looking for beginning of value [822]
Error while unmarshalling body from fingerprint request invalid character '<' looking for beginning of value

**Comment by V4NSH4J** [comment]
Discord is sending you HTML. I think you're being rate limited. Use proxies.
