### ISSUE TITLE
New capmonster issue - 

### ISSUE THREAD

**Issue by pixelartnft1** [V4NSH4J/discord-mass-DM-GO#392]
Anyone have a solution for this - never received before until today. Tried different proxies etc still occuring.
![image](https://user-images.githubusercontent.com/100177238/157089468-b71e5496-4b6f-4aa6-aa12-b45623d18a63.png)

**Comment by V4NSH4J** [comment]
You seem to be IP banned from capmonster.cloud 
Try using a VPN.

**Comment by pscpc** [comment]
btw aren't your tokens get locked after solving captcha? @pixelartnft1. Whenever i pass(solve) the tokens they become invalid

**Comment by pixelartnft1** [comment]
> btw aren't your tokens get locked after solving captcha? @pixelartnft1. Whenever i pass(solve) the tokens they become invalid

yep

**Comment by pscpc** [comment]
so why are you trying to solve captchas

**Comment by pixelartnft1** [comment]
because thats how you join servers 
im just finding mine this evening is just being blocked in all angles

**Comment by V4NSH4J** [comment]
#488
