### ISSUE TITLE
failed to join guild

### ISSUE THREAD

**Issue by Felix735735** [V4NSH4J/discord-mass-DM-GO#393]
Says failed to join guild. 401 unauthorized code 0
even though its not locked and everything is correct
also what is your discord server invite cus it's expired

**Comment by V4NSH4J** [comment]
We don't have a discord server at the moment. Only a telegram server https://t.me/tosviolators

401 could mean that your token is disabled/locked or the format is wrong. You could be using email:pass:token instead of token.
