### ISSUE TITLE
Started receiving unmarshalling fingerprint body error

### ISSUE THREAD

**Issue by ganynmednet** [V4NSH4J/discord-mass-DM-GO#394]
![image](https://user-images.githubusercontent.com/51125243/157304779-889abb0e-160b-410c-9360-0eab4c1c1a73.png)

Tokens are ok, proxies are ok

**Comment by V4NSH4J** [comment]
Discord is down at the moment

**Comment by V4NSH4J** [comment]
Should be fine now.
