### ISSUE TITLE
rqtoken - hcaptcha udpate - captcha solving does not work most of the time on any platform

### ISSUE THREAD

**Issue by dmulrooney** [V4NSH4J/discord-mass-DM-GO#395]
This will join your tokens from tokens.txt to a server

[01:00:35] Captcha detected OTQ0MDgzMTkzODAyNDEyMTAy.Yg8eQQ.H.........FI [4c672d35-0701-42b2-88c3-78380b0db560] [0]
2022/03/09 01:00:35 Status 200 OK data OK|69755785138
2022/03/09 01:00:58 Status 200 OK data CAPCHA_NOT_READY
2022/03/09 01:01:21 Status 200 OK data OK|P0_eyJ0eXAiOiJ.........YvgORxl73lzDHWLA-48AwWjjgM7DtrXNA
[01:01:21] Error while joining: max retries exceeded
[01:01:22] All threads finished

This issue persists on anti-captcha, capmonster, 2captcha, and others platforms tested. Can someone identify the issue so I can submit a fix proposal? I assume the joining headers/data/code has changed on Discord. I'd like to help fix this, but I just started using the joiner today. I have made mods in the mass advertiser code so I am familiar with the codebase a bit.

The issue is due to a new post data item called "rqtoken" and I would like to work with the community to solve this together. Botting as we know it could be coming to an end because of this. Hcaptcha and Discord are working together to create a "Guild Captcha Type". We need a way to farm these.

**Comment by dmulrooney** [comment]
This might have to do with the new "rqtoken" in the join server post. It gives error "Update your app" if you use the old 4c key... but it's not working anymore for me using old app code.

**Comment by dmulrooney** [comment]
Here are examples of the "rqtoken" data, not quite sure where it is coming from. It is not in plain text in the **website, clearly in javascript, request, or response network data**. I believe it is _encoded in base64, encrypted, or manipulated data in JS.._

Im02UFBqSXpYUDlNZ0s3WlAvSjBLbDQ3VkhhUzliMElnNiswRXRNYmlwMnJ3L2tOV2ZaK1lzWjEzMUIvaHc1ZDFvRlVrR1E9PW9QYytXNjhCazBpcmJXMjIi.YihwFA.js0BkbN6aCj_RdDT8aXdR8foJfc
Ijl4Q1NYUEtLN1FlaEtMZzM0MHJrbmFaL05ybVVEZ1ZRRUJKbTdFbytWMjlvSFZHa0I5QzlQbG1VMG5FOHVTU2NPVzNSaHc9PVpEc2NOT1RCeEo3SFFvc2gi.YihxQQ.nVOGEI3re0dzb2_QxtJOgJvk9_k
Ik00azV4YUk2SGFuTlVzUEZmQyt1Vkk1R0VUSFdMZlRTR0s3WlRLUDVma29NZmpXYnFMM0xyVTNOeWFDcGZVeElGcGg4Unc9PVNVSWJKVXhvVjF6RW9aMDMi
InJLNTljNklxR1ZNbk81Y3VDWVZ3SEFVV0Q2L1U4WTl3UnRmK1k4MjNpNnpnOS9CZmFnNlNpL24ybUJObzNPZlhQaWN5WXc9PTV4TDc4QnA3Zjg3cHpVMUki.Yih2Fw.056Zk5wwsw1xaklCcFoaNEmcyUY
ImgvditJMXVDZGJpWFhjZ3E2UUZYU0FHUE5qaGNLUlNWdXJ1M1BEYVdtdldFdW1lN3RoOG1vaUJIakluaDlLVThrR3EwWlE9PW5yalBaKy9zV25CbzZLM1Yi.Yih19w.frpENmsuMG82bk07nkYPXfZSE3g
InNmOUpRQ1FQYXFQRlFRY1VueUpzTmkwNHpJWUxvTXBuZFgvV2RUWEIvZkJpL1loTVdCNUp2WjZ0SzI5WWVxRGFkeCtiTkE9PVk3bGEyTGpWMlBIcjVNbTQi.Yih15A.Kncnrh7Hajoi39iFJJEWpSZfBgw



Example of base64 exchanged:
'eyJldmVudHMiOlt7InR5cGUiOiJpbnZpdGVfdmlld2VkIiwicHJvcGVydGllcyI6eyJjbGllbnRfdHJhY2tfdGltZXN0YW1wIjoxNjQ2ODE3NjIwODIyLCJhY2Nlc3NpYmlsaXR5X3N1cHBvcnRfZW5hYmxlZCI6ZmFsc2UsImFjY2Vzc2liaWxpdHlfZmVhdHVyZXMiOjEyOCwicmVuZGVyZWRfbG9jYWxlIjoiZW4tVVMiLCJjbGllbnRfdXVpZCI6IkZHQkM0Y1RMTWcyYVpBb0VGemY2Ylg4QkFBQUlBQUFBIiwiY2xpZW50X3NlbmRfdGltZXN0YW1wIjoxNjQ2ODE3NjIwODIyfX1dfQ=='
converts to 

'{"events":[{"type":"invite_viewed","properties":{"client_track_timestamp":1646817620822,"accessibility_support_enabled":false,"accessibility_features":128,"rendered_locale":"en-US","client_uuid":"FGBC4cTLMg2aZAoEFzf6bX8BAAAIAAAA","client_send_timestamp":1646817620822}}]}'
for example.

**Comment by V4NSH4J** [comment]
Hey, I'm aware of this. I think 2captcha and rucaptcha support sending this additional information to them. I'll write an update for it today or tomorrow.
