### ISSUE TITLE
About `X-Super-Properties`, `X-Track-Properties` and proxy.

### ISSUE THREAD

**Issue by muhitrhn** [V4NSH4J/discord-mass-DM-GO#398]
How do I generate `X-Super-Properties` and `X-Track-Properties`?
Also, I'm thinking of using iproyal for proxies, is it the best choice and which package should I purchase?

**Comment by V4NSH4J** [comment]
`X-Super-Properties` and `X-Track` are just some device information in base64. They are constants so you can just get them from the requests your browser sends out.
Here's an example: 

`eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRmlyZWZveCIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJlbi1VUyIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2OjgzLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvODMuMCIsImJyb3dzZXJfdmVyc2lvbiI6IjgzLjAiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6IiIsInJlZmVycmluZ19kb21haW4iOiIiLCJyZWZlcnJlcl9jdXJyZW50IjoiIiwicmVmZXJyaW5nX2RvbWFpbl9jdXJyZW50IjoiIiwicmVsZWFzZV9jaGFubmVsIjoic3RhYmxlIiwiY2xpZW50X2J1aWxkX251bWJlciI6MTE2MzExLCJjbGllbnRfZXZlbnRfc291cmNlIjpudWxsfQ==`

decodes to 

`{"os":"Windows","browser":"Firefox","device":"","system_locale":"en-US","browser_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","browser_version":"83.0","os_version":"10","referrer":"","referring_domain":"","referrer_current":"","referring_domain_current":"","release_channel":"stable","client_build_number":116311,"client_event_source":null}`

Iproyal is alright, sometimes there are some connectivity issues. You can try packetstream too, they're 1/3rd the price and same proxies.

**Comment by muhitrhn** [comment]
> `X-Super-Properties` and `X-Track` are just some device information in base64. They are constants so you can just get them from the requests your browser sends out. Here's an example:
> 
> `eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRmlyZWZveCIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJlbi1VUyIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2OjgzLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvODMuMCIsImJyb3dzZXJfdmVyc2lvbiI6IjgzLjAiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6IiIsInJlZmVycmluZ19kb21haW4iOiIiLCJyZWZlcnJlcl9jdXJyZW50IjoiIiwicmVmZXJyaW5nX2RvbWFpbl9jdXJyZW50IjoiIiwicmVsZWFzZV9jaGFubmVsIjoic3RhYmxlIiwiY2xpZW50X2J1aWxkX251bWJlciI6MTE2MzExLCJjbGllbnRfZXZlbnRfc291cmNlIjpudWxsfQ==`
> 
> decodes to
> 
> `{"os":"Windows","browser":"Firefox","device":"","system_locale":"en-US","browser_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","browser_version":"83.0","os_version":"10","referrer":"","referring_domain":"","referrer_current":"","referring_domain_current":"","release_channel":"stable","client_build_number":116311,"client_event_source":null}`

Oh, then I can just decode the values you have in the code fro those to find out the values I guess.

> Iproyal is alright, sometimes there are some connectivity issues. You can try packetstream too, they're 1/3rd the price and same proxies.

Do they randomize IP for each connection/request? And I just need to refill the account right?

**Comment by V4NSH4J** [comment]
> > `X-Super-Properties` and `X-Track` are just some device information in base64. They are constants so you can just get them from the requests your browser sends out. Here's an example:
> > `eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRmlyZWZveCIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJlbi1VUyIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2OjgzLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvODMuMCIsImJyb3dzZXJfdmVyc2lvbiI6IjgzLjAiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6IiIsInJlZmVycmluZ19kb21haW4iOiIiLCJyZWZlcnJlcl9jdXJyZW50IjoiIiwicmVmZXJyaW5nX2RvbWFpbl9jdXJyZW50IjoiIiwicmVsZWFzZV9jaGFubmVsIjoic3RhYmxlIiwiY2xpZW50X2J1aWxkX251bWJlciI6MTE2MzExLCJjbGllbnRfZXZlbnRfc291cmNlIjpudWxsfQ==`
> > decodes to
> > `{"os":"Windows","browser":"Firefox","device":"","system_locale":"en-US","browser_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","browser_version":"83.0","os_version":"10","referrer":"","referring_domain":"","referrer_current":"","referring_domain_current":"","release_channel":"stable","client_build_number":116311,"client_event_source":null}`
> 
> Oh, then I can just decode the values you have in the code to find out the values I guess.
> 
> > Iproyal is alright, sometimes there are some connectivity issues. You can try packetstream too, they're 1/3rd the price and same proxies.
> 
> Do they randomize IP for each connection/request? And I just need to refill the account right?
> 
> Edit: I don't see an option to deposit custom amount with PayPal though.

Yes, you can decode the values in my code to find out but you don't really need to, it goes in the requests encoded. Just make sure your useragent, x-track and x-super-properties match everywhere.

Yeah, they have an option for rotating proxies. You just have to refill the account. I'm not sure of the deposit methods, I've always used bitcoin for iproyal and a credit card for packetstream. You should talk to their support about it.

**Comment by muhitrhn** [comment]
Great! Thanks for all the help.
