### ISSUE TITLE
GetCfBm() "r" Variable

### ISSUE THREAD

**Issue by adstromedia** [V4NSH4J/discord-mass-DM-GO#399]
You pass this function 3 paramters : m , r , cookies
How exactly do you obtain the variable "r", by requesting/searching in what?

**Comment by V4NSH4J** [comment]
Hey, thank you for this issue. 
If you observe your network requests, you'd see a request to `https://discord.com/cdn-cgi/bm/cv/669835187/api.js` 
(The number in URL can be different)
This request returns some javascript which is ran with some browser functions to obtain values for r. 
Fortunately, Discord isn't checking if the value of r is repeated as of now, so you can keep it constant. m would change each instance, it's returned from our request to `https://discord.com` from where we get the `__dcfduid` and `__sdcfduid` cookies too. You'd get a new `__cf_bm` each time you repeat the request. 
Alternatively, you can generate random hex strings for r values but I tested it and discord seems to be detecting it so keeping them constant for now would be a better idea. 
As of now, if you don't include the `__cf_bm` cookie at all, it wouldn't matter anywhere (You can test this yourself by blocking the endpoint which sets it)
