### ISSUE TITLE
Error while Solving Captcha: unknown error [1] (invite joiner)

### ISSUE THREAD

**Issue by Doom306** [V4NSH4J/discord-mass-DM-GO#400]
![image](https://user-images.githubusercontent.com/76986040/157588634-ee353055-c6cb-41ff-836a-860389cccc30.png)

**Comment by V4NSH4J** [comment]
You're on an older version of DMDGO 
Error 1 according to anti-captcha.com documentation means that you're using an incorrect API key.

**Comment by Diogovski** [comment]
Any possibility to support another captcha solver? anti-captcha sucks, i have the bot set to wait over 60 seconds per thread ( i only use 1 ) and still he cant either solve it on time or actually solve it.

**Comment by V4NSH4J** [comment]
There are a lot of captcha solvers supported.
