### ISSUE TITLE
Proxy setup.

### ISSUE THREAD

**Issue by muhitrhn** [V4NSH4J/discord-mass-DM-GO#402]
Do I need to use proxy for getting cookies, fingerprint and xcontext also?

**Note:** Not using DMDGO, trying to setup my custom script.

**Comment by V4NSH4J** [comment]
Not really but while making any discord selfbot, you should try to emulate the real scenario as well as possible. Which if you wanted to do, you'll have to use proxies for cookies and fingerprints too. But it wouldn't matter if you didn't as well.
