### ISSUE TITLE
404 Failed to join guild {"message": "404: Not Found", "code": 0}

### ISSUE THREAD

**Issue by oxyuranus1** [V4NSH4J/discord-mass-DM-GO#404]
What's the problem?
![image](https://user-images.githubusercontent.com/99614629/157922749-b8c0e85d-9860-4c72-bd61-36a03aff2f58.png)

**Comment by V4NSH4J** [comment]
yeah LOL
Make sure the invites you added to invites.txt were valid. If you intended to join only one server, use the single invite mode and add one invite when it asks you.
