### ISSUE TITLE
capmonster problem

### ISSUE THREAD

**Issue by MrTlauncher** [V4NSH4J/discord-mass-DM-GO#406]
when program is trying to solve the captcha its just skipping it and trying more and more times
![image](https://user-images.githubusercontent.com/51132775/158032866-9902e9ea-5216-4420-beb0-563821f40f77.png)
but in my capmonster acc i saw that the number of solved captchas is increased

**Comment by MrTlauncher** [comment]
![image](https://user-images.githubusercontent.com/51132775/158033420-7ead3817-6725-420e-a2e4-7b5635b44bdb.png)
also the new problem with new captcha servicies. program gets key but it's trying to solve it more and more.

**Comment by V4NSH4J** [comment]
If you login into your token, you'll find out that it can't join any servers. #370 #363 
Only way around this is getting better tokens, good tokens don't even give you captcha.
