### ISSUE TITLE
func GetCfBm

### ISSUE THREAD

**Issue by LethalSnake1337** [V4NSH4J/discord-mass-DM-GO#409]
https://github.com/V4NSH4J/discord-mass-DM-GO/blob/0373a9e4522ab14c122c4d78144a67bb2552b5f4/utilities/direct_messages.go#L83

Is this function anywhere used because I can't find any reference.

**Comment by V4NSH4J** [comment]
Hey, this function was used from DMDGO v1.8.2 - v1.8.3 but as we were using randomly generated r values, it started to flag tokens. If we make the r values constant and legitimate from browser (it wouldn't matter if they're constant, as discord isn't checking it and it gives a new cookie nonetheless), we can implement it again for the meantime. As of V1.8.4 and v1.8.5 we are not setting a __cf_bm cookie.
