### ISSUE TITLE
scrape error i have installed discum 

### ISSUE THREAD

**Issue by wegwerper** [V4NSH4J/discord-mass-DM-GO#41]
Retrieving Discord's build number...
Could not retrieve discord build number.
list index out of range
 [+] (<discum.start.login.Login->getXFingerprint) Get ->api/v9/experiments
 [+] (<discum.start.login.Login->getXFingerprint) Responxbd\x06\x00\xef\xbf\xbd\x12Y\xef\xbf\xbdU{\xef\xbf\xbd\xf\xbd\x05\xef\xbf\xbd0tQ|\xef\xbf\xbd\xef\xbf\xbdO\xdf\xd\xef\xbf\xbd\xc2\x80\xef\xbf\xbd\x08WP\r\xef\xbf\xbd\xebf\xbd1\xef\xbf\xbdf\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xe9\xb4\x98\xef\xbf\xbd\x1f\xef\xbf\xbd1\xef\xbf\xbd\xee\xef\xbf\xbd\xef\xbf\xbd\x7f/\xef\xbf\xbd\xef\xbf\xbd\xd\xef\xbf\xbd\xef\xbf\xbd\x7f\xef\xbf\xbd\xef\xbf\xbd\xe\xbd\xef\xbf\xbd\x7f_^{\xef\xbf\xbd\xef\xbf\xbdn\xef\xbff\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd?\xef\xbf\xbd\xef\xf\xbf\xbd\xef\xbf\xbd3\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xf\xbd\xef\xbf\xbd\xef\xbf\xbdW\xef\xbf\xbdy\xef\xbf\xbd\bd\xef\xbf\xbd\xe1\xbd\xb7\xef\xbf\xbd\xef\xbf\xbd\xef\xf\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xb\xbdW\xef\xbf\xbd\xef\xbf\xbd\xcf\x9f\xef\xbf\xbd\xef\xb\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdxbd\xef\xbf\xbdk\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdvaN\bd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd+|>\xef\xbf\xbd\xe\xf1\xbd\x97\x8d\xef\xbf\xbdE\xcf\x87\xef\xbf\xbd\x0f<\xbd\xef\xbf\xbd\x1e\x1e\xef\xbf\xbdw\xef\xbf\xbd\xce\xb0fdO_\xef\xbf\xbda\xef\xbf\xbdq\x07\x1cy\xef\xbf\xbd\\V\xedW\xef\xbf\xbd|e\x06\xef\xbf\xbdf\xef\xbf\xbd|\xef\xbf\xny>\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdf\xef\xbf\xbd\xefbd\xef\xbf\xbd;\xcf\x9a\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\05>\x1f\xef\xbf\xbd\x1c\xef\xbf\xbd6}\xef\xbf\xbd=\xef\xxef\xbf\xbd[\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbfbd[@8Q\xef\xbf\xbdd\xef\xbf\xbd-B+\xef\xbf\xbd9\xef\xbf\f\xbf\xbdC5\xef\xbf\xbd\xef\xbf\xbd\n .\xef\xbf\xbd|\xefxef\xbf\xbd\xef\xbf\xbdOT\xef\xbf\xbd\xef\xbf\xbd\xef\xbp|\xef\xbf\xbd\xef\xbf\xbd\x16\xef\xbf\xbdj\xef\xbf\xbddxbd\xef\xbf\xbdeA\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xebd\xef\xbf\xbd\xef\xbf\xbdl\xef\xbf\xbd\xef\xbf\xbd\xef\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdt\xef\xbf\xbd3S\x0b\xd3\xd0\x93\xef\xbf\xbd{\xef\xbf\xbdt~L\xef\xbf\xbd\xef\xd\xd4\x8d}C\x19~\xef\xbf\xbd?Cx\xef\xbf\xbd\xef\xbf\xbdEd\xef\xbf\xbd\xef\xbf\xbd\xde\x8dGW\x047$<\xef\xbf\xbd\xdmv\xef\xbf\xbdI\xef\xbf\xbd\xef\xbf\xbd$\x02\xef\xbf\xb\xbdf{\xef\xbf\xbd\xef\xbf\xbd:\xef\xbf\xbdxo\xef\xbf\xbd\x06a\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x02\xef\xbf\xxbd\\\xef\xbf\xbd\xef\xbf\xbdS\xef\xbf\xbdX\xef\xbf\xbd\xef\xbf\xbd\x15f\xef\xbf\xbd\xef\xbf\xbd<\xef\xbf\xbdc~!xbf\xbd\xef\xbf\xbdI\xef\xbf\xbd\xda\xa9\xef\xbf\xbd+\r\xbd\xef\xbf\xbdG\xef\xbf\xbd.u\xef\xbf\xbd\r\xef\xbf\xbd\xbd[\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdC\xef\xbf\xbd\xxbd:3-\xef\x9a\xa4~\xef\xbf\xbd<\x1fY\xc9\xb8Yj\xcb\xb5\
\xef\xbf\xbd\r\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdP)5{v\xbdS{\xef\xbf\xbd\xef\xbf\xbdr\xef\xbf\xbd\xef\xbf\xbdd\ef\xbf\xbd\xef\xbf\xbdv\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\bf\xbd6\x19b\xef\xbf\xbdF#\xef\xbf\xbd\xef\xbf\xbd@YI\xebd\x1eo\x03W\xef\xbf\xbdP)\x01I5nV\xef\xbf\xbd\xef\xbf\xd\xd9\x990cW83j\xef\xbf\xbd\xef\xbf\xbd\x1d\xef\xbf\xbd\bd\x05G"\xef\xbf\xbd\xef\xbf\xbd:\x08\xc2\x9ai\xef\xbf\xxef\xbf\xbd\xef\xbf\xbdX\x18\x19;\xef\xbf\xbdI\xef\xbf\xxbf\xbdI\xef\xbf\xbd/`\xef\xbf\xbd\xef\xbf\xbd]Jl\xef\xb\n\xc5\x84z\xef\xbf\xbd\x05\x08\xef\xbf\xbd\xef\xbf\xbd\xbd\xef\xbf\xbd\xef\xbf\xbd\n\xef\xbf\xbd\xef\xbf\xbd\xe>\xef\xbf\xbd\xc2\x96\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbbf\xbd\x02\x1c\xef\xbf\xbdx\xef\xbf\xbd\xef\xbf\xbd\xe8\xef\xbf\xbdQ\xef\xbf\xbdd\x13\xef\xbf\xbd\x03tu\xef\xbf\bf\xbdZ\xef\xbf\xbdn\xef\xbf\xbd\x13\xec\xaa\xb6\x1d\x00\xbda\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xc\xef\xbf\xbdd|\xef\xbf\xbdp2\xef\xbf\xbd\xef\xbf\xbd\x15xbf\xbdQ\xef\xbf\xbd\xc2\x8d\xd2\x8c\xef\xbf\xbd\xef\xbf\xbf\xbd[\xef\xbf\xbd\xef\xbf\xbd5gb\xef\xbf\xbd]\xef\xb\x13\xcd\xa2y\n\xe3\x99\xb4\xef\xbf\xbd\xef\xbf\xbd\x0cF\xbd\n\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xxbd4gN\xef\xbf\xbd\xef\xbf\xbdE\xef\xbf\xbd\xef\xbf\xbd f\xbd1\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdQ@xbf\xbd\xef\xbf\xbdf\x1b\xef\xbf\xbd\xef\xbf\xbdLx=\xc3\bd\xef\xbf\xbdR\xef\xbf\xbdbE;\xef\xbf\xbd\xef\xbf\xbd\xd9\x13n\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd6\xef\xbf\xbd\xbdu\xef\xbf\xbdE\xef\xbf\xbd\xef\xbf\xbdS\x07\xef\xbf\f\xbf\xbd!\xef\xbf\xbd\x19\xef\xbf\xbd8NQ\xef\xbf\xbd4\xd\x10\xef\xbf\xbd\xef\xbf\xbd\x15\xef\xbf\xbd/\xef\xbf\xf\xbd5;\x1b\xef\xbf\xbd\x0f\xef\xbf\xbd\xef\xbf\xbd\xef\xef\xbf\xbd\x07I\xef\xbf\xbdE*\xef\xbf\xbd \xef\xbf\xbd\\xbf\xbd\xc3\x99v75\xef\xbf\xbdU\xef\xbf\xbd\xe\xbf\xbd\f\xbf\xbdT\x07\xef\xbf\xbd\xef\xbf\xbdQ\r9\xef\(\xef\xbfxbf\xbd\xef\xbf\xbd\x03\xef\xbf\xbd"(\xef\xbf\xef\xbf\xbbdZ\x19W(\xef\xbf\xbdXG\xef\xbf\xbd\'G\xef\xbf\xbdJ\x14\xbd\r\xef\xbf\xbdHl\xdc\xa4\xef\xbf\xbd\xef\xbff\xbd+-\rxbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\f\xbf\xbd`+xbd\xef\xxbdJ\x14\xef\xbf\xbd`+\xcc\x9e\xef\x\xef\xbf\xbxbf\xbd\xbf\xbdm\xef\xbf\xbd2YW\xef\xbf\xbd+-dgzW\xef\xb\xbd3\xef\xbf\xbd+-\r\xca\x8f\xef\x\xbf\xbdgzf\xbf\xbd\xxd7\x97\xbf\xbd\xef\xbf\xbdgzW\xef\xef\xbf\xbxbd\xef\xbf\xbf\xbd\xbf\xbd\xef\xbf\xbd\xef\xbxbdl\xef\xbf\xbd\xef\bf\xbd\xef\xbd\x05\xef\xbf\xbd\xef\\xbf\xbd\x6\xb9\xef\xxbf\xbdl\xef\xbf\xbd\x16\xef\xbf\xbd\xbd\x0c\x116\xef\xbf\xbd\xef\xbf\xef\xef\xbf\xxef\xbf\xbd\xbd\xef\xbf\xbd~\xef\\xef\xbf\xbdu*f\xbd\xdc\xef\xbf\xbd>\xef\xbfd\xxef\18(\xef\xb\xbd\r\x03'\xbd\xef\xbf\xbd3\xef\xbf\xbda\xef\xbf\xbd\xd6\xb9\xef\xbf\xbd\xef\xbf\xbdu*\xd7\x97\xef\xbf\xbd\x0c\x18(\xef\xbf\xbd\xef\xbf\xbdl7fN&T25n\xef\xbf\xbd\xef\xbf\xbd\x03i\xef\xbf\xbd\xef\xbf\xbd\xdc\xa6lm\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\r\x03'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\Desktop\discord - kopie\scraper\scrape.py", line 10, in <module>
    bot = discum.Client(token='yes my token was here')
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discum\start\login.py", line 38, in getXFingerprint
    xfingerprint = reqxfinger.json().get('fingerprint')
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
�� ,�1�f���j�̚鴘��1��Xڎ��/�����������_^{��n�ّCLί���?�����3�������W�y����ί���
��������W��ϟ�����������k���vaN�����+|>���񽗍�Eχ�<�3���w�ΰf/ 7�╚~~dO_�a�qy�\V�v�W
�|e═�f�|�O�R
y>���f��rv`��;Ϛ����JK-n║>��6}�=�W�3�[����d
�[@8Q�d�-B+�9�Uw�U�C5��
��������W��ϟ�����������k���vaN�����+|>���񽗍�Eχ�<�3���w�ΰf/ 7�╚~~dO_�a�qy�\V�v�W�|e═�f�|�O�R
y>���f��rv`��;Ϛ����JK-n║>��6}�=�W�3�[����d
�[@8Q�d�-B+�9�Uw�U�C5��
 .�|����OT���?�p|���j�d���eA����       ���l���p����t�3S
  ��X;�I�/�)�I�/`��]Jl��                               ��3Г�{�t~L��╗�ԍ}C~�?Cx��E���P)5{v�-�S{��r��d֣���v�����6
b�F#��@YI�d%�o╚W�P)╔I5nV��Ǒ�ٙ0cW83j���參�║G"��i�BZ�
����>�����6U�╗�x��蔭l��Q�d�╚tu���Z�n�쪶 �q�a����Η���X;�I�/�)�I�/`��]Jl��
ńz���N���
����>�����6U�╗�x��蔭l��Q�d�╚tu���Z�n�쪶 �q�a����Η�hi       �d|�p2����Q�Ҍ���v�[��5gb�]��͢y
㙴��F�h�
����F�h�
����ލ7Q�4gN��E�� Ce��1����Q@N�3jy��f?��Lx=Ú��R�bE;����9n���6�}��u�E��S�Gjw��!��╚: 0zW���║��l����~�>��3�a�ֹ��
u*ח�                            (��l7fN&T25n��╚i��ܦlm���
PS C(��l7fN&T25n��╚i��ܦlm���

**Comment by wegwerper** [comment]
i had installed discum ,last week it still worked on my old laptop

**Comment by V4NSH4J** [comment]
Looks like it's brotli encoded or something, could you try installing https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by V4NSH4J** [comment]
Please use DMDGO V1.0.7, it has inbuilt scraper
