### ISSUE TITLE
Captcha API key

### ISSUE THREAD

**Issue by Sorlnco** [V4NSH4J/discord-mass-DM-GO#411]
I was trying to use this to raid a server but when i do it i get an error that says "Error while Solving Captcha: No captcha API key or Incorrect Captcha API key (Can happen if you've specified a different service but using a different service's key)". Could u fix this please?

**Comment by V4NSH4J** [comment]
What's there to fix? Have you put a captcha API key in the config?

**Comment by Sorlnco** [comment]
i dont know how to add an api key do i have to buy it

**Comment by V4NSH4J** [comment]
Although I highly recommend getting tokens which do not give a captcha on joining servers as solving the captcha using public solver services has a very high chance of getting the account flagged. 
You can use services like 2captcha.com anti-captcha.com capmonster.cloud

**Comment by cristianberbecaru** [comment]
I put the key from capmonster in the config file but it won't resolve the captcha


<img width="957" alt="image" src="https://user-images.githubusercontent.com/32863083/158875883-d804cfc7-0398-44eb-8ebf-72539b5ac1cc.png">

**Comment by V4NSH4J** [comment]
Please get tokens which don't give captcha. This new captcha key can not be solved by most public captcha solving APIs yet.
