### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by john1122334455** [V4NSH4J/discord-mass-DM-GO#412]
I am using proxyware, and the proxy was running perfectly but now I am getting this error.
![image_2022_03_15T05_32_40_255Z](https://user-images.githubusercontent.com/99329787/158313502-7c9a18ef-7b25-41ca-ae14-046b5c4e1924.png)

**Comment by SolSecSociety** [comment]
same here

**Comment by V4NSH4J** [comment]
Unexpected EOF = Unexpected End of File
(File refers to the response body from discord) 
Meaning discord either did not send a response or sent an invalid response. This is technically a connection problem, it could be your proxy or your own internet. I can't help you with connection related problems with your proxies.

**Comment by SolSecSociety** [comment]
In my case it was the "proxy_protocol" set to null... i cahnged it to "https" and it worked out
