### ISSUE TITLE
Email-verified tokens getting banned after 3-5 attempts 

### ISSUE THREAD

**Issue by kaleragot** [V4NSH4J/discord-mass-DM-GO#42]
Hi, I tried to send mass DMs with email verified tokens but they get banned very quickly (3-5 attempts). I have a rotating proxy with a lot of different residential address (smartproxy) that I'm using to run the script, however, the tokens are still blocked very quickly. Any idea what might be the issue?

**Comment by cChimney** [comment]
Bad tokens

**Comment by V4NSH4J** [comment]
As cChimney said, many domains got flagged in the recent discord patch which is causing tokens to lock quickly. Try logging into any one token and send DMs manually to confirm.

**Comment by kaleragot** [comment]
My tokens are from outlook/ gmail. Just confirmed, I can send around 40 messages manually. I suspect it has something to do with the rotating proxy since a new IP for most new messages would seem suspicious. Thoughts?

**Comment by kaleragot** [comment]
Also when I'm creating the tokens, many get immediately phone number locked since even many of the residential IPs are banned by Discord. Do you guys have any suggestions for which residential proxies work better?

**Comment by kaleragot** [comment]
I tried a bunch of fresh unblocked ip addresses, created a new token and verified on outlook, but the token keeps getting locker after exactly 5 tries. I also changed `individual_delay` to 60 seconds and even added a random delay to it, but no luck :(

**Comment by V4NSH4J** [comment]
> My tokens are from outlook/ gmail. Just confirmed, I can send around 40 messages manually. I suspect it has something to do with the rotating proxy since a new IP for most new messages would seem suspicious. Thoughts?

It's less suspicious than tons of accounts on same IP 


> I tried a bunch of fresh unblocked ip addresses, created a new token and verified on outlook/ google, but the token keeps getting locked after exactly 5 tries (even tried MFA tokens). I also changed `individual_delay` to 60 seconds and even added a random delay to it, but no luck :(

Interesting, Could you DM me on Discord V4NSH4J#4424 I'll give you some tokens which I know get around 50 or more DMs so you can try them out and we can figure out if it's a problem with your config/installation or the tokens.

**Comment by kaleragot** [comment]
Sure, appreciate it! I tried to join your discord ([https://discord.gg/6BsEXEHuNS](https://discord.gg/6BsEXEHuNS)) but my mfa account gets immediately banned. Is there any other way to contact you?

**Comment by V4NSH4J** [comment]
V4NSH4J#4424

**Comment by kaleragot** [comment]
sent you a request from eaglestart#1189. Thanks!

**Comment by V4NSH4J** [comment]
Got termed, new discord V6NSH4J#1511
