### ISSUE TITLE
Captcha won't be resolved from multiple attempts

### ISSUE THREAD

**Issue by cristianberbecaru** [V4NSH4J/discord-mass-DM-GO#420]
With capmonster

<img width="957" alt="image" src="https://user-images.githubusercontent.com/32863083/158876081-3bee28b6-32d0-48f0-93ad-c8732398b78c.png">

**Comment by cristianberbecaru** [comment]
Same with anti-capcha.com
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/32863083/158881348-1c4a20b8-885e-4c52-a843-3934f0fab57c.png">

**Comment by V4NSH4J** [comment]
Most captcha services can't solve the new captcha sitekey yet. I recommend getting better tokens.
