### ISSUE TITLE
coding help(python)

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#425]
i'm try to code some python script about reacting. the point is this, i will be able to type how many tokens will react to message. but i couldnt figure it out

**Comment by V4NSH4J** [comment]
Store your tokens in an array, once you have the number of tokens to use from the user, use the tokens upto that index to react.

**Comment by pscpc** [comment]
i didn't understand sorry. my knowledge of english and programming language is weak. please, can you send me some template

**Comment by pscpc** [comment]
this is my final code. but its output as "{"message": "Unknown Emoji", "code": 10014}"
![image](https://user-images.githubusercontent.com/56173496/159195364-ab5215e2-6004-46d7-9243-f139761bfb81.png)

**Comment by Doom306** [comment]
you are supposed to replace the {emoji} i think

**Comment by V4NSH4J** [comment]
Yeah, in place of emoji, you have to add a unicode emoji or a Nitro emoji in format (Id:name or name:id I forgot) in URL encoding. You can use f-strings.

**Comment by APrimaveraV** [comment]
This thanks is for me sr?
