### ISSUE TITLE
How did you get the cookie here?

### ISSUE THREAD

**Issue by Doom306** [V4NSH4J/discord-mass-DM-GO#427]
https://github.com/V4NSH4J/discord-mass-DM-GO/blob/0373a9e4522ab14c122c4d78144a67bb2552b5f4/utilities/invite.go#L164

**Comment by V4NSH4J** [comment]
https://github.com/V4NSH4J/discord-mass-DM-GO/blob/0373a9e4522ab14c122c4d78144a67bb2552b5f4/utilities/direct_messages.go#L29

**Comment by Doom306** [comment]
Aight ty
