### ISSUE TITLE
MacOS run discord-mass-dm-GO

### ISSUE THREAD

**Issue by uzushitn** [V4NSH4J/discord-mass-DM-GO#43]
I can't run discord-mass-dm-GO on macos is there something I missed or I should know ?

**Comment by V4NSH4J** [comment]
Hi, if you're on MacOS with the M1 chips (ARM64) You'd have to build from source. This is explained in the readme.

If you're on MacOs with Intel chips (AMD64) You can download the binary from releases and execute these commands in the terminal in the right directory:
`chmod +x ./discord-mass-dm-GO`
`./discord-mass-dm-GO`

If you're unsure what's your architecture, you can check your computer specifications or install GO from https://golang.org and type `go version` on the terminal
