### ISSUE TITLE
Error while opening memberids.txt , The system cannot find the path specified.

### ISSUE THREAD

**Issue by siriwiz** [V4NSH4J/discord-mass-DM-GO#432]
![Screenshot (2637)_LI](https://user-images.githubusercontent.com/101368969/159631242-381f38ae-d8e7-4050-a13c-fc17445b4a73.jpg)

**Comment by V4NSH4J** [comment]
Hey, you're running the source code using `go run`, the program looks for the associated files relative to the binary. When you do `go run` it builds the binary in some temporary directory where the files are not present. Doing `go build` then running the binary would fix this problem. You can also download a pre-compiled version matching your OS/Arch from the releases section.
