### ISSUE TITLE
Cannot join server. Captcha error. 

### ISSUE THREAD

**Issue by BrancasKitchen** [V4NSH4J/discord-mass-DM-GO#434]
Keep receiving a cannot bypass captcha error 25. Captcha cannot be solved. Im using anti-captcha. This when trying to join a server

**Comment by BrancasKitchen** [comment]
<img width="397" alt="Screenshot 2022-03-23 at 16 18 09" src="https://user-images.githubusercontent.com/28354552/159733419-81053bf0-6898-4c61-be42-3ebd8104293b.png">

**Comment by BrancasKitchen** [comment]
<img width="438" alt="Screenshot 2022-03-23 at 16 23 17" src="https://user-images.githubusercontent.com/28354552/159734512-facd627a-9d79-453b-bf29-7e719f56bc9e.png">

**Comment by V4NSH4J** [comment]
No, but they don't support hostname, try using the IP.

**Comment by BrancasKitchen** [comment]
<img width="910" alt="Screenshot 2022-03-23 at 21 27 18" src="https://user-images.githubusercontent.com/28354552/159789760-9e00dbff-ad04-4796-a730-23f9069df772.png">
i already tested IP before. i turned off the proxie for captcha and the problem still remains.

**Comment by BrancasKitchen** [comment]
<img width="343" alt="Screenshot 2022-03-23 at 21 28 58" src="https://user-images.githubusercontent.com/28354552/159789982-b540d126-8876-45f3-a60a-562e55c20f10.png">
i removed the captcha key for this screenshot. Am i doing something wrong?

**Comment by BrancasKitchen** [comment]
weird thing is that everything worked smoothly yesterday

**Comment by maxaxicek** [comment]
Hello i have problem with server joining too. Keep getting catpcha detected nothing solving

**Comment by BrancasKitchen** [comment]
<img width="911" alt="Screenshot 2022-03-23 at 22 22 09" src="https://user-images.githubusercontent.com/28354552/159797953-b06b5846-e34f-4188-84ba-76d1015d9733.png">
im fairly confident everything is set to the right settings. Since it worked yesterday.

**Comment by maxaxicek** [comment]
![image](https://user-images.githubusercontent.com/56396704/159799080-afcc5a78-490a-4b7c-8bcf-3cac93c882a1.png)
this is what i got

**Comment by gitiliya** [comment]
getting this error aswell atm
using capmonster

**Comment by APrimaveraV** [comment]
Can be posible have call assistance?

**Comment by kyriesol** [comment]
Got the same problem as @maxaxicek
<img width="948" alt="Снимок экрана 2022-03-24 в 19 41 46" src="https://user-images.githubusercontent.com/100087094/159955474-38a49d3c-5ac1-4c65-8adc-1931f18caae8.png">

**Comment by lukosevic** [comment]
I am having the same problem. I tried anti-captcha and capmonster

**Comment by BrancasKitchen** [comment]
Has anyone resolved this? Still receiving the same error

**Comment by smith2122** [comment]
Same here, having the same issue

**Comment by scastradio** [comment]
same issue still with 1.8.6

**Comment by V4NSH4J** [comment]
#488
