### ISSUE TITLE
scraping - nothing happens ?

### ISSUE THREAD

**Issue by harry9222** [V4NSH4J/discord-mass-DM-GO#439]
Hi guys, new here so appreciate if i could get some guidance.
I succesfully joined the tokens in a server, however when i use the offline scraper and put the number of tokens i want to use, 
nothing happens. I hit enter and it does nothing, no error, nothing.
Anyone have any ideas why this might be happening ? 
thanks in advance !
![2022-03-25 00_43_05-V4NSH4J_discord-mass-DM-GO_ The most popular Discord selfbot written in GO allow](https://user-images.githubusercontent.com/102333421/160027948-07a4aec1-6b8e-40c0-848f-80d1320e347e.png)
![2022-03-25 00_45_34-scraping - nothing happens _ · Issue #439 · V4NSH4J_discord-mass-DM-GO](https://user-images.githubusercontent.com/102333421/160027960-a37a30a8-2695-4c99-9a29-6c925179e9e3.png)

![2022-03-25 00_44_30-config - Notepad](https://user-images.githubusercontent.com/102333421/160027663-c12424ea-f936-4c76-abdf-e165f57154b0.png)

**Comment by misty00x** [comment]
It's because you are entering the invite link and you are suppose to enter the ServerID. Those are different.

**Comment by V4NSH4J** [comment]
Yeah ^ you have to enter th server ID. Turn on developer settings on Discord and right click the s ever to copy it's ID

**Comment by harry9222** [comment]
thanks guys, I did not realize that ! Will try with server ID later on today, hopefully it goes well
