### ISSUE TITLE
dankgrinder formatting issue

### ISSUE THREAD

**Issue by hey000hey** [V4NSH4J/discord-mass-DM-GO#440]
hello, i'm writing this here because issues is disabled(?) on the dankgrinder page. Whenever I run the bot with more than one instance, I recieve this message 
![image](https://user-images.githubusercontent.com/83317718/160217891-8b1930bb-6e7d-4c58-bdfd-d2d39563ecef.png)
but I literally copy-pasted the format that the example used. My current setup is this: clusters:
  default:
    master:
       token: "OTQzNzI2MDQ3ODk0MDQ0NzE2.Yg3RUA.1WSLwImHnGWhJZ9AuwXxbpIs0e8"
       channel_id: "957070692451495947"  
      instances: 
       - token: "OTQzNzI3NjUzMjc2NDk5OTk4.Yg3RVg.gEHW9hcKvXcR0lbKPkZVsjjEZQE"
	 channel_id: "957070692451495947"

**Comment by hey000hey** [comment]
clusters:
  default:
    master:
       token: "OTQzNzI2MDQ3ODk0MDQ0NzE2.Yg3RUA.1WSLwImHnGWhJZ9AuwXxbpIs0e8"
       channel_id: "957070692451495947"  
      instances: 
       - token: "OTQzNzI3NjUzMjc2NDk5OTk4.Yg3RVg.gEHW9hcKvXcR0lbKPkZVsjjEZQE"
	 channel_id: "957070692451495947"

**Comment by hey000hey** [comment]
`clusters:
  default:
    master:
       token: "OTQzNzI2MDQ3ODk0MDQ0NzE2.Yg3RUA.1WSLwImHnGWhJZ9AuwXxbpIs0e8"
       channel_id: "957070692451495947"  
      instances: 
       - token: "OTQzNzI3NjUzMjc2NDk5OTk4.Yg3RVg.gEHW9hcKvXcR0lbKPkZVsjjEZQE"
	 channel_id: "957070692451495947"`

**Comment by hey000hey** [comment]
hmm, i'm not sure how to format it correctly on github, could someone add me on discord (Akari#7949) and help? ty

**Comment by V4NSH4J** [comment]
Hey, the formatting does make it difficult to read. You can make an issue on the parent repository https://github.com/dankgrinder/dankgrinder or join the official discord server https://discord.gg/w4AbYJ4GcC
Also you can attach your config.yml as a file and please do not share your token, it can be used to login into your account.

**Comment by hey000hey** [comment]
[config.txt](https://github.com/V4NSH4J/discord-mass-DM-GO/files/8356486/config.txt)

here

dw, that's not my own token
