### ISSUE TITLE
Captcha Detected

### ISSUE THREAD

**Issue by gitiliya** [V4NSH4J/discord-mass-DM-GO#445]
Captchas aren't getting solved and they exceed max retries, I am using capmonster.

**Comment by V4NSH4J** [comment]
Find better tokens, good tokens don't even give you captcha.

**Comment by gitiliya** [comment]
> Find better tokens, good tokens don't even give you captcha.

It's because I have email verified tokens, not phone verified. Unless you can find me some cheap phone verified tokens ill continue using aged email accounts, nonetheless that doesn't change the fact that the captcha solver doesnt work lol

**Comment by V4NSH4J** [comment]
The captcha solver works. It's not my problem if public captcha solving APIs can't solve certain type of captchas. And finding tokens is your problem not mine, I just maintain the program. So if you have a real problem, feel free to reopen this.
