### ISSUE TITLE
DMs not sendet to all users

### ISSUE THREAD

**Issue by ChristianErdtmann** [V4NSH4J/discord-mass-DM-GO#45]
Hey i have a server with 4 Users.
3 Accounts of them are from me for testing.

I run the software and get the message;

Token ..... send DM to 897697625124511804 [3]

and it said "Secussfully sent DMs to 3 IDs" - I got 3 Ids in my mebersids.txt

But now i checked my Discord accounts and i got 0 Messages on my Accounts.
The other account i cant check because its not mine.

How to solve this?

**Comment by ChristianErdtmann** [comment]
All ids are now deleted from the membersids.txt but i got no messages to this accounts

**Comment by V4NSH4J** [comment]
Are you sure? This isn't possible. Have you made sure they weren't already in completed.txt or anything?

**Comment by ChristianErdtmann** [comment]
Thanks. That was the problem they wasnt deleted in completed.txt
