### ISSUE TITLE
Question Regarding The Amount Of Tokens I Could Use?

### ISSUE THREAD

**Issue by Clarence21Clarence21** [V4NSH4J/discord-mass-DM-GO#453]
How many tokens would I be able to use at the same time with a great gaming pc and 10 Mbps upload speed? I plan on sending out loads of medium length messages to people on discord and I'm trying to figure out how many tokens I could have running on the DMDGO mass dm. I saw on the video you guys were using 300 tokens and getting like 8/10 messages per second, but I wanted to ask if I could raise the amount of tokens to a few thousand, or if that would be too much. Thank you.

**Comment by gajojr** [comment]
> How many tokens would I be able to use at the same time with a great gaming pc and 10 Mbps upload speed? I plan on sending out loads of medium length messages to people on discord and I'm trying to figure out how many tokens I could have running on the DMDGO mass dm. I saw on the video you guys were using 300 tokens and getting like 8/10 messages per second, but I wanted to ask if I could raise the amount of tokens to a few thousand, or if that would be too much. Thank you.

How did you generate 1000 tokens?

**Comment by Clarence21Clarence21** [comment]
> 

I plan on buying some
