### ISSUE TITLE
It's still 1.8.6 on the 1.8.7 update

### ISSUE THREAD

**Issue by Masoud6267** [V4NSH4J/discord-mass-DM-GO#461]
It's still 1.8.6 on the 1.8.7 update

**Comment by Masoud6267** [comment]
Thank you for this cool tool. Please re-check the latest version that you've uploaded. I think you uploaded the V1.8.6 again

**Comment by Masoud6267** [comment]
![image](https://user-images.githubusercontent.com/96719873/161220342-c8019b46-9579-48d6-b901-68bfcab720c9.png)

**Comment by Masoud6267** [comment]
Still getting HTTP response code 400 (Bad request) while DM'ing

**Comment by king3435** [comment]
still captcha problem.

**Comment by king3435** [comment]
Tokens won't join a server.

**Comment by tw9cRC9x** [comment]
same for me, tokens wont join

**Comment by Seredar** [comment]
same for me

**Comment by BrancasKitchen** [comment]
same captcha problem as before, and also seeing 1.8.6 on windows version

**Comment by leodigitalpro** [comment]
i have captcha problem too

**Comment by M-Jawad-Ch** [comment]
I have captcha problems too

**Comment by V4NSH4J** [comment]
#465 captcha on DMs is currently bypassed with v1.8.8 
The version issue was me just forgetting to update the version number, sorry for that.
