### ISSUE TITLE
400 bad request not fixed in the 1.8.7 update

### ISSUE THREAD

**Issue by M-Jawad-Ch** [V4NSH4J/discord-mass-DM-GO#465]
Hey, so I built from source and am still getting "400 bad request", about 10 dms are successful in every thousand for me

**Comment by Seredar** [comment]
+++

**Comment by king3435** [comment]
Hi. I build from source as well. Its working fine for me. out of 67 DMs 49 were successful 18 failed.

**Comment by V4NSH4J** [comment]
https://github.com/V4NSH4J/discord-mass-DM-GO/releases
Try v1.8.8 discord has added captchas on DMs, it's for now completely bypassed by DMDGO till they patch it. I'll look for more permanent solutions in the meantime.
