### ISSUE TITLE
Captcha problem on joining.

### ISSUE THREAD

**Issue by tw9cRC9x** [V4NSH4J/discord-mass-DM-GO#467]
Tokens wont join on server due to captcha, i used good tokens with email + phone verified 
![image](https://user-images.githubusercontent.com/102795762/161341604-ac74551e-420b-45aa-8cb9-33c23f78e22c.png)

**Comment by kovgan201** [comment]
I had this issue when I used email verified tokens, but when I bought email+phone I didn't have this issue anymore

**Comment by tw9cRC9x** [comment]
> I had this issue when I used (tokinaist) email verified tokens, but when I bought email+phone I didn't have this issue anymore

bro, but i have always used tokens with phone and email verified

**Comment by KKamoto** [comment]
i have same problem. after 1 invite token is dying because of captcha

**Comment by V4NSH4J** [comment]
#488
