### ISSUE TITLE
Error on Mass DM stage

### ISSUE THREAD

**Issue by kovgan201** [V4NSH4J/discord-mass-DM-GO#468]
Everything done properly, IPRoyal rotating proxy, UHQ tokens phone verified.
So first I checked all the tokens, then I joined those tokens to targeted server, after this I used DMDGO scrapper and one of the tokens that joined to get memberIDs. After this I checked if my tokens are still in the guilt and after successful check I started massDM using my message.json But for some reason I`m getting this error and I don't know how to deal with it, tried to change some config stats to make process longer but still no juice. 
First I`m getting green message that websocket connected successfully and after it errors
You've seen all my steps, where did I make a mistake?
![dmdgo web](https://user-images.githubusercontent.com/102835957/161352739-db7182bf-6ba5-4e1b-86d9-6e1442489538.png)
![dmdgo fail](https://user-images.githubusercontent.com/102835957/161352742-fd2fb263-b2dc-4241-9b3e-cbdc1e7a9af0.png)

**Comment by kovgan201** [comment]
Any ideas guys? really need to fix it

**Comment by V4NSH4J** [comment]
#465 update to DMDGO 1.8.8
