### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by ramez121** [V4NSH4J/discord-mass-DM-GO#470]
![image](https://user-images.githubusercontent.com/86024913/161422960-4a21d2b3-8293-4972-8a7d-4c61a6b2e269.png)

**Comment by xagler** [comment]
same for me

**Comment by wawryoski** [comment]
Same... pls help with it :)

**Comment by V4NSH4J** [comment]
Hi, this is because Discord has implemented Captchas on sending DMs and the bypass that was implemented in v1.8.8 is patched. Please wait for an update, in the meantime, your tokens can send a maximum of 10 DMs before getting the captcha.

**Comment by ramez121** [comment]
@V4NSH4J sorry for the mention could you tell me how to open chat with the id and i can help with a new method.... 


Yours, 

Ramez

**Comment by V4NSH4J** [comment]
@ramez121 You can check the direct_message.go file to see how to open channels

Yours, 

Vanshaj

#488 for captcha issues.
