### ISSUE TITLE
Captcha doesn't send results back

### ISSUE THREAD

**Issue by kovgan201** [V4NSH4J/discord-mass-DM-GO#471]
So on joining to a server I'm getting a captcha, I can see that captcha is going through but I'm not getting it back, so token couldn't join
![caa](https://user-images.githubusercontent.com/102835957/161430391-4b48e5a3-f146-4ff6-be69-66f8768db6a8.png)
![captcha](https://user-images.githubusercontent.com/102835957/161430392-13829204-c7d1-47ee-8c1e-09eed9d4eeaf.png)

**Comment by tw9cRC9x** [comment]
same for me :(

**Comment by king3435** [comment]
That cannot be solved i guess. Once tokens need captcha to solve to join a server they are done. You need new aged tokens again for them to join a server.

**Comment by V4NSH4J** [comment]
Yeah ^ Anyways I've fixed invite joiner for capmonster.cloud and 2captcha.com in the source code if you want to try again.

**Comment by kovgan201** [comment]
Hey thanks, seems to be a little bit better on joiner. But now scraper stopped working 
![scrape](https://user-images.githubusercontent.com/102835957/161565454-60c05768-2d89-4118-beda-68c441f00ff6.png)
