### ISSUE TITLE
tokens got banned after I sent 79 dms (50 tokens)

### ISSUE THREAD

**Issue by alikeremo** [V4NSH4J/discord-mass-DM-GO#472]
Hi I used 150 proxies and all 50 of my tokens got banned after sending 79 dms what would you advice ?
<img width="1440" alt="Screen_Shot_2022-04-03_at_18 17 19" src="https://user-images.githubusercontent.com/88512101/161435152-171570a7-8aae-4843-bdaf-de64e82f51ec.png">

**Comment by LongTomForever** [comment]
This is very bad, really need advice.
I bought 500 tokens and expected at least 5000 DM

**Comment by V4NSH4J** [comment]
#488

**Comment by AriGatoa** [comment]
Hey did you find a solution for the tokens getting banned??
