### ISSUE TITLE
Captcha failed with panic: runtime error: index out of range [1]

### ISSUE THREAD

**Issue by Platonx99** [V4NSH4J/discord-mass-DM-GO#473]
When trying to enter channel by invite: 

panic: runtime error: index out of range [1] with length 1

goroutine 33 [running]:
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Instance).SolveCaptchaCapmonster(0xc00000c5a0, {0xc0003f40c0, 0x24}, {0xc0000c4210, 0xaf}, {0xc000238000, 0xa8})
	/opt/discord/discord-mass-DM-GO/utilities/captcha.go:61 +0x1749
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Instance).SolveCaptcha(0xc00000c5a0, {0xc0003f40c0, 0x24}, {0xc0000c4210, 0xaf}, {0xc000238000, 0xa8}, {0xc0001de0a0, 0x9b})
	/opt/discord/discord-mass-DM-GO/utilities/captcha.go:19 +0x305
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Instance).Invite(0xc00000c5a0, {0xc00023a300, 0x8})
	/opt/discord/discord-mass-DM-GO/utilities/extra.go:286 +0xa1c
main.Options.func1(0x1c)

	/opt/discord/discord-mass-DM-GO/main.go:111 +0x56
created by main.Options
	/opt/discord/discord-mass-DM-GO/main.go:110 +0x8bbf

![captcha_dm](https://user-images.githubusercontent.com/39624131/161485174-9fcb6013-c71b-416a-823c-20ee5ef825c1.png)

**Comment by ganynmednet** [comment]
same here

![image](https://user-images.githubusercontent.com/51125243/161538465-e739bc3e-c22d-4193-8a4d-d8a85d3c5b58.png)
