### ISSUE TITLE
Captcha is again patched.

### ISSUE THREAD

**Issue by lukosevic** [V4NSH4J/discord-mass-DM-GO#477]
After sending 8-10 DMs, it won't bypass captcha. Max retries reached.

**Comment by ganynmednet** [comment]
have this problem
![image](https://user-images.githubusercontent.com/51125243/161586334-5077c31b-9c4e-40d5-af69-a33f32aafb57.png)

**Comment by lukosevic** [comment]
yeah something like that

**Comment by V4NSH4J** [comment]
#488
