### ISSUE TITLE
Cannot confirm captchas

### ISSUE THREAD

**Issue by alikeremo** [V4NSH4J/discord-mass-DM-GO#479]
![20220404_224756.jpg](https://user-images.githubusercontent.com/88512101/161620590-09bed1d8-c2cd-4f35-8cab-8c11ea274b96.jpg)

**Comment by lukosevic** [comment]
yes, we all have the same issue.

**Comment by yawww94854** [comment]
yes

**Comment by V4NSH4J** [comment]
#488
