### ISSUE TITLE
Windows 10: EXE detected as Win32/Wacapew.C!ml by Microsoft Defender

### ISSUE THREAD

**Issue by GradinCheese** [V4NSH4J/discord-mass-DM-GO#48]
Anybody else run into this issue when attempting to download the zip? Is this just a false positive? 
containerfile: D:\Downloads\DMDGO_v1.0.6_windows.zip

**Comment by V4NSH4J** [comment]
It is indeed a false positive, but don't take my word. Run it on Sandbox/VM
