### ISSUE TITLE
plz help i am getting this in mass dm

### ISSUE THREAD

**Issue by ramez121** [V4NSH4J/discord-mass-DM-GO#486]
![image](https://user-images.githubusercontent.com/86024913/161945833-943e9e4e-90b0-48e2-a2ca-7953c5ae0025.png)

**Comment by LongTomForever** [comment]
it looks like you have a problem with proxy servers, are you sure that your set of servers is operational?
Did you write them in the correct format in the file?

**Comment by king3435** [comment]
Proxy format:
Username:password@IP:PORT

**Comment by ramez121** [comment]
> Proxy format: Username:password@IP:PORT

Pro i don't use proxies

**Comment by ramez121** [comment]
> it looks like you have a problem with proxy servers, are you sure that your set of servers is operational? Did you write them in the correct format in the file?

I don't use proxies thier is some with the dmgo

**Comment by ramez121** [comment]
Any one could help please

**Comment by ramez121** [comment]
@V4NSH4J

**Comment by LongTomForever** [comment]
If you are not using a proxy, check the settings in config.yml in the section "proxy_settings:"

**Comment by V4NSH4J** [comment]
I think you left in the default proxies, head over to your config and disable proxy_from_file. 
Reopen if problem persists.
