### ISSUE TITLE
termed

### ISSUE THREAD

**Issue by cateee69** [V4NSH4J/discord-mass-DM-GO#49]
Hello,

Your account is receiving this notice due to participation in a server that violates our Community Guidelines.

Specifically, Discord TOS Followers allows or facilitates harmful activities related to cybercrime.

Please be aware of the purposes of the servers you join. If servers you're in are posting content or engaging in behaviour that's in violation of our Guidelines, we strongly suggest that you report the content and leave; otherwise, there may be situations where we take action on your account in the future.

Sincerely,
Discord Trust & Safety

**Comment by ItsChasa** [comment]
racist, discord need to get a better help and support team

**Comment by ItsChasa** [comment]
> Hello,
> 
> 
> 
> Discord is focused on maintaining a safe and secure environment for our community. We've found your account to be in violation of our Terms of Service or Community Guidelines. As a result, we've disabled your account for the following reason:
> 
> 
> 
> Your account attempted to deceive others into providing their authentication token, or participated in servers dedicated to doing so.
> 
> 
> 
> Sincerely,
> 
> Discord Trust & Safety

just read it, discord is big brain with trust and safety team, tryna find any excuse to term people

**Comment by ItsChasa** [comment]
you making a new server?

**Comment by V4NSH4J** [comment]
> > Hello,
> > Discord is focused on maintaining a safe and secure environment for our community. We've found your account to be in violation of our Terms of Service or Community Guidelines. As a result, we've disabled your account for the following reason:
> > Your account attempted to deceive others into providing their authentication token, or participated in servers dedicated to doing so.
> > Sincerely,
> > Discord Trust & Safety
> 
> just read it, discord is big brain with trust and safety team, tryna find any excuse to term people

Ikr 😂 even Siegfried was banned for this...


> you making a new server?

https://guilded.gg/tos
Guilded server for now, till we make the discord one

**Comment by V4NSH4J** [comment]
New server:https://discord.gg/YxE3ymJbwX
