### ISSUE TITLE
Build For Mac M1 Chipset

### ISSUE THREAD

**Issue by FossilBlade** [V4NSH4J/discord-mass-DM-GO#490]
Would be great if we can have a prebuilt package for Mac M1 chipset as well

**Comment by ramy-git** [comment]
just build it lol

**Comment by itschasa** [comment]
> just build it lol

this, download go and dmdgo source code, make sure it's added to path, then do "go build" on command line in the same directory as the source code.

**Comment by V4NSH4J** [comment]
Hey the Darwin ARM64 builds in releases are for M1 Macs.
