### ISSUE TITLE
captcha error

### ISSUE THREAD

**Issue by rembrandt-h** [V4NSH4J/discord-mass-DM-GO#495]
![image](https://user-images.githubusercontent.com/76389351/162518406-ea282585-8448-4179-8a88-af98663cbd71.png)
i use newest version but still not working

**Comment by alikeremo** [comment]
Try to use capmonster or 2captcha

**Comment by SY573M404** [comment]
@alikeremo That's not the problem. If you look at the problematic code, it's relates to proxy and not to captcha itself
https://github.com/V4NSH4J/discord-mass-DM-GO/blob/a21d4742c0e9204b7c408dc2f41db143804ed69f/utilities/captcha.go#L62
`port, err = strconv.Atoi(strings.Split(in.Proxy, ":")[1])`

**Comment by LongTomForever** [comment]
> @alikeremo That's not the problem. If you look at the problematic code, it's relates to proxy and not to captcha itself
> 
> https://github.com/V4NSH4J/discord-mass-DM-GO/blob/a21d4742c0e9204b7c408dc2f41db143804ed69f/utilities/captcha.go#L62

It may be specified in the settings to use a proxy, but the proxies themselves are not in the proxies.txt file or are specified in the wrong format

**Comment by V4NSH4J** [comment]
> @alikeremo That's not the problem. If you look at the problematic code, it's relates to proxy and not to captcha itself
> 
> https://github.com/V4NSH4J/discord-mass-DM-GO/blob/a21d4742c0e9204b7c408dc2f41db143804ed69f/utilities/captcha.go#L62

He has either not put proxies or has put them in the wrong format. The only supported format is user:pass@ip:port or ip:port 
Although I should've handled the exception

**Comment by rembrandt-h** [comment]
> > @alikeremo That's not the problem. If you look at the problematic code, it's relates to proxy and not to captcha itself
> > https://github.com/V4NSH4J/discord-mass-DM-GO/blob/a21d4742c0e9204b7c408dc2f41db143804ed69f/utilities/captcha.go#L62
> 
> He has either not put proxies or has put them in the wrong format. The only supported format is user:pass@ip:port or ip:port Although I should've handled the exception

everything is working now, thanks for the help
