### ISSUE TITLE
api key does not exists

### ISSUE THREAD

**Issue by Alisha8141l** [V4NSH4J/discord-mass-DM-GO#496]
![Screenshot (146)](https://user-images.githubusercontent.com/87426877/162577837-c0a04cfe-a45d-4a43-abaa-a76f0daeba49.png)

**Comment by itschasa** [comment]
the api key you put in the config file isn't valid for the api you are using.

make sure you enter it correctly, and remember that the config is now a yml file.

**Comment by Alisha8141l** [comment]
i used the same file which is provided
![Screenshot (147)](https://user-images.githubusercontent.com/87426877/162583652-5da88525-8244-4b67-a806-4a53484b08ab.png)

**Comment by ayoubalaouikadiri** [comment]
Change you api key now, you shared it in the picture ..

**Comment by itschasa** [comment]
> Change you api key now, you shared it in the picture ..

@Alisha8141l make sure you do this

have you double checked that it is the same? sometimes with 2cap you need to reset the key. also make sure it's the customer key you are getting, not the worker key.

**Comment by V4NSH4J** [comment]
Hey, you're using the default key which I left in on accident, I already revoked it. You need to get your own key.

**Comment by Alisha8141l** [comment]
> Hey, you're using the default key which I left in on accident, I already revoked it. You need to get your own key.

please tell me how can i get my own key ?

**Comment by V4NSH4J** [comment]
https://2captcha.com
https://capmonster.cloud

**Comment by Alisha8141l** [comment]
> https://2captcha.com https://capmonster.cloud

is it free or paid ?

**Comment by itschasa** [comment]
> > https://2captcha.com https://capmonster.cloud
> 
> 
> 
> is it free or paid ?

captchas are paid, but they aren't too expensive. it's around $1-3 per 1000 captchas.

**Comment by Alisha8141l** [comment]
![Screenshot (152)](https://user-images.githubusercontent.com/87426877/162907966-70a54fe6-71e2-4603-a7f1-87469f4eb1ba.png)
I changed the captcha api but its still catching previous api which i removed from config.yml file
