### ISSUE TITLE
not an issue, just wanted to get some help

### ISSUE THREAD

**Issue by ItsChasa** [V4NSH4J/discord-mass-DM-GO#5]
can u add me on discord? i need some help with this, discord is for some reason sending encrypting or encoding successful responses. any ideas? I've used cookies, fingerprints, user-agents etc,

discord: chasa # 0001
without spaces, markdown is cool

**Comment by ItsChasa** [comment]
![image](https://user-images.githubusercontent.com/79016507/141599798-750253a9-62be-4626-be94-facf0a48326b.png)

**Comment by ItsChasa** [comment]
fixed

**Comment by V4NSH4J** [comment]
Solved on discord for anyone else looking for the solution to this. 
https://discord.com/channels/905121020430659594/905132747549458452/908886833247711284
Response was encoded in brotli, removing "br" from accepted encoding solved the issue
