### ISSUE TITLE
anti captcha service? 

### ISSUE THREAD

**Issue by jahanshahub** [V4NSH4J/discord-mass-DM-GO#509]
Can we get support for anti-catpcha.com?

**Comment by alikeremo** [comment]
dmdgo doesnt support anti-captcha.com anymore ı suggest you to apply for refund

**Comment by V4NSH4J** [comment]
DMDGO does not support anti-captcha anymore. Discord's new HCaptcha's are enterprise HCaptchas and Anti-Captcha does not support them.
<img width="1202" alt="Screenshot 2022-04-14 at 11 15 01 AM" src="https://user-images.githubusercontent.com/79518089/163321525-f92825d2-9fd5-4535-a697-adbdb862158e.png">
When they start supporting it, they'll be supported again.
