### ISSUE TITLE
Discord invite link / server down?

### ISSUE THREAD

**Issue by nisanb** [V4NSH4J/discord-mass-DM-GO#51]

**Comment by cChimney** [comment]
yes

**Comment by V4NSH4J** [comment]
Hi, yes the server got termed for the second time... We will make a new server tonight and update links everywhere

**Comment by cChimney** [comment]
sexy

**Comment by Cloudzik1337** [comment]
Col

**Comment by Cloudzik1337** [comment]
![image](https://user-images.githubusercontent.com/92876777/149353614-31334cbe-addd-4e29-826f-e9fbdabedf3c.png)
Any idea why it have high lock ratio

**Comment by Hunolog** [comment]
https://github.com/Itroublve/DiscordJoiner/blob/v5/TokenSettings.cs

might wane take a look there
ik its c# but you only need the request stuff so it might help you ¯\_(ツ)_/¯

**Comment by cyno66** [comment]
🚀🌕

**Comment by cChimney** [comment]
> ![image](https://user-images.githubusercontent.com/92876777/149353614-31334cbe-addd-4e29-826f-e9fbdabedf3c.png) Any idea why it have high lock ratio

seems fine

**Comment by V4NSH4J** [comment]
Guys please join our guilded server https://guilded.gg/tos while we figure out a discord one

**Comment by V4NSH4J** [comment]
New discord: https://discord.gg/YxE3ymJbwX
