### ISSUE TITLE
Bot closes abruptly

### ISSUE THREAD

**Issue by git-chao** [V4NSH4J/discord-mass-DM-GO#510]
The bot closes in using the version "Discord Mass DM GO v1.8.12".

Happens after I enter the Server ID then 1 then 0 then 3
![image](https://user-images.githubusercontent.com/69294315/163331738-0999633a-acc1-4314-8d94-4f81c96f51d9.png)

**Comment by misty00x** [comment]
I can confirm this error. 
I get the same thing with certain tokens. Not sure the cause but maybe V4NSH4J can take a look.

If you use that guys token above: OTU3NjI4NDYzODM2MTY4MjEy.YkF7Vw.sflcSs1mTm90dhBUUl42toYvWPk and try to join any server the program will crash with the same error. But if you manually connect to that token, it works fine.

**Comment by markus80809** [comment]
i got this too had no idea it was related to tokens tho.. thanks for figuring that part out. Now we gotta see why some tokens cause this and some dont.
I bought a bunch of tokens from different places and its happen to random ones.. about half of em tho

**Comment by V4NSH4J** [comment]
Hey, try out DMDGO v1.8.13

**Comment by markus80809** [comment]
This update fixed it for me ~~Resolved.

**Comment by git-chao** [comment]
Same, thanks!
