### ISSUE TITLE
can't parse my proxies

### ISSUE THREAD

**Issue by lukosevic** [V4NSH4J/discord-mass-DM-GO#512]
![Screenshot_81](https://user-images.githubusercontent.com/80982331/163458142-ca0f6dda-9a6d-468b-9e46-7bc3a6dba7f8.png)
 
 why's that? I am using IPROYAL proxies, I've whitelisted my IP.

**Comment by lukosevic** [comment]
I am using HTTP/HTTPS proxies in IP:PROXY format

**Comment by lukosevic** [comment]
Also tried in username:password@hostname:port but it says that wrong port.

**Comment by V4NSH4J** [comment]
Turn off proxy_for_captcha

**Comment by lukosevic** [comment]
> Turn off proxy_for_captcha
![Screenshot_83](https://user-images.githubusercontent.com/80982331/163459446-a637b622-f1ed-4bbf-88ae-5968e99421ea.png)

![Screenshot_84](https://user-images.githubusercontent.com/80982331/163459639-f833b047-afbb-4948-bf71-7d8c44113a30.png)

getting new error
