### ISSUE TITLE
About rate limit delay

### ISSUE THREAD

**Issue by thewisehound** [V4NSH4J/discord-mass-DM-GO#52]
Hi there, thanks for your project, it's amazing.

I'm not so sure about rate limit delay. On the FAQ you say limit is 10 new DMs every 10 minutes, but above there in "Token Quality & Functionality (Updated: 2nd Nov)" you mention about 50+ DMs for phone verified tokens.  Is this a daily limit or do you mean that after 50 DMs every token gets blocked?

Thanks for providing clarification.

**Comment by V4NSH4J** [comment]
Hi, the limits in token functionality are maximum possible DMs these tokens can send. After that, they get locked/disabled 


The rate limit delay is something completely different, due to how discord is structured, you can only send 10 new dms every 10 minutes.
