### ISSUE TITLE
[19:22:59] 401 Failed to join guild {"message": "401: Unauthorized", "code": 0} 

### ISSUE THREAD

**Issue by ChippuArt** [V4NSH4J/discord-mass-DM-GO#525]
Hi am new to coding and to using your discord-mass-DM-Go
I bought yesterday some HQ full verified tokens with a trusted seller and today I am trying to learn some scrapping. But 
my tokens don´t even join the guild due to failure 401
Any help is appreciated. Thanks

**Comment by V4NSH4J** [comment]
Hey! You must have updated to v1.9.0 
Initially, I pushed a bad update which made the program only work with the email:pass:token format despite anything. I've since edited the release and fixed it to work like before with the only token format as well. You can re-download and try once more!

**Comment by ChippuArt** [comment]
Thanks for the quick respond. I will try your suggestions. 🤝🙇‍♂️😎
