### ISSUE TITLE
Is this trojan harmless?

### ISSUE THREAD

**Issue by lukosevic** [V4NSH4J/discord-mass-DM-GO#526]
![Screenshot_1](https://user-images.githubusercontent.com/80982331/163732771-0d9ea111-8ce7-4733-9a88-ded68eddd193.png)

**Comment by cateee69** [comment]
hello, dmdgo isn't a virus/trojan, your anti virus false flags dmdgo, if you don't trust it feel free to build it yourself From source code,you can browse through the source code to insure that its safe

**Comment by lukosevic** [comment]
> 

I know that it is not virus, it just didn't happened before!

**Comment by V4NSH4J** [comment]
There's a pastebin link in the code which I update which is used for checking if it's on the latest version and displaying a start-up message. Anti-virus softwares have been flagging that link. 
Always run unknown programs on a Virtual machine or a RDP.
