### ISSUE TITLE
DM ON REACT PROBLEM

### ISSUE THREAD

**Issue by johnwatfun** [V4NSH4J/discord-mass-DM-GO#529]
Hey, my dm on react has a massive delay of one minute or 60000 ms and I need help since i want it to be as low as possible. Somebody please help me ASAP

**Comment by V4NSH4J** [comment]
Hey, In the new update I've turned down all the suspicion avoidance delays which were causing the massive delays. (It was configurable in config but no one understood what it was, fair enough though as I never explained why I added it)
It's been turned completely down, your DM speeds should be around 500-1000ms if no captcha is met. Good luck.
