### ISSUE TITLE
Token <token> failed to DM <userID>

### ISSUE THREAD

**Issue by NaiiTex** [V4NSH4J/discord-mass-DM-GO#53]
When using the Single DM spam mode, after choosing the number of threads and putting the userID, it shows me as a result : 
Token |token| failed to DM |userID|.

I tried to find out where the problem was, but didn't found anything, so i hope that you'll help me with this. 
Thanks a lot !

**Comment by NaiiTex** [comment]
Forget to say it, but my token is a email-verified token and the user id and the token are linked ( in the same ds server).

**Comment by V4NSH4J** [comment]
Hey, it could be that the DMs are closed

**Comment by NaiiTex** [comment]
Found the problem, it was a coma in front of content in the message.json file. Thanks a lot for the response!

**Comment by V4NSH4J** [comment]
> Found the problem, it was a coma in front of content in the message.json file. Thanks a lot for the response!

No worries, feel free to open another issue if you face any problems!
