### ISSUE TITLE
Error after adding prxoxies

### ISSUE THREAD

**Issue by shurjeelfayyaz1** [V4NSH4J/discord-mass-DM-GO#532]
<img width="654" alt="proxy" src="https://user-images.githubusercontent.com/94997952/163895756-8aa48000-4367-4d12-9ff5-4db3177ccbdd.PNG">
Getting this issue after adding proxies from proxiware

**Comment by V4NSH4J** [comment]
Authorize your IP on proxiware, if you're using a VPN, authorize the VPN IP.
