### ISSUE TITLE
Is there a way to convert token into email:pass:token format

### ISSUE THREAD

**Issue by ConutRBX** [V4NSH4J/discord-mass-DM-GO#535]
I have 1000 tokens but dont have the email or pass for it and I dont want to go through each token to retrieve it. Is there a way to convert the token into a email:pass:token format?

**Comment by itschasa** [comment]
if the password is the same for each token, then yes. but it's not in dmdgo

**Comment by V4NSH4J** [comment]
You can't retrieve a token's password from just the token. If you have their password elsewhere, you can get the email from the token and arrange all 3 in email:pass:token 
But the email is not used for any actions, so you might as well have any random string in place of it
