### ISSUE TITLE
Query with mass dm software

### ISSUE THREAD

**Issue by killerboy2007** [V4NSH4J/discord-mass-DM-GO#537]
Discord Mass DM GO, I need your help with the process. Are the below mentioned steps correct ?

1. Put token and proxy in software
2. Authenticate the IP to use Proxy
3. Convert Token format (option 6)
4. Join the Target server where mass dm needs to done.
5. Scrap Members (option 10) & offline scraper (option 3)

Someone told me that after Scraping Members, I should use option 1 (Invite Joiner) and send atleast 10 / 12 fake memebrs to the Target server

6. Now use option 2(mass dm), sub option 1(use message from file)
After that should I use advance setting or not ?

As I need to send mass dm to around 50k members, should I mass dm entire 50k members in one shot or in intervals ?

How many dms can a email verified token send ? (basic quality)

Should I buy email verified or email & mobile verified token?

**Comment by killerboy2007** [comment]
I use Dedicated proxy from 

https://proxyscrape.com/

**Comment by Johnybhiduri** [comment]
Dm me on discord i will help you to set it up and run it without any error-JohnyDAO🖤#5753
And send screenshot of this so that i could remember

**Comment by killerboy2007** [comment]
@V4NSH4J 

Kindly help

**Comment by killerboy2007** [comment]
@V4NSH4J

Dude, please help me. Just 2 minutes work for you.

**Comment by killerboy2007** [comment]
done
