### ISSUE TITLE
Dont understand how it works

### ISSUE THREAD

**Issue by Bobolistic45** [V4NSH4J/discord-mass-DM-GO#54]
Hello V4NSHJ,

I tried all my possible best to get this done but i dont understand how it works at ALL,
I've installed almost every software required by you yet i cant get to the bottom on how to set it up

Please I'm making this comment so you can help and guide me better on how to set it up And better still if i get some other people who can help me with this i will be glad 

My discord name is Roach#6224

Thanks

**Comment by V4NSH4J** [comment]
Hi, I'll make a video for updated version soon.

**Comment by Bobolistic45** [comment]
Aiit thank you
