### ISSUE TITLE
 Error while joining: max retries exceeded

### ISSUE THREAD

**Issue by davyguy** [V4NSH4J/discord-mass-DM-GO#544]
Hello everyone. Please I keep getting this error when I try joining a server on this recent update. Any clues where I can check?

**Comment by davyguy** [comment]
![image](https://user-images.githubusercontent.com/104029915/164077315-70d72288-3e60-4c27-931a-eb14720db7c5.png)

**Comment by Johnybhiduri** [comment]
Dm me on discord i will help you to set it up and run it without any error-JohnyDAO🖤#5753
And send screenshot of this so that i could remember

**Comment by V4NSH4J** [comment]
The config.yml file has changed, looks like you haven't updated it. Please download the latest config and put it in.
