### ISSUE TITLE
invalid status code while sending request error 400

### ISSUE THREAD

**Issue by babaoye** [V4NSH4J/discord-mass-DM-GO#55]
i keep getting invalid status code while sending request error 400 when i am sending single dm....and the user and i are in same server....what can possibly cause this??

**Comment by V4NSH4J** [comment]
Hi, error 400 is a malformed request. It can mean a few things: 
1) The token has never been websocketed 
2) The message format is wrong which is causing it to send empty messages 

Could you provide more information? Which version of DMDGO are you on and how did you set your message?

**Comment by babaoye** [comment]
i got it sorted out...i am using the latest version...thanks alot

**Comment by V4NSH4J** [comment]
👍 Feel free to open another issue if you face any difficulties.
