### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by poegod** [V4NSH4J/discord-mass-DM-GO#555]
Anyone else facing issues with anticaptcha?

**Comment by Alisha8141l** [comment]
> Hey! Everyone is having problems with Anti-Captcha right now. I'll implement and update if there's anything I can do.
![164287303-ced424d0-9727-4ac5-9991-00f2f1bf5370](https://user-images.githubusercontent.com/87426877/164911154-ad435bd9-30a0-4d4b-ac5f-880d78fece23.png)

**Comment by Alisha8141l** [comment]
i tried anti captcha even i tried capmonster but both not working.

**Comment by dcryptodev** [comment]
@Alisha8141l were you able to resolve this issue? I also tried on capmonster and it didn’t work
