### ISSUE TITLE
Great Update. Issue with scraping tool (Reactions)

### ISSUE THREAD

**Issue by PoLottoNFT** [V4NSH4J/discord-mass-DM-GO#56]
Hey I am trying to scrape based on reactions. It asks for reaction manually and I enter it in this format :thumbsup: for example and it just shuts down after i put that , what is the correct entry ?

Also I am wondering which option from the 3 can be set up to be watching new members being added all the time ?

I am seeing some really cool bots that are sending messages as soon as someone is verified in a server and the sender is not an admin or moderator. 

It sound like the offline scraper does that since it stays connected. Is it possible to have the scraper and message send both on at the same time this way as soon as someone joins they are sent a message ?

**Comment by V4NSH4J** [comment]
Hi, have you made sure that the token you're trying to scrape with is able to see the message you're trying to scrape?

Also have you tried with getting the reaction from the message?

Personally, I think that the new member DM is not done by re-scraping. When a new member joins a guild, and reacts to the message to gain access to the server, there is a gateway event like MESSAGE_REACTION_ADD so discord can increment the reaction count. Along with that, the user information is passed who clicks on it from where you can DM them. Re-scraping would be highly inefficient for achieving this

**Comment by notihamdutch** [comment]
quick question is there a way the tool can auto-dm the new users scraped from a particular reaction? thanks

**Comment by V4NSH4J** [comment]
> quick question is there a way the tool can auto-dm the new users scraped from a particular reaction? thanks

Ofcourse, whenever a user clicks on a reaction. Discord sends a MESSAGE_REACTION_ADD gateway event from where you can get the userid and DM them. A good structure for this would be having 1 token which listens for events and not use it for DMing so it doesn't get locked/flagged/banned and tokens from another list join the server and DM the user passes by the listener token.

**Comment by ChronoBrake** [comment]
`I am seeing some really cool bots that are sending messages as soon as someone is verified in a server and the sender is not an admin or moderator.`

It's will be cool if this tool will can spam to users who react on some message "like on verify message". You have sosomething in plan @V4NSH4J ?

Best Regards

**Comment by V4NSH4J** [comment]
> `I am seeing some really cool bots that are sending messages as soon as someone is verified in a server and the sender is not an admin or moderator.`
> 
> It's will be cool if this tool will can spam to users who react on some message "like on verify message". You have sosomething in plan @V4NSH4J ?
> 
> Best Regards



> 

Hi, no plans as of now. DMDGO is supposed to be for mass DMs. This isn't mass-dming exactly so I don't have plans in the near future of adding it.
