### ISSUE TITLE
Anti captcha now working

### ISSUE THREAD

**Issue by poegod** [V4NSH4J/discord-mass-DM-GO#567]

**Comment by poegod** [comment]
![image](https://user-images.githubusercontent.com/82784342/165060450-91269661-a17b-48ef-ae5d-f7b4458e6522.png)

**Comment by Shinyshiny347** [comment]
not working yet

**Comment by V4NSH4J** [comment]
As of writing this post, the captchas solved by most public solver APIs get your tokens flagged.
