### ISSUE TITLE
Error while setting messages: invalid character '\r' in string literal

### ISSUE THREAD

**Issue by Bjsavage234** [V4NSH4J/discord-mass-DM-GO#57]
How to fix?

**Comment by V4NSH4J** [comment]
Hi @Bjsavage234 do you face this when you set message in message.json or input it in console?

**Comment by kamajaph** [comment]
i also face this problem when getting messages from the message.json

**Comment by V4NSH4J** [comment]
> i also face this problem when getting messages from the message.json

I checked the guy who made the issue's message on guilded. It had an extra comma at the end was pressing enter instead of using \n to change line. Just ensure your message.json is correct or send it here for me to verify

**Comment by adonmax** [comment]
https://github.com/V4NSH4J/discord-mass-DM-GO/issues/63
