### ISSUE TITLE
INVITE - 404 Failed to join guild {"message": "404: Not Found", "code": 0}

### ISSUE THREAD

**Issue by AdamSendler1710** [V4NSH4J/discord-mass-DM-GO#570]
Hi again! Problem with the invite. the invite code is 100% valid
![invite](https://user-images.githubusercontent.com/104168540/165172487-ad729880-d9af-41c0-922a-bddb6578f034.png)

.

**Comment by itschasa** [comment]
don't include the "https://discord.gg/" part, only the code

**Comment by V4NSH4J** [comment]
Yes, only input the invite code. 
https://discord.gg/friendlynftserver becomes friendlynftserver 
Re-open if you still have a question!
