### ISSUE TITLE
Unable to process `evaluate`: debuggee is running

### ISSUE THREAD

**Issue by Iliasrahmouni** [V4NSH4J/discord-mass-DM-GO#572]
Guys please help when i enter the choice i want from the menu i get this error: Unable to process `evaluate`: debuggee is running.
any idea?
![Bild_2022-04-26_001344868](https://user-images.githubusercontent.com/51827091/165183650-104c2eae-6726-419a-84e7-0acdf7802496.png)

**Comment by itschasa** [comment]
try using the exe version, using "go build" in cmd

**Comment by V4NSH4J** [comment]
I think you might have accidentally tried to debug the code. There are detailed instructions in the readme if you want to build from source. If you just want to run the program without wanting to build, there are already pre-compiled binaries in the [releases](https://github.com/V4NSH4J/discord-mass-DM-GO/releases)
Re-Open if you have any questions left!
