### ISSUE TITLE
captcha problems

### ISSUE THREAD

**Issue by gang000** [V4NSH4J/discord-mass-DM-GO#578]
hi, i have fully verified discord tokens but there is a captcha error when joining a guild or dming someone

```
[22:54:01] Error while Solving Captcha: error 1 {"errorId":1,"errorCode":"ERROR_ZERO_BALANCE","errorDescription":"Account has zero balance","taskId":0}
```
this is the error i have a valid api key for capmonster
it also detects the captcha but cant solve it

**Comment by ChippuArt** [comment]
@gang000 it is recommended to use anti-captcha.com for the version 1.9.1 as far as I know. If you use 1.9.2 and you have issues you should give a feedback to the host V4SH4J. Kind regards

**Comment by testttbqwebg** [comment]
u need to add funds to ur capmonster account

**Comment by V4NSH4J** [comment]
You need to add funds to your capmonster.cloud account.
