### ISSUE TITLE
Message not loading [Error while setting messages: json: cannot unmarshal object into Go value of type []instance.Message]

### ISSUE THREAD

**Issue by Descatres** [V4NSH4J/discord-mass-DM-GO#587]
### I was trying to message me this, just to have fun:
```json
{
    "embed": {
        "title": "Hello!! 👋",
        "description": "We are name !\n",
        "color": 16065893,
        "url": "https://discord.gg/bsJGQHf6",
        "author": {
            "name": "Name",
            "url": "https://discord.com/",
            "icon_url": "https://unsplash.it/100"
        },
        "thumbnail": {
            "url": "https://unsplash.it/200"
        },
        "image": {
            "url": "https://unsplash.it/380/200"
        },
        "footer": {
            "text": "Name",
            "icon_url": "https://unsplash.it/100"
        },
        "fields": [
            {
                "name": "Visit our website for more information about the project!",
                "value": "[website.com](https://website.com/)"
            },
            {
                "name": "Check our socials!",
                "value": "[Twitter](https://twitter.com) and [Instagram](https://www.instagram.com)!",
                "inline": true
            },
            {
                "name": "Join our Discord!",
                "value": "> [Take me there!](https://discord.gg)",
                "inline": false
            }
        ]
    }
}
```
![image](https://user-images.githubusercontent.com/73725403/166116470-641ce958-2af4-4d1a-b5f5-73f6d9315448.png)
(the preview on the side seems nice and no errors appeared on the website)
### But I seem to be failing somewhere...
![image](https://user-images.githubusercontent.com/73725403/166116296-7f83b1c2-19ce-47ce-b424-e66cad4e704b.png)

### Any idea what can it be?

**Comment by Descatres** [comment]
got my response from [!575](https://github.com/V4NSH4J/discord-mass-DM-GO/issues/575)
I just had to create a link.

**Comment by Descatres** [comment]
# Update:
### I followed the teamplate on this repo for the embeds and ended up with this:
---
```json
{
    "title": "We are Name",
    "description": "Join our discord to know more about our project!\nWe hope you enjoy our work!",
    "redirect": "https://website.com/",
    "color": "#f7267d",
    "author": {
        "name": "Discord",
        "url": "https://discord.gg"
    },
    "provider": {
        "name": "Website",
        "url": "https://website.com/"
    },
    "image": {
        "thumbnail": false,
        "url": "https://ai-gen.club/img/gallery/All/Fantasy%20Rain%20forest%2014202256421747768151-200.png",
        "info": ""
    }    
}
```
---
Hope it helps!

**Comment by V4NSH4J** [comment]
Hey! A bit more details on this, Discord removed regular embeds, so now we're using links to send embeds. They don't support all fields like before, so you would have to follow the template. 
In your message.json you can only have the content field (which is a regular discord message) and you have to follow the format for that as well, as it's an array of messages, one message is sent at random from the list. 
Hope you have a bit more clarity!

**Comment by Descatres** [comment]
We ended up making our own embed using [this](https://stackoverflow.com/questions/59335731/how-to-create-own-embed-site-for-discord#:~:text=Put%20this%20HTML%20code%20at%20the%20top%20of%20your%20site.).
Thank you very much for your work!!
