### ISSUE TITLE
Massdm error

### ISSUE THREAD

**Issue by DaddyShank** [V4NSH4J/discord-mass-DM-GO#59]
when i try mdming, gives me a error and says status 400 bad request message read unauthorized info on errors on Github readme

**Comment by DaddyShank** [comment]
Version V1.0.6

**Comment by V4NSH4J** [comment]
Hi, 400 Unauthorized means your tokens have never been websocketed before. You can use a token onliner to fix them. There is one included in DMDGO V1.0.7 and higher.
