### ISSUE TITLE
Error with /tmp file? 

### ISSUE THREAD

**Issue by Knepala** [V4NSH4J/discord-mass-DM-GO#6]
![capture2](https://user-images.githubusercontent.com/55921163/141663254-66768bb6-a55e-4834-99ef-f9621e1cc2d1.png)

Hi I am trying to run the script and use the first option to add a server code, but I am getting the following error. 

I am completely new to Go so I have no idea what it means.

**Comment by V4NSH4J** [comment]
Hey! Please compile the program using `go build` and run the binary!
The program tries to find all the data - config, tokens, memberids relative to the binary. Doing `go run main.go` makes a temporary binary somewhere so it can't find all the files!

**Comment by Knepala** [comment]
I had already used 'go build' in the Directory. 

Which one is the binary, the one called Discord-Mass-dm-GO?

**Comment by V4NSH4J** [comment]
Yes
