### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VulcanBirdy** [V4NSH4J/discord-mass-DM-GO#60]
Everytime I try to use it I get some strange issue, it says Error while joining: invalid character e looking for beginning of value

**Comment by boubouleV** [comment]
Its because your ban ip use a vpn :D

**Comment by VulcanBirdy** [comment]
When it shows in red Error Code 4001; status 400 Bad Request; Message Unauthorized Does that mean they have dms off?

**Comment by V4NSH4J** [comment]
> When it shows in red Error Code 4001; status 400 Bad Request; Message Unauthorized Does that mean they have dms off?

This means your token isn't websocketed. Which basically means it has never connected to Discord Gateway after registering. You can use the token onliner and such tokens will start working. 
invalid character e looking for beginning of value is a cloudflare rate limit. error 1015. You will need to use VPN/Proxies
