### ISSUE TITLE
json cannot unmarshal object into Go value of type []utilities.Message

### ISSUE THREAD

**Issue by remixtoxik** [V4NSH4J/discord-mass-DM-GO#61]
when I choose the option message from file I get this error , what could be the cause?

**Comment by V4NSH4J** [comment]
Hi, in DMDGO V1.0.7 and above, we changed the message.json to an array of messages. Check out the readme for examples but basically you'll have to add a pair of [] around the whole message.

**Comment by remixtoxik** [comment]
> Hi, in DMDGO V1.0.7 and above, we changed the message.json to an array of messages. Check out the readme for examples but basically you'll have to add a pair of [] around the whole message.

My fault thank you!!
