### ISSUE TITLE
Hello Error When send Massage! help please

### ISSUE THREAD

**Issue by adonmax** [V4NSH4J/discord-mass-DM-GO#63]
i use the embed site
https://glitchii.github.io/embedbuilder/?editor=json
i design my massage and past in on json massage
and when send i get error
 Error while setting messages: json: cannot unmarshal object into Go value of type []utilities.Message
i try Add S to embed.
try [
see any video ans try and chance and alaways error!
also when i not make massage i just copy past from 
https://glitchii.github.io/embedbuilder/?editor=json
same error!
how i need write the massage to get work????

**Comment by V4NSH4J** [comment]
Hi, in DMDGO V1.0.7 and above we changed the message.json file to take an array of messages. Add a pair of [] around the whole message and it would fix the problem. You can checkout more about this in the readme file.

**Comment by adonmax** [comment]
just add [] on start and on the end??
not add S? or any thing 
please send me example of massage that work

**Comment by adonmax** [comment]
Error while setting messages: invalid character ':' after array element

**Comment by adonmax** [comment]
man please please!! just go the site! copy the massage and change it! let me see
i do on start [ and on end
also double also with S or without!
i spend 6 hours on that tool!!!
why anyone not just show example how the massage need to look???
also on readme is give u link to embed site! and is not work!!

**Comment by adonmax** [comment]
please repley with massage example change it for something work! i try any
{
    "content": "You can~~not~~ do `this`.```py\nAnd this.\nprint('Hi')```\n*italics* or _italics_     __*underline italics*__\n**bold**     __**underline bold**__\n***bold italics***  __***underline bold italics***__\n__underline__     ~~Strikethrough~~",
    "embed": {
        "title": "Hello ~~people~~ world :wave:",
        "description": "You can use [links](https://discord.com) or emojis :smile: 😎\n```\nAnd also code blocks\n```",
        "color": 4321431,
        "timestamp": "2022-01-17T06:00:34.458Z",
        "url": "https://discord.com",
        "author": {
            "name": "Author name",
            "url": "https://discord.com",
            "icon_url": "https://unsplash.it/100"
        },
        "thumbnail": {
            "url": "https://unsplash.it/200"
        },
        "image": {
            "url": "https://unsplash.it/380/200"
        },
        "footer": {
            "text": "Footer text",
            "icon_url": "https://unsplash.it/100"
        },
        "fields": [
            {
                "name": "Field 1, *lorem* **ipsum**, ~~dolor~~",
                "value": "Field value"
            },
            {
                "name": "Field 2",
                "value": "You can use custom emojis <:Kekwlaugh:722088222766923847>. <:GangstaBlob:742256196295065661>",
                "inline": false
            },
            {
                "name": "Inline field",
                "value": "Fields can be inline",
                "inline": true
            },
            {
                "name": "Inline field",
                "value": "*Lorem ipsum*",
                "inline": true
            },
            {
                "name": "Inline field",
                "value": "value",
                "inline": true
            },
            {
                "name": "Another field",
                "value": "> Nope, didn't forget about this",
                "inline": false
            }
        ]
    }
}

**Comment by adonmax** [comment]
Error while setting messages: invalid character ':' after array element
i try alll the options!
please just send example not explain to me what add!!

**Comment by V4NSH4J** [comment]
Why are you like this? There is literally examples in readme.
https://github.com/V4NSH4J/discord-mass-DM-GO#message-in-file

**Comment by adonmax** [comment]
oh thnx
i new on github
bro i do all the same i get error still
Error while setting messages: invalid character ':' after array element

**Comment by adonmax** [comment]
man can u please just send me the json from the site with fixed that need to work?? 
please

**Comment by adonmax** [comment]
> Why are you like this? There is literally examples in readme. https://github.com/V4NSH4J/discord-mass-DM-GO#message-in-file

man take the json from the site and do replece like the readme example and see is not work!
simple bro i ask if u can just send me example massage from the site not empty

**Comment by adonmax** [comment]
mann please help me
i will pay u!
why u cant just send example massage!!!?????????
