### ISSUE TITLE
can not join servers i get the issue 

### ISSUE THREAD

**Issue by undertaker8801** [V4NSH4J/discord-mass-DM-GO#64]
[22:11:06] Error while joining: invalid character 'e' looking for beginning of value
Error while unmarshalling body invalid character 'e' looking for beginning of value
[22:11:06] Error while joining: invalid character 'e' looking for beginning of value

**Comment by V4NSH4J** [comment]
You're rate limited. Use proxy/VPN.

**Comment by cChimney** [comment]
Why dont you make a proper error for that

**Comment by undertaker8801** [comment]
i just put fresh proxies in and still no luck nice program though thanks for creating

**Comment by undertaker8801** [comment]
![image](https://user-images.githubusercontent.com/87919338/149737805-2ffa94c1-5e5b-460b-9b00-88d0fa7657a1.png)
this is my issue

**Comment by V4NSH4J** [comment]
Please check if proxy_from_file is enabled
