### ISSUE TITLE
Error opening websocket

### ISSUE THREAD

**Issue by lolstephens** [V4NSH4J/discord-mass-DM-GO#65]
Error while opening websocket: failed to create websocket connection: error while waiting for ready event: error while unmarshalling incoming websocket message json: cannot unmarshal bool into Go struct field Event.d of type utilities.data

No idea what this means, program was working fine for an hour then get this error.

**Comment by V4NSH4J** [comment]
Discord just sends this when they want to close the websocket. Don't worry, it tries to reconnect on its own.

**Comment by lolstephens** [comment]
> Discord just sends this when they want to close the websocket. Don't worry, it tries to reconnect on its own.

Well, its making the program unusable, it's kind of an issue.

It's not a token issue as I just changed them, could it be the proxies or just discord rate limiting something?

**Comment by V4NSH4J** [comment]
> > Discord just sends this when they want to close the websocket. Don't worry, it tries to reconnect on its own.
> 
> Well, its making the program unusable, it's kind of an issue.
> 
> It's not a token issue as I just changed them, could it be the proxies or just discord rate limiting something?

I wanna know more about this. Which mode gave you this problem? How did it make it unusable? Like does it panic or something? And what's your config? Are you using proxy for gateway?

**Comment by lolstephens** [comment]
> > > Discord just sends this when they want to close the websocket. Don't worry, it tries to reconnect on its own.
> > 
> > 
> > Well, its making the program unusable, it's kind of an issue.
> > It's not a token issue as I just changed them, could it be the proxies or just discord rate limiting something?
> 
> I wanna know more about this. Which mode gave you this problem? How did it make it unusable? Like does it panic or something? And what's your config? Are you using proxy for gateway?

Mass DM advertiser is giving the issue. I am using about 60-80 tokens all which are still in good standing. I open mass dm advertisers then all tokens get Websocketed then shortly after I get this error and roughly 4-5 messages get sent out then the program closes. The error is very persistent and goes away by itself that's why im thinking it's discord rate limiting something. The current settings I am using will be below.

    "individual_delay": 60,
    "rate_limit_delay": 60,
    "offset": 100,
    "skip_completed": true,
    "remove_dead_tokens": true,
    "remove_completed_members": true,
    "stop_dead_tokens": true,
    "check_mutual": false,
    "friend_before_DM": false,
    "online_tokens": true,
    "online_scraper_delay": 1000,
    "call": false,
    "proxy_from_file": true,
    "max_dms_per_token": 0,
    "receive_messages": true,
    "use_proxy_for_gateway": false

**Comment by V4NSH4J** [comment]
> > > > Discord just sends this when they want to close the websocket. Don't worry, it tries to reconnect on its own.
> > > 
> > > 
> > > Well, its making the program unusable, it's kind of an issue.
> > > It's not a token issue as I just changed them, could it be the proxies or just discord rate limiting something?
> > 
> > 
> > I wanna know more about this. Which mode gave you this problem? How did it make it unusable? Like does it panic or something? And what's your config? Are you using proxy for gateway?
> 
> Mass DM advertiser is giving the issue. I am using about 60-80 tokens all which are still in good standing. I open mass dm advertisers then all tokens get Websocketed then shortly after I get this error and roughly 4-5 messages get sent out then the program closes. The error is very persistent and goes away by itself that's why im thinking it's discord rate limiting something. The current settings I am using will be below. (If you'd like we can troubleshoot via discord or guilded would probably be much easier to do and replicate via screenshare or screenshots. Reached out on both if you're wanting to take that route)
> 
> ```
> "individual_delay": 60,
> "rate_limit_delay": 60,
> "offset": 100,
> "skip_completed": true,
> "remove_dead_tokens": true,
> "remove_completed_members": true,
> "stop_dead_tokens": true,
> "check_mutual": false,
> "friend_before_DM": false,
> "online_tokens": true,
> "online_scraper_delay": 1000,
> "call": false,
> "proxy_from_file": true,
> "max_dms_per_token": 0,
> "receive_messages": true,
> "use_proxy_for_gateway": false
> ```

We can take that route, for now please disable "online_tokens"
