### ISSUE TITLE
Proxies / Invite Joiner issues

### ISSUE THREAD

**Issue by Creepo4ek** [V4NSH4J/discord-mass-DM-GO#651]
I'm trying to accept a guild invite from multiple accounts.
I am using a proxy in the _PQxoUD:BPDNtm@180.157.82.242:8672_ (example) format  (I have more than 100 proxies in the txt list)
Also set proxy_from_file: true 

After starting the program and about twenty actions performed, error 40007 appears
After that My IP is blocked and I cannot accept the invitation even from my computer

As I understand it, proxies are simply not used (although they are working). Is there a solution to this problem or any advice?

P.S. This is the best discord software I have ever used.

**Comment by V4NSH4J** [comment]
Hey, thank you for your kind words. 
How many accounts are you using? and are you using the same proxy on your computer as well?

**Comment by Creepo4ek** [comment]
> 

I mean that the program does not use proxies that I entered in txt .
The whole process happens from my IP , so it gets banned quickly

**Comment by V4NSH4J** [comment]
If `proxy_from_file` is enabled in your config, it would use proxies from `proxies.txt` 

However, if your config is broken (Even 1 field is broken the whole config won't be detected) the default value for proxy_from_file is false which would result it in not using proxies and you'd get rate limited.

I'd recommend downloading the config from github again, and changing your values carefully. Make sure strings are enclosed in "", integers are not strings and bools are spelled correctly if you change anything. Or send your config here so I can check it out!

**Comment by Creepo4ek** [comment]
> If `proxy_from_file` is enabled in your config, it would use proxies from `proxies.txt`
> 
> However, if your config is broken (Even 1 field is broken the whole config won't be detected) the default value for proxy_from_file is false which would result it in not using proxies and you'd get rate limited.
> 
> I'd recommend downloading the config from github again, and changing your values carefully. Make sure strings are enclosed in "", integers are not strings and bools are spelled correctly if you change anything. Or send your config here so I can check it out!



> If `proxy_from_file` is enabled in your config, it would use proxies from `proxies.txt`
> 
> However, if your config is broken (Even 1 field is broken the whole config won't be detected) the default value for proxy_from_file is false which would result it in not using proxies and you'd get rate limited.
> 
> I'd recommend downloading the config from github again, and changing your values carefully. Make sure strings are enclosed in "", integers are not strings and bools are spelled correctly if you change anything. Or send your config here so I can check it out!

Thanks a lot , fixed it ! There was a problem on my side
I'm sorry if I bothered you
