### ISSUE TITLE
Can I somehow use fingerprints ?

### ISSUE THREAD

**Issue by Creepo4ek** [V4NSH4J/discord-mass-DM-GO#659]
Can I somehow use FingerprintSwitcher in the process?

**Comment by V4NSH4J** [comment]
If you're talking about the FingerprintSwitcher of Bablosoft, no because DMDGO is entirely based on requests and not browser emulation.

**Comment by Creepo4ek** [comment]
> If you're talking about the FingerprintSwitcher of Bablosoft, no because DMDGO is entirely based on requests and not browser emulation.

Okay, thanks a lot
