### ISSUE TITLE
an idea

### ISSUE THREAD

**Issue by toprak1881** [V4NSH4J/discord-mass-DM-GO#666]
just make like an option that you chance your pfp every second without like spamming the command
i mean like  that you run dmdgo say like 25
then you give the program 10  pfps and it changes all the time and with name too like
your normal name theben with the command it changer 100 time all the time
it would be funny
if you dont understand this vid show u what i mean and do it with names bios and pfps
https://www.youtube.com/watch?v=aVIMga0zILs

**Comment by Skwll** [comment]
Never heard of rate limits? You can't change your pfp that fast...

**Comment by toprak1881** [comment]
no but thanks that u saying that
