### ISSUE TITLE
How to only DM new users？

### ISSUE THREAD

**Issue by GR-coin** [V4NSH4J/discord-mass-DM-GO#68]

**Comment by V4NSH4J** [comment]
DMDGO as of V1.0.7 does not have such an option.

**Comment by remixtoxik** [comment]
> DMDGO as of V1.0.7 does not have such an option.

could it be a paid version, because I have the same question

**Comment by V4NSH4J** [comment]
> > DMDGO as of V1.0.7 does not have such an option.
> 
> could it be a paid version, because I have the same question

No plans of making a commercial paid version of DMDGO as of now.

**Comment by ChronoBrake** [comment]
+1 see option like "DM Advertiser when someone join/react in server"

**Comment by V4NSH4J** [comment]
It does not come under mass dms.

**Comment by KORKI1** [comment]
I have python program which sends dm to only new users on reaction. Discord: KORKI#5945
