### ISSUE TITLE
Verifying while using invite joiner bot

### ISSUE THREAD

**Issue by Marijnvanrossen** [V4NSH4J/discord-mass-DM-GO#69]
Hi there, can I make my bots verify themself by using your system? Like interacting with emojis? Or do I have to do that manually?

**Comment by V4NSH4J** [comment]
Hi, the program has an option for "Reaction Adder", check it out.

**Comment by Marijnvanrossen** [comment]
Thanks, what tokens will react to it? Will only the tokens react to it that are in the tokens.txt? and what do I need to fill in buy Enter Emoji

**Comment by V4NSH4J** [comment]
Tokens in tokens.txt which are in the server and can see the channel will react to it.
It will ask you for some information, once filled, you can get emojis from the message. Pressing the number to the left of the emoji will start adding the reactions.

**Comment by Marijnvanrossen** [comment]
It's a custom emoji, what do I fill in then?

**Comment by V4NSH4J** [comment]
Hi, if it's a custom emoji. Right click the emoji and copy the link. In the link there would be a long number towards the end, that's the emoji ID copy that. And you would have to input emojiname:emojiID in this format only. 

Simpler way would be to get reactions from message, you won't have to do all this

**Comment by PoLottoNFT** [comment]
Hey thank you for everything. What if besides the reaction the server requires to accept terms and conditions does that matter ?

**Comment by Marijnvanrossen** [comment]
So for example META:emoji-85923 ?

**Comment by V4NSH4J** [comment]
> Hey thank you for everything. What if besides the reaction the server requires to accept terms and conditions does that matter ?

The community screening is automatically bypassed by the invite joiner 



> So for example META:emoji-85923 ?

No looks wrong, why not get the emoji from message?

**Comment by PoLottoNFT** [comment]
thank you I will try that !

**Comment by Marijnvanrossen** [comment]
Can u please send me a screen shot of what to enter, I feel like I've tried everything and I really need this to work. discord = Marijn#7811

**Comment by V4NSH4J** [comment]
> Can u please send me a screen shot of what to enter, I feel like I've tried everything and I really need this to work. discord = Marijn#7811

You have to enter the emoji name and emoji ID in this format
emojiname:emojiID 
Join the guilded support server and find me

**Comment by Marijnvanrossen** [comment]
I dmed you there
