### ISSUE TITLE
What's causing 401 Failed to join guild on new tokens?

### ISSUE THREAD

**Issue by LawmanL** [V4NSH4J/discord-mass-DM-GO#698]
This happens, and after I log into the new accs using their emails and passwords the tokens for each one of them is changed. If i paste the changed tokens into the tokens.txt the same thing happens again. What causes this, and is there a specific time limit that I need to wait for on new tokens before using them?

**Comment by LawmanL** [comment]
![Screenshot 2022-06-28 172140](https://user-images.githubusercontent.com/95107067/176295226-a8258451-12ba-4d52-b923-6df6ada28f2f.png)

**Comment by foxzsz** [comment]
Have you tried logging into the tokens manually and then trying to join a server?

**Comment by LawmanL** [comment]
> Contributor

I can join servers if i log into them manually. (There is no captcha) However its annoying logging into each one and joining servers. I think waiting for the tokens to age more might fix it. If anyone else is having this problem, I'd recommend you to let them age a little (a couple of days) and join manually whenever you need to use them.
