### ISSUE TITLE
How many dm's can be sent from a single token if the token is from a number+email verified account?

### ISSUE THREAD

**Issue by muhitrhn** [V4NSH4J/discord-mass-DM-GO#70]

**Comment by V4NSH4J** [comment]
Hi, it largely depends on the age of the account. But if it has a phone number & an email and it is NOT flagged. It should be able to get around 100+ (max dms does not count closed dms)

**Comment by muhitrhn** [comment]
How do I know if the account is flagged or not?

**Comment by V4NSH4J** [comment]
Log into it on discord, send some DMs by hand. Flagged accounts would get locked/disabled on joining server and sending 2-3 dms

**Comment by muhitrhn** [comment]
Understood. Is there any way to prevent account from getting flagged?

**Comment by V4NSH4J** [comment]
> Understood. Is there any way to prevent account from getting flagged?

The kind of flagging I mean is done at registering. Maybe bad phone number or over-used email domain or bad proxy. Things like that.
