### ISSUE TITLE
I have a question about Reaction scraper, everything works fine but 

### ISSUE THREAD

**Issue by remixtoxik** [V4NSH4J/discord-mass-DM-GO#71]
Hi when I run the reaction scraper the Ids are saved in the order from 1 to 9 but is it possible to scrape the reactions from new to old ?
I was just wondering, by the way thank you for your project it is amazing!!!

**Comment by V4NSH4J** [comment]
<3 Thank you 
This is not possible with DMDGO right now. But in code, it should be possible. It could input the current reaction count and scrape them backwards so you'd get the newest **registered** discord users.

**Comment by remixtoxik** [comment]
> But

Is there a way I could talk to u in private?

**Comment by V4NSH4J** [comment]
> > But
> 
> Is there a way I could talk to u in private?

V6NSH4J#1511

**Comment by KORKI1** [comment]
I have python program which sends dm to only new users on reaction. Discord: KORKI#5945
