### ISSUE TITLE
JOIN TOOL PATCHED

### ISSUE THREAD

**Issue by pizzalover32** [V4NSH4J/discord-mass-DM-GO#714]
sup nerds join the telegram at https://t.me/tosviolators

**Comment by V4NSH4J** [comment]
There was some patch around 12 hours ago.

I have fixed the joiner in 1.10.2 since then. 

https://github.com/V4NSH4J/discord-mass-DM-GO/releases/tag/v1.10.2

Re-open if you have any more questions!
