### ISSUE TITLE
Error Code 40001

### ISSUE THREAD

**Issue by Massyck** [V4NSH4J/discord-mass-DM-GO#74]
<img width="1257" alt="Schermata 2022-01-18 alle 16 02 02" src="https://user-images.githubusercontent.com/97940125/149967426-dae4f0e8-25da-43d9-9499-533e52fa4dfc.png">
I configured everything and entered the tokens. Before starting the dm spam I checked if the tokens were actually valid and they are. Once started I get this error, how can I solve it?

**Comment by V4NSH4J** [comment]
Hi, your token has never been websocketed after generation. Use token onliner included in DMDGO v1.0.7 and above once, it should solve your problem.

**Comment by Massyck** [comment]
ok the initial problem seems to have solved it for me, but now this shows up
<img width="1512" alt="Schermata 2022-01-18 alle 17 42 06" src="https://user-images.githubusercontent.com/97940125/149980291-c9ebdc48-e213-4be4-9733-f85f65949e26.png">
:

**Comment by V4NSH4J** [comment]
DMs are closed or you don't have a mutual server.

**Comment by Massyck** [comment]
so to send a message to people inside a certain server I have to get my tokens into that server?

**Comment by V4NSH4J** [comment]
Yes

**Comment by Educational-Por** [comment]
How do I setup this file lol?

**Comment by V4NSH4J** [comment]
> How do I setup this file lol?

Read the readme.
