### ISSUE TITLE
Cant scrape 

### ISSUE THREAD

**Issue by DigitalKek** [V4NSH4J/discord-mass-DM-GO#75]
Hello! I tried to scrape some servers to mass dm but when I do I just get an error where it keeps scrapping 0 members. When I do it offline it collects some then closes itself and doesn't save it. Please help

**Comment by SablyTv** [comment]
Tried with different proxies?

**Comment by DigitalKek** [comment]
Theres no place to even use proxies

**Comment by SablyTv** [comment]
in /input/proxies.txt
You either need to buy some proxies or find free ones. I recommend buying them at https://proxiware.com/

**Comment by V4NSH4J** [comment]
^ Also try the new update, redownload/build.

**Comment by grx7** [comment]
use the Discum version, works well
