### ISSUE TITLE
Writes: "Cannot send messages to this user" 

### ISSUE THREAD

**Issue by DMG-G** [V4NSH4J/discord-mass-DM-GO#76]
Writes: "Cannot send messages to this user". I understand that his private messages are closed. Or it is possible that verification on the server has not been passed (The account that parses is verified on the server).

**Comment by V4NSH4J** [comment]
The DMs should be closed or your token which tried to DM might not share a mutual server. If there is a problem with verification you'll get an error "Channel Verification too high".

**Comment by DMG-G** [comment]
> The DMs should be closed or your token which tried to DM might not share a mutual server. If there is a problem with verification you'll get an error "Channel Verification too high".

And how to close the DM on your token? So that my token uses a shared server?

**Comment by DMG-G** [comment]
> > What should I do to make the token use a shared server?
> 
> Use Invite joiner and join them to the server

Thanks, cool update

**Comment by V4NSH4J** [comment]
<3

**Comment by DMG-G** [comment]
> <3

Can you tell me where you buy tokens, give a link please )
