### ISSUE TITLE
Error with captcha, but actually not with captcha

### ISSUE THREAD

**Issue by Qunik** [V4NSH4J/discord-mass-DM-GO#766]
With invites, DMDGO writes that it has found a captcha.
I modified the code and looked at the full body of the response and it says that in order to invite you need to have a new version of the discord.
I started looking into the code and found that the [link](https://pastebin.com/raw/pGgMQGiJ) to get XSuperProperties  is not valid. Pastbin writes this "This paste has been considered potentially harmful." Apparently you need to find a more reliable place to store data or make DMDGO get it yourself

instance/instance.go

**Comment by HumzzCopper** [comment]
does anyone know any other discord token joiners that work?

**Comment by Qunik** [comment]
> does anyone know any other discord token joiners that work?

Пиздец чел, у тебя в публичном репозитории 600 токенов
