### ISSUE TITLE
Doesn't anycaptcha.com support it?

### ISSUE THREAD

**Issue by oreilyciracoc** [V4NSH4J/discord-mass-DM-GO#776]
https://prnt.sc/k-p4wt7tL3WE 

Doesn't anycaptcha.com support it?

**Comment by pizzalover32** [comment]
not supported

**Comment by V4NSH4J** [comment]
It is unsupported as it doesn't support HCaptcha Enterprise which Discord uses. Here's a list of Captcha APIs supported in DMDGO V1.11.0+

1) rucaptcha.com
2) 2captcha.com
3) capmonster.cloud
4) anti-captcha.com
5) invisifox.com
6) capcat.xyz
7) captchaai.com 

All are fully supported but results aren't guaranteed and vary from service to service. 

Re-open if you have any other queries.

**Comment by FF5252** [comment]
captchaai.com I putted that into the config and it doesnt work
