### ISSUE TITLE
What proxy format do you use with iproyal?

### ISSUE THREAD

**Issue by ArcadePlayed** [V4NSH4J/discord-mass-DM-GO#777]
![5e052c8039a924a874f0093178b6d62197fb28ea](https://user-images.githubusercontent.com/81503780/181861363-8b139f01-65e1-4ef5-b3ab-6f4b3ee5da86.png)

???

**Comment by pizzalover32** [comment]
last one

**Comment by V4NSH4J** [comment]
The format for proxies is username:password@hostname:port or hostname:port. The IP address can also be used in place of hostname as required by some proxy services. So yes, the last one should work. 

Re-open if you have any other queries.
