### ISSUE TITLE
Program shuts down when running Mass DM Advertiser.

### ISSUE THREAD

**Issue by serialstrifer** [V4NSH4J/discord-mass-DM-GO#78]
Running from provided .exe file on windows. Every other function works (including single DM spam) except when the program attempts to Mass DM, wherein it forcibly closes before any other messages, error or otherwise, can come up.

I have ensured valid:
-tokens 
-proxies
-config files
-member ids 
-antivirus/firewall exceptions

Apologies in advance for a possibly basic question with a simple solution.

**Comment by V4NSH4J** [comment]
Hi @serialstrifer I had incorrectly pushed a wrong version of the binary last night at 3AM. This morning, I uploaded a fixed version. Re-download it and try it out.

**Comment by serialstrifer** [comment]
Ah perfect and in working order thank you very much!
