### ISSUE TITLE
Error while getting cookies 

### ISSUE THREAD

**Issue by Hiddenpasha** [V4NSH4J/discord-mass-DM-GO#780]
![photo_2022-07-30_23-04-25](https://user-images.githubusercontent.com/104562573/181936000-a396f428-4a55-424c-9cf2-00b2b0a1b029.jpg)
What should i do about that >_<

**Comment by foxzsz** [comment]
Use better proxies

**Comment by V4NSH4J** [comment]
It looks like it timed-out while waiting for a response from discord, this can happen if you're using slow proxies. You can increase proxy timeout in config so it waits longer for the response (By default it is 30 seconds)

If after increasing timeout, it still times-out the request, you'll have to find better/faster proxies to use or go proxyless. 

Re-open if you have any other queries.
