### ISSUE TITLE
add invisifox support

### ISSUE THREAD

**Issue by xhuloo** [V4NSH4J/discord-mass-DM-GO#801]
### Put the following in the title of your Issue:

`[Question]` for a general question.
> Be specific, people can't help you if we don't know what you are talking about

`[Bug]` for unexpected error/behavior on the program.
> Please include your:
> - DMDGO version (shown on title screen)
> - Whether you built from source or downloaded a release
> - Your operating system.

## Explain your question/bug below:

this is a good idea

**Comment by V4NSH4J** [comment]
Hey, invisifox is already supported by DMDGO. To use invisifox, add your API key in the config and set the API to 'invisifox.com'

Re-open if you have any other questions

**Comment by xhuloo** [comment]
> Hey, invisifox is already supported by DMDGO. To use invisifox, add your API key in the config and set the API to 'invisifox.com'
> 
> Re-open if you have any other questions

hey invisifox doesnt really work, not solving the captcha
