### ISSUE TITLE
Cannot start scrape anymore *sadface* 

### ISSUE THREAD

**Issue by Sl33ker** [V4NSH4J/discord-mass-DM-GO#82]
When I start " python scrape.py"

I get this:
"Retrieving Discord's build number...
Could not retrieve discord build number.
list index out of range"

and then it continues string of this for awhile:
------------------------------------------------------------------------------------------------------------------

Begins here:
[+] (<discum.start.login.Login->getXFingerprint) Response <- b'\xef\xbf\xbdP\x07\x00\xef\xbf\xbd\x14\xef\xbf\xbd?V\xef\xbf\xbdO\xef\xbf\xbd\xef\xbf\xbdD\x1e\xef\xbf\xbd=N\tX\x01\x1d\x10V\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xce\xa7u\x1ea{*e+\xef\xbf\xbd+\x0c\x08\xef\xbf\xbdp\xef\xbf\xbd*\xef\xbf\xbd\xef\xbf\xbdE\xef\xbf\xbd(\xef\xbf\xbd&\xef\xbf\xbd\x0e\xef\xbf\xbd\xef\xbf\xbd+\xef\xbf\xbd\x15\x13k\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdr\x13-\xef\xbf\xbd\xef\xbf\xbd+\xef\xbf\xbd\x04\x16X\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x7fo\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd~\xef\xbf\xbd\xef\xbf\xbd\x7f\xef\xbf\xbd\xef\xbf\xbd_\x7f\xef\xbf\xbd\xef\xbf\xbd\x7f\xef\xbf\xbd\xef\xbf\xbd{\xef\xbf\xbd\xef\xbf\xbd\xc4\x90\xef\xbf\xbd0\xef\xbf\xbd*\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xdd\xaf\xef\xbf\xbd\xef\xbf\xbd\xe5\xaf\xbf\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdF0\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x0f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd?\xef\xbf\xbd\xef\xbf\xbdC\xde\x9e\xef\xbf\xbd\xef\xbf\xbd/\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd?\xef\xbf\xbd\xef\xbf\xbdo\x7f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd^?\xef\xbf\xbd12]{4\xef\xbf\xbdW=/<\xef\xbf\xbdw\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\n\xef\xbf\xbd\x0eg>/=/>\xef\xbf\xbd%C\x15-\xef\xbf\xbd\x1e\xef\xbf\xbd7\xef\xbf\xbd\xef\xbf\xbd\x17\xd0\x9bs\
Traceback (most recent call last):
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\Desktop\discord-mass-DM-GO-main\scrape.py.txt", line 10, in <module>
    bot = discum.Client(token='MjU0NTM2OTEyMjYwMzAwODAw.YbDoUQ.sa8Nv0tDOV2zVaDNZikUc4PQ8oM')
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\start\login.py", line 38, in getXFingerprint
    xfingerprint = reqxfinger.json().get('fingerprint')
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] �P�¶�?V�O��D▲�=N   X☺↔►V�����Χu▲a{*e+�+
�p�*��E�(�&���+�§‼k���r‼-��+�♦▬X���o����~����_����{��Đ�0�*���ݯ��寿����F0���������?��Cޞ��/���?��o�������^?�12]{4�W=/<�w�����
�g>/=/>�%C§-�▲�7��↨Лs☺9�§�_1;7~.�p<.,�xv↓�$��g'��{����↔��ǵ�4����Kg�p��o�◄���#�:,�/͝����↓m♠:�ݪ�� �i�+6�Ydq҆0��z�gk�3W`�m���dx{‼�D�
�Th��ÓF&p▬����#���M
I�d-◄�C↨x��`WM>�����;j�►8r�ig�{^���M�z∟{"0U�↑J%►j"x
M�I�4���o�ݞ=�\�3S�f~���*<�6}1R1�‼��߼۟��♥: 0
-------------------------------------------Ends Here-----------------------------------------------------------

If anyone has a solution for this that'll be wonderful.

Thank you!

screenshot:
![sad day for me](https://user-images.githubusercontent.com/98061640/150229789-85799905-cf7a-48df-8b23-3d50bf3cc4fa.png)

**Comment by dtsrgb** [comment]
1) install `pip install discum` on desktop (on your terminal it will be: `C:\Users\Jordan cd Desktop pip install discum` )
2) your file should be **scrape.py** not _scrape.py.txt_
