### ISSUE TITLE
Shoud the ja3 needed in config file as it has fingerprint.json file?

### ISSUE THREAD

**Issue by searchingforcode** [V4NSH4J/discord-mass-DM-GO#825]
Hello you have added single ja3 in config file but is it needed ? Or should i remove it? As there is fingerprints.json file for multiple fingerprints. Thanks

### Put the following in the title of your Issue:

`[Question]` for a general question.
> Be specific, people can't help you if we don't know what you are talking about

`[Bug]` for unexpected error/behavior on the program.
> Please include your:
> - DMDGO version (shown on title screen)
> - Whether you built from source or downloaded a release
> - Your operating system.

**Comment by pizzalover32** [comment]
fingerprints.json is for the new mass dm (option24) you can add your fingerprint ua and x props in config if you're using option 2 to mass dm.
