### ISSUE TITLE
[Feedback Wanted] How are you liking the new update?

### ISSUE THREAD

**Issue by V4NSH4J** [V4NSH4J/discord-mass-DM-GO#84]
Hey guys, it has been a few days since the initial roll-out of V1.0.7, there have been 6+ minor updates since then patching multiple bugs and stuff. Make sure you're always using the latest versions! As I am approaching the end of dusting up everything with V1.0.7, I'd like you to share your experiences which can be useful in more fixes and features!

**Comment by pscpc** [comment]
Hello, this was amazing update. Like name and pfp changer omg. Just 1 problem, i got error like this: "Error while setting messages: json: cannot unmarshal object into Go value of type []utilities.Message". What can i do about it

**Comment by pscpc** [comment]
> 

Okay guys i got it. Add "[" before the all text and "]" at the end.
Before
![Screenshot_1](https://user-images.githubusercontent.com/56173496/150417724-3d86d4d3-ba4e-40bc-a386-e1b4d0bb78b4.png)
![Screenshot_2](https://user-images.githubusercontent.com/56173496/150417743-744e1c12-3ee9-4dd7-a809-31a623591d25.png)

After
![Screenshot_3](https://user-images.githubusercontent.com/56173496/150417759-758eb0e7-0617-4886-b900-e3bf9ea5a8d2.png)
![Screenshot_4](https://user-images.githubusercontent.com/56173496/150417763-3e768a22-fb0a-41d8-8e25-1b07f628725d.png)

**Comment by theroney** [comment]
hi, memberid's is not updated when you close the program while dm, is there a chance to update it when we close it manually?

**Comment by V4NSH4J** [comment]
> hi, memberid's is not updated when you close the program while dm, is there a chance to update it when we close it manually?

There is no way of knowing when you'll close it hence no way of updating it, but something can be written to update the file live.
