### ISSUE TITLE
 Error while joining: invalid character

### ISSUE THREAD

**Issue by dtsrgb** [V4NSH4J/discord-mass-DM-GO#85]
Thanks a lot for such a nice tool - appreciate your amazing skills✌️

Right after I run joiner mode I got this type of error. Any suggestions?
Screenshot:
![image](https://user-images.githubusercontent.com/89306625/150418534-5d00123e-254e-458c-9127-372110cd4bb2.png)

```
Error while joining: invalid character 'e' looking for beginning of value
Error while unmarshalling body invalid character 'e' looking for beginning of value
```

**Comment by dtsrgb** [comment]
Ok, trying the solution from here: https://github.com/V4NSH4J/discord-mass-DM-GO/issues/64

**Comment by V4NSH4J** [comment]
Yes, it is rate limited. Use a VPN or use proxies

**Comment by grx7** [comment]
what is the format to put urls into invite.txt for mass joining from file?

**Comment by V4NSH4J** [comment]
One invite code on each line 
Not links. Just the end part (the code)
