### ISSUE TITLE
Can't write to memberids/completed/failed

### ISSUE THREAD

**Issue by ASpaark** [V4NSH4J/discord-mass-DM-GO#87]
When I run the Mass DM advertiser or Scraper, whenever it tries to write to memberids/completed/failed .txt files it comes up saying "Access is Denied". I have tried running PowerShell and Command Prompt as administrator and have made sure the correct permissions have been given to the files but it still gives the same error. Any ideas? Thanks.

**Comment by V4NSH4J** [comment]
It's something to do with read/write permissions on your computer, try looking it up

**Comment by Y234333** [comment]
Try disabling your antivirus, that worked for me (McAffe, Avast, Malwarebytes).
