### ISSUE TITLE
403 Failed to join guild {"message": "Unknown Message", "code": 10008}

### ISSUE THREAD

**Issue by Paudideueye** [V4NSH4J/discord-mass-DM-GO#887]
Getting this error on most of my tokens with joiner. All tokens are 1-7 years aged and HQ.
Using proxies and everything. If I join the server manually on browser it only asks for captcha (error 400), here on dmdgo it gives error 403 with this unknown message type of error

**Comment by njho** [comment]
Did you manage to solve this?
