### ISSUE TITLE
Big Skidd

### ISSUE THREAD

**Issue by Privxx** [V4NSH4J/discord-mass-DM-GO#9]
you are big skidd ;( 
sad times

**Comment by V4NSH4J** [comment]
@Privxx Please mention where I skidded from in the next 24 hours.

**Comment by Privxx** [comment]
Quiet skid paki skid boy UwU

**Comment by V4NSH4J** [comment]
> Quiet skid paki skid boy UwU

You and your friend are just racist no skill losers, stop spamming my issues and get a job.

**Comment by Privxx** [comment]
This guy is a skid

**Comment by V4NSH4J** [comment]
> This guy is a skid

You can't prove it can you? You're the skid among us two lmao. Loser.
