### ISSUE TITLE
Message Send Successed But Embed content display

### ISSUE THREAD

**Issue by confesseur** [V4NSH4J/discord-mass-DM-GO#91]
hello , I used the embed message in message.json to send the message, and it was sent successfully, but what I see in the browser is only a single-line text message in the content, and the rest of the embed messages have disappeared, what is going on? , can you help me, thanks

**Comment by cChimney** [comment]
send message.json here

**Comment by confesseur** [comment]
`[{
    "content": "You can~~not~~ do `this`.```py\nAnd this.\nprint('Hi')```\n*italics* or _italics_     __*underline italics*__\n**bold**     __**underline bold**__\n***bold italics***  __***underline bold italics***__\n__underline__     ~~Strikethrough~~",
    "embed": {
        "title": "Hello ~~people~~ world :wave:",
        "description": "You can use [links](https://discord.com) or emojis :smile: 😎\n```\nAnd also code blocks\n```",
        "color": 4321431,
        "timestamp": "2022-01-21T15:15:16.985Z",
        "url": "https://discord.com",
        "author": {
            "name": "Author name",
            "url": "https://discord.com",
            "icon_url": "https://unsplash.it/100"
        },
        "thumbnail": {
            "url": "https://unsplash.it/200"
        },
        "image": {
            "url": "https://unsplash.it/380/200"
        },
        "footer": {
            "text": "Footer text",
            "icon_url": "https://unsplash.it/100"
        },
        "fields": [
            {
                "name": "Field 1, *lorem* **ipsum**, ~~dolor~~",
                "value": "Field value"
            },
            {
                "name": "Field 2",
                "value": "You can use custom emojis <:Kekwlaugh:722088222766923847>. <:GangstaBlob:742256196295065661>",
                "inline": false
            },
            {
                "name": "Inline field",
                "value": "Fields can be inline",
                "inline": true
            },
            {
                "name": "Inline field",
                "value": "*Lorem ipsum*",
                "inline": true
            },
            {
                "name": "Inline field",
                "value": "value",
                "inline": true
            },
            {
                "name": "Another field",
                "value": "> Nope, didn't forget about this",
                "inline": false
            }
        ]
    }
}]`

**Comment by V4NSH4J** [comment]
Hi, the field's name is "embeds" and not "embed". Embeds is an array of the embed object. Please check the example provided in readme. 
You'd have to change the name of the field and add a pair of [] around it.

**Comment by confesseur** [comment]
hello， I use embeds to repleaces embed it happened json error , when is use below case , it still display embed content:
`[{"content":"This is Content","embeds":[{"title":"This is title"}]}]`

the embeds content display , if not  add " [ ] " , the send error
