### ISSUE TITLE
Tool now bans all my tokens

### ISSUE THREAD

**Issue by ReinV2** [V4NSH4J/discord-mass-DM-GO#92]
Was working fine, but now suddenly it bans all my tokens or claims them as "invalid" even though they work.

**Comment by V4NSH4J** [comment]
Hi, it might be that you were rate limited. Have you tried using a different checker or proxies with DMdgo?

**Comment by drizzy009** [comment]
Not working here

**Comment by V4NSH4J** [comment]
> Not working here

Good to know, if you ever need help feel free to make an issue detailing your situation.
