### ISSUE TITLE
Scrape from reacts crashes exe

### ISSUE THREAD

**Issue by pscpc** [V4NSH4J/discord-mass-DM-GO#93]
I'm scraping from react, at first its scraping with no error. But then when i want to save the id's to "memberids.txt" (say 'y' to question) 15 seconds later its crashes. Then i have to scrape again.

**Comment by pscpc** [comment]
Update: It write the ID's to "input\memderids.txt" but not write in "scraped\557xxxxxxxxxxxxxx412.txt"

**Comment by V4NSH4J** [comment]
Hi, do you have the scraped folder?

**Comment by pscpc** [comment]
> Hi, do you have the scraped folder?

Yes

**Comment by V4NSH4J** [comment]
Could you run from a command prompt and send me the error it outputs before it crashes

**Comment by pscpc** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/56173496/150643971-9a474153-3a64-4298-bffd-ea48c3437cc0.png)

**Comment by pscpc** [comment]
looks like it has range while

**Comment by pscpc** [comment]
![image](https://user-images.githubusercontent.com/56173496/150645302-b499b752-b518-498f-86eb-2099f00aba78.png)
another server

**Comment by pscpc** [comment]
My directory is on "G:\Diğer bilgisayarlar\Dizüstü Bilgisayarım\Desktop\New\What\scrape\"

**Comment by V4NSH4J** [comment]
> My directory is on "G:\Diğer bilgisayarlar\Dizüstü Bilgisayarım\Desktop\New\What\scrape"

Hi, which version of DMDGO are you on? Could you try the latest one so I can match which line it's crashing on?

**Comment by pscpc** [comment]
> > My directory is on "G:\Diğer bilgisayarlar\Dizüstü Bilgisayarım\Desktop\New\What\scrape"
> 
> Hi, which version of DMDGO are you on? Could you try the latest one so I can match which line it's crashing on?

windows_amd64_dmdgo_v1.0.7.4. You released v1.0.7.5 i saw it now. i will try later on that version

**Comment by V4NSH4J** [comment]
Try it out, let me know which line it is. I just did a scrape to test and it didn't crash so I'm not sure.

**Comment by V4NSH4J** [comment]
Hey, sorry for this. I have identified and fixed the issue. Its updated in the source code and I'll drop a release too soon
