### ISSUE TITLE
Can't send embed DM with the new update

### ISSUE THREAD

**Issue by Arkandes** [V4NSH4J/discord-mass-DM-GO#94]
When I try to mass DM it gives me this error: 
Error while setting messages: json: cannot unmarshal object into Go value of type []utilities.Message

**Comment by V4NSH4J** [comment]
Hi, the message.json file structure has been changed a bit. You have to enclose your whole message in a pair of [] as we added support for adding multiple messages to message.json from which one message is randomly sent. You can also see the examples from the readme file.

**Comment by Arkandes** [comment]
I can't see what is wrong, sorry. Could tell me what's wrong? Here's the code:
{
    "content": "Benvenuto nella **White-List** ufficiale di **ORGVSM**.",
    "embeds": [{
        "title": "www.orgvsm.com",
        "description": "Ti contattiamo per informarti che è appena iniziata la **Private Sale** per mintare\nil primo  **ORGVSM Meta-Pass**, una chiave per accedere ad un nuovo mondo. \nDa oggi abbiamo iniziato a riempire i primi posti della **White-List** selezionando \nalcuni **membri** in modo casuale, **tu sei uno di questi**.",
        "color": 3092414,
        "url": "https://orgvsm.netlify.app/",
        "author": {
            "name": "ORGVSM 2.0",
            "url": "https://orgvsm.netlify.app/",
            "icon_url": "https://i.postimg.cc/QxMvJ49v/fae9a51cc16725f0862dc6aaa0b6e704.png"
        },
        "thumbnail": {
            "url": ""
        },
        "image": {
            "url": "https://i.postimg.cc/4NX50Ppg/black-orgvsm-meta-pass.jpg"
        },
        "footer": {
            "text": "ORGVSM By Edwin Basha",
            "icon_url": "https://i.postimg.cc/nhy5ZnRt/instadp-orgvsm-full-size.jpg"
        },
        "fields": [
            {
                "name": "MINT",
                "value": "Blockchain\nSupply\nPrivate Mint Price\nMax Per Wallet\nPrivate Sale",
                "inline": true
            },
            {
                "name": "INFO",
                "value": "Ξ\n3 0 0 0\n0 . 1 5 Ξ\n5 NFT\n[Disponibile](https://orgvsm.netlify.app/)\n",
                "inline": true
            },
            {
                "name": "UTILITIES",
                "value": "ORGVSM Meta Store\nHuman Events x Milan\nPrivate Collection Access + Content\nRELIGION Project\n\nIl tuo nome si colorerà di giallo nel giro di pochi giorni.",
                "inline": false
            }
        ]
    }]
}
