### ISSUE TITLE
New Version of DMDGO 

### ISSUE THREAD

**Issue by xTer1vS** [V4NSH4J/discord-mass-DM-GO#945]
## DMDGO v1.20.1
- fixed the problems that everyone knows
- Fixed and optimized joiner (added delay)
- Fixed detections
- Fixed Mass DM (unflagged with new fingerprints)
- Added new captcha solvers (btw u can add ur own)

- I put fingeprints pack if this gest a flag again, just replace it on fingerprints.json

![image](https://github.com/user-attachments/assets/b957be3b-fdb5-446d-a0d4-32f44eb57f66)

My telegram @AgingTokens

**Comment by V4NSH4J** [comment]
Source code not available, probably a rat. Please do not download.
