### ISSUE TITLE
Embed message isn't working - HELP

### ISSUE THREAD

**Issue by shreD133** [V4NSH4J/discord-mass-DM-GO#95]
Well when i try to send embed message with links the bot execute only ''content'' and yes i renamed "embed" to "embeds": [{ 
![image](https://user-images.githubusercontent.com/98200142/150623724-351a32d2-7a64-4a71-8894-3bb30e51372c.png)
 and that's the bottom 
![image](https://user-images.githubusercontent.com/98200142/150623742-b9dfb18e-4e95-4d89-9496-d983b41432de.png)
That's the result: 
![image](https://user-images.githubusercontent.com/98200142/150623777-f4e7299d-598b-42a4-82ef-c6d736723027.png)

Please help

**Comment by V4NSH4J** [comment]
Yes because the embed is wrong. You're using an embed field without actually making the fields array

**Comment by PoLottoNFT** [comment]
No i can confirm message templates that were working fine on Mon , Tues , Wed have stopped working and are only sending the first line !

**Comment by songbaizhi** [comment]
I have the same problem!! It worked yesterday, it doesn't work today

**Comment by PoLottoNFT** [comment]
The embed in the readme doesn't work anymore either. 

Did discord change something ?

**Comment by shreD133** [comment]
True, yesterday this worked for me

**Comment by shreD133** [comment]
To be exact 4 hours ago i was able to send embed. Nothing has changed from my side and now isn't working. Hopefully you have answer for this

**Comment by PoLottoNFT** [comment]
Someone just told me its a discord patch. Is there a workaround or are embeds gone for good ?

**Comment by shreD133** [comment]
We will wait and see what's next, i'm with tight hands now :(

**Comment by V4NSH4J** [comment]
You guys are right, I just tried the default embed message and it appears that discord has removed embed support for self-bots.

**Comment by songbaizhi** [comment]
So there is no way to send embedded messages now? ;_;

**Comment by V4NSH4J** [comment]
> So there is no way to send embedded messages now? ;_;

I'm afraid not, I will still try a few things and get a confirmation from others.

**Comment by shreD133** [comment]
That's sad, i may sound stupid but i have no idea how to send normal message with link etc. Can you please tell me how to do it properly? Thanks in advance :)

**Comment by V4NSH4J** [comment]
> That's sad, i may sound stupid but i have no idea how to send normal message with link etc. Can you please tell me how to do it properly? Thanks in advance :)

Just put the message how you'd write it on discord in the "content" field and use \n to change lines

**Comment by PoLottoNFT** [comment]
The \n works really good actually. Is there a way to shorten links in content ?

**Comment by V4NSH4J** [comment]
> The \n works really good actually. Is there a way to shorten links in content ?

If you mean hyperlinking, we can't do that in embeds. If you meant shortening the URL, then use a URL shortener like https://bit.ly

**Comment by V4NSH4J** [comment]
> Can we add images to the content messages since we can't send the embed messages again.

Ofcourse you can, the content field is what is sent normally when you send messages on discord. You can add anything there which you're normally able to send on discord.

**Comment by ciribo-sys** [comment]
is there any tag for adding images? something like that i guess ?

img: <img src='/path/to/img'>

**Comment by ciribo-sys** [comment]
"img: <img src='/path/to/img'>"

**Comment by ciribo-sys** [comment]
i can't sort it out , could you please help me ?

**Comment by mint-nft** [comment]
I have the same problem as you ,
yesterday it works good.

**Comment by V4NSH4J** [comment]
> I have the same problem as you , yesterday it works good.

Discord completely removed embeds, now only message content.

**Comment by grx7** [comment]
@V4NSH4J I just saw someone spammed with embedded message, not sure how he did it. here's a message. https://imgur.com/a/0GlAPGT Any idea how he did it?

**Comment by V4NSH4J** [comment]
> @V4NSH4J I just saw someone spammed with embedded message, not sure how he did it. here's a message. https://imgur.com/a/0GlAPGT Any idea how he did it?

It's their website, when you send links they get embedded too so you're able to arrange some data like that.

**Comment by grx7** [comment]
> > @V4NSH4J I just saw someone spammed with embedded message, not sure how he did it. here's a message. https://imgur.com/a/0GlAPGT Any idea how he did it?
> 
> It's their website, when you send links they get embedded too so you're able to arrange some data like that.

Got it. Very smart.

**Comment by seanthakid** [comment]
> > > @V4NSH4J I just saw someone spammed with embedded message, not sure how he did it. here's a message. https://imgur.com/a/0GlAPGT Any idea how he did it?
> > 
> > 
> > It's their website, when you send links they get embedded too so you're able to arrange some data like that.
> 
> Got it. Very smart.

do you know how to construct a message that looks like the one from the picture? Lol discord sucks :/

**Comment by shreD133** [comment]
> > I have the same problem as you , yesterday it works good.
> 
> Discord completely removed embeds, now only message content.

Someone just send me embed message, new update again?

**Comment by seanthakid** [comment]
> > > @V4NSH4J I have the same problem as you , yesterday it works good.
> > 
> > 
> > Discord completely removed embeds, now only message content.
> 
> Someone just send me embed message, new update again?

can you attach a picture?

**Comment by V4NSH4J** [comment]
> > > @V4NSH4J I have the same problem as you , yesterday it works good.
> > 
> > 
> > Discord completely removed embeds, now only message content.
> 
> Someone just send me embed message, new update again?

It's their website. The regular embeds are gone.

**Comment by manisakurdu** [comment]
is it still not working?

**Comment by V4NSH4J** [comment]
> is it still not working?

Regular userbot embeds are gone so ofcourse it's still not working.
