### ISSUE TITLE
Error Code: 50006; Status: 400 Bad Request; Message: Cannot send an empty message [10]

### ISSUE THREAD

**Issue by DMG-G** [V4NSH4J/discord-mass-DM-GO#96]
Yesterday I sent this message everything was fine, today I can not send it

**Comment by PoLottoNFT** [comment]
Yes something is wrong with the messages. Only my first line is sending "content" the rest of the message isnt sending. And my team and I were wondering why no one was joining our discord anymore !

**Comment by DMG-G** [comment]
In another message only text works for me too. Embed does not work

**Comment by shreD133** [comment]
Same bro, just opened thread because of this. Only first line is sending "content" the rest embeds links isnt sending.

**Comment by V4NSH4J** [comment]
I just tested out a message, it appears discord may have removed embed support for userbots.

**Comment by DMG-G** [comment]
> 

Is there any way around this problem?

**Comment by V4NSH4J** [comment]
> > 
> 
> Is there any way around this problem?

I don't think so.
