### ISSUE TITLE
Option to work with proxies with password.

### ISSUE THREAD

**Issue by GhostGkali** [V4NSH4J/discord-mass-DM-GO#97]
for example:

edge.uwu.com:7777:sdsqr-ssdssdR_q12yaqdt-cc-us-sessid-cQ47Vv:nk0te123

**Comment by V4NSH4J** [comment]
Hi the format is user:pass@ip:port

**Comment by GhostGkali** [comment]
Can you change the order?

or be able to add the same format?

I would really appreciate it

ip:port:username:password

**Comment by GhostGkali** [comment]
My proxies only work this way.

**Comment by V4NSH4J** [comment]
> My proxies only work this way.

You can change the order of your proxies, it will work. I'm not going to be changing the default order the program uses. If you're using some proxy service, you'll have an option there to get your proxies in a different format.

**Comment by V4NSH4J** [comment]
> My proxies only work this way.

No, you can rearrange them and they will work
