### ISSUE TITLE
anyone else having an issue with the scaper? It outputs continuously but never stops. Nothing is ever inputed into the text  file.

### ISSUE THREAD

**Issue by seanthakid** [V4NSH4J/discord-mass-DM-GO#99]

**Comment by V4NSH4J** [comment]
Discum scraper?

**Comment by seanthakid** [comment]
Yes. The code is continuously running and dosnt stop. Because of this it also never puts anything into the txt file. I can attach some pictures if you would like :)

**Comment by seanthakid** [comment]
![465CC117-2477-4B52-A268-DDFE65278AAB](https://user-images.githubusercontent.com/96969678/150669065-13add80a-cde6-4834-b932-acf841e9062a.jpeg)

**Comment by V4NSH4J** [comment]
I don't think it's scraping, it's just connected to websocket and receiving gateway events. Have you tried using the scraper in-built into DMDGO V1.0.7 and above?

**Comment by seanthakid** [comment]
This is the scraper from above

**Comment by seanthakid** [comment]
Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?

**Comment by V4NSH4J** [comment]
> This is the scraper from above

Please try the DMDGO Scraper. 



> Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?

I'm not sure, if you want help with this scraper, you should make an issue on [Discum](https://github.com/Merubokkusu/Discord-S.C.U.M)

**Comment by seanthakid** [comment]
> > This is the scraper from above
> 
> Please try the DMDGO Scraper.
> 
> > Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?
> 
> I'm not sure, if you want help with this scraper, you should make an issue on [Discum](https://github.com/Merubokkusu/Discord-S.C.U.M)

I do not see a scraper function in the DMDGO version 1.7.0.5 download

**Comment by V4NSH4J** [comment]
> > > This is the scraper from above
> > 
> > 
> > Please try the DMDGO Scraper.
> > > Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?
> > 
> > 
> > I'm not sure, if you want help with this scraper, you should make an issue on [Discum](https://github.com/Merubokkusu/Discord-S.C.U.M)
> 
> I do not see a scraper function in the DMDGO version 1.7.0.5 download

Option 10; there is a scraper function.

**Comment by seanthakid** [comment]
> > > > This is the scraper from above
> > > 
> > > 
> > > Please try the DMDGO Scraper.
> > > > Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?
> > > 
> > > 
> > > I'm not sure, if you want help with this scraper, you should make an issue on [Discum](https://github.com/Merubokkusu/Discord-S.C.U.M)
> > 
> > 
> > I do not see a scraper function in the DMDGO version 1.7.0.5 download
> 
> Option 10; there is a scraper function.

ok it successfully scraped, but I cannot find where it places the member ids. Do you know where it is?

**Comment by V4NSH4J** [comment]
> > > > > This is the scraper from above
> > > > 
> > > > 
> > > > Please try the DMDGO Scraper.
> > > > > Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?
> > > > 
> > > > 
> > > > I'm not sure, if you want help with this scraper, you should make an issue on [Discum](https://github.com/Merubokkusu/Discord-S.C.U.M)
> > > 
> > > 
> > > I do not see a scraper function in the DMDGO version 1.7.0.5 download
> > 
> > 
> > Option 10; there is a scraper function.
> 
> ok it successfully scraped, but I cannot find where it places the member ids. Do you know where it is?

DMDGO scraper puts them in memberids.txt 
Discum, the script from the YouTube video saves them in the users.txt file

**Comment by seanthakid** [comment]
> > > > > > This is the scraper from above
> > > > > 
> > > > > 
> > > > > Please try the DMDGO Scraper.
> > > > > > Is there a reason why it’s just connecting to web sockets and not scraping? If so, do you know if there is a fix?
> > > > > 
> > > > > 
> > > > > I'm not sure, if you want help with this scraper, you should make an issue on [Discum](https://github.com/Merubokkusu/Discord-S.C.U.M)
> > > > 
> > > > 
> > > > I do not see a scraper function in the DMDGO version 1.7.0.5 download
> > > 
> > > 
> > > Option 10; there is a scraper function.
> > 
> > 
> > ok it successfully scraped, but I cannot find where it places the member ids. Do you know where it is?
> 
> DMDGO scraper puts them in memberids.txt Discum, the script from the YouTube video saves them in the users.txt file

Im using the DMDGO scraper. It is working but I checked the memberids.txt in the input folder and there is nothing there after it scrapes. Thank you so much for the help.
